"""Hand-judged CALIB_JUDGMENTS for CUAD v4t-tuned Protocol B calibration.

All 632 non-refusal answer entries scored 1-by-1 (claude-opus-4.7-1m).
Score scale: {0.0, 0.25, 0.5, 0.75, 1.0}
Key = qid minus "cuad__v4t-tuned__calibration__" and "__seed42"
Only non-zero entries are stored; 0.0 falls through to default in judge script.
"""

CALIB_JUDGMENTS_PARTIAL: dict[str, tuple[float, str]] = {
    # ── Entries 1–97 ────────────────────────────────────────────────────────
    "doc31_qa4__after37": (1.0, "Gold '5 years from Effective Date'; pred '5 years after Effective Date' — equivalent."),
    "doc40_qa0__after40": (1.0, "Exact match on 'Intellectual Property Agreement'."),
    "doc39_qa15__after49": (0.5, "Non-transferable concept present; pred adds wrong-contract anti-assignment framing."),
    "doc0_qa17__after75": (0.25, "Insurance concept present; pred adds bilateral framing and wrong-contract details."),
    "doc68_qa7__after75": (0.75, "Anti-assignment concept correct; pred says bilateral while gold is Contractor-only."),
    "doc76_qa4__after81": (0.75, "4-year initial term captured; pred omits auto-renewal."),
    "doc9_qa10__after83": (0.25, "TFC concept present; wrong party scope and notice period."),
    "doc43_qa17__after85": (0.25, "Insurance concept present; pred gives wrong amount and CGL details."),
    "doc87_qa2__after89": (1.0, "Exact match on 'December 3rd, 2018'."),
    "doc30_qa16__after99": (0.5, "Non-sublicense concept present; pred gives consent-based framing instead of absolute prohibition."),
    "doc69_qa5__after109": (1.0, "Match on 'laws of the State of California'."),
    "doc21_qa6__after109": (0.75, "Anti-assignment consent correct; omits lender carve-out."),
    "doc19_qa7__after110": (1.0, "Exact match on '90 days written notice'."),
    "doc57_qa16__after112": (0.75, "Non-transferable identified; pred incorrectly adds consent mechanism."),
    "doc11_qa10__after118": (0.75, "Anti-assignment concept correct; pred adds M&A exceptions not in gold."),
    "doc31_qa6__after121": (1.0, "Exact match on '30 days prior'."),
    "doc1_qa6__after123": (0.5, "Anti-assignment concept correct; gold heavily redacted."),
    "doc120_qa8__after123": (0.75, "Audit right correct; pred quotes gold then adds wrong-contract content."),
    "doc51_qa5__after124": (0.25, "TFC concept present; wrong restriction and notice period."),
    "doc51_qa6__after134": (0.75, "Anti-assignment consent correct; pred bilateral vs Broker-Dealer-only."),
    "doc11_qa14__after143": (0.75, "Both say 12-month warranty; different delivery trigger."),
    "doc83_qa11__after168": (0.75, "Anti-assignment concept correct; pred adds void consequence."),
    "doc8_qa19__after174": (0.5, "Audit right concept present; pred vague with no specific detail."),
    "doc96_qa5__after174": (1.0, "Exact match on 'law of the State of New York'."),
    "doc161_qa14__after178": (0.25, "Audit concept present; pred gives wrong-contract quality oversight."),
    "doc11_qa8__after179": (0.25, "No-solicit concept present; pred omits liquidated damages."),
    "doc50_qa9__after180": (0.25, "CoC concept partially present; pred gives wrong mechanism."),
    "doc53_qa5__after183": (0.25, "CoC concept present; pred gives different notification mechanism."),
    "doc115_qa11__after185": (0.5, "Non-transferable concept present; anti-assignment framing used."),
    "doc92_qa4__after186": (0.75, "Two-year duration correct; pred adds specific dates from wrong contract."),
    "doc135_qa8__after191": (0.75, "Anti-assignment consent correct; pred omits reasonableness qualifier."),
    "doc27_qa0__after192": (0.25, "Partial name match; pred misses 'DOMAIN NAME AND' prefix."),
    "doc148_qa4__after193": (1.0, "Exact match on '3 years from Effective Date'."),
    # ── Entries 98–193 ──────────────────────────────────────────────────────
    "doc192_qa13__after195": (0.75, "Non-transferable correctly identified with IAC/Affiliates; lacks worldwide/royalty-free detail."),
    "doc95_qa5__after196": (0.25, "Year-to-year renewal concept correct; pred gives wrong termination mechanism."),
    "doc191_qa16__after198": (0.5, "IP infringement uncapped liability concept present; pred adds wrong-contract carve-outs."),
    "doc77_qa10__after203": (0.5, "Anti-assignment concept correct; pred adds M&A/affiliate exceptions not in gold."),
    "doc29_qa0__after205": (0.75, "Document name 'CONSULTING AGREEMENT' correct; pred adds full exhibit identifier."),
    "doc190_qa0__after206": (0.75, "Document name 'JOINT VENTURE AGREEMENT' correct; pred adds exhibit identifier."),
    "doc153_qa12__after206": (0.75, "Non-transferable Cisco software correctly identified; pred cites Section 8.2."),
    "doc185_qa11__after211": (0.75, "M&A assignment without consent exception correctly captured; minor framing difference."),
    "doc15_qa4__after215": (0.75, "Anti-assignment concept correct; gold absolute restriction, pred implies consent."),
    "doc123_qa5__after215": (0.25, "Year-to-year renewal correct; pred gives wrong notice period (30 vs 60 days)."),
    "doc153_qa12__after219": (0.25, "Non-transferable concept partially present through anti-assignment."),
    "doc121_qa9__after220": (0.25, "Audit right concept present; wrong parties — Zogenix/Distributor vs Owner/Operator."),
    "doc112_qa3__after221": (0.25, "10-year duration concept correct; specific computed date unverifiable."),
    "doc35_qa4__after222": (0.75, "One-year duration correct; different trigger — delivery vs initial period."),
    "doc133_qa0__after222": (0.25, "Partial name match; pred says 'Maintenance Agreement' only."),
    "doc206_qa9__after227": (1.0, "Exact match on 'may not be assigned...without prior written consent of the other'."),
    "doc76_qa11__after228": (0.5, "Non-transferable concept correct; pred adds wrong-contract Changepoint/Customer details."),
    "doc54_qa15__after230": (0.25, "License restriction concept partially captured; pred gets sublicensable nature wrong."),
    "doc72_qa8__after231": (0.75, "Anti-assignment correct; pred omits explicit void consequence."),
    "doc214_qa8__after232": (0.25, "Termination right present; gold truncated, pred cites different section."),
    "doc190_qa0__after233": (1.0, "Exact match on 'JOINT VENTURE AGREEMENT'."),
    "doc215_qa0__after234": (1.0, "Exact match on 'JOINT FILING AGREEMENT'."),
    "doc11_qa0__after237": (1.0, "Exact match on 'STRATEGIC ALLIANCE AGREEMENT'."),
    "doc224_qa10__after238": (0.5, "Audit rights concept correct; bilateral vs APOLLO-only; different sections."),
    "doc231_qa0__after240": (0.75, "Document name 'JOINT FILING AGREEMENT' correct; pred adds full exhibit identifier."),
    "doc125_qa7__after242": (0.5, "Consequential damages exclusion concept correct; pred makes it bilateral and adds cap."),
    "doc102_qa5__after242": (0.25, "TFC concept correct; pred gives bilateral vs Microsoft-only, and specific period."),
    "doc128_qa15__after243": (0.25, "No-sublicense partially addressed; pred gives anti-transfer framing."),
    "doc229_qa4__after245": (1.0, "Near-exact match on 'laws of the State of New York without recourse to conflicts of law'."),
    "doc151_qa13__after245": (0.75, "Consequential damages exclusion correct; pred adds extra carve-outs and cap."),
    "doc129_qa8__after245": (0.25, "12-month post-term no-solicit concept present; gold is truncated after colon."),
    "doc245_qa1__after246": (0.75, "Correct parties named (Pfizer and Exact/EXACT SCIENCES); pred gives formal names."),
    "doc77_qa13__after247": (0.25, "License limitation concept partially present; pred doesn't specifically say non-transferable."),
    "doc47_qa10__after248": (0.75, "CoC consent concept correct; pred gives anti-assignment framing covering mergers."),
    "doc38_qa16__after248": (0.75, "Anti-assignment with CoC exception correct; pred doesn't specify CoC as exception."),
    "doc250_qa5__after250": (0.25, "TFC concept correct; wrong party scope and notice period."),
    "doc55_qa9__after252": (0.5, "No-solicit-of-employees concept correct; pred adds wrong post-termination period."),
    "doc43_qa16__after255": (0.5, "Consequential damages excluded concept correct; different carve-outs."),
    "doc79_qa11__after255": (0.25, "Named additional insured concept correct; wrong parties and missing notice details."),
    "doc80_qa6__after256": (0.75, "Anti-assignment concept correct; pred adds explicit consent + void."),
    "doc214_qa14__after260": (0.25, "Audit concept correct; pred is vague with no specifics."),
    "doc89_qa5__after262": (1.0, "Exact match on '60 days' notice period."),
    # ── Entries 194–289 ─────────────────────────────────────────────────────
    "doc76_qa5__after265": (0.75, "Annual auto-renewal correctly captured; pred adds 60-day notice not specified in gold."),
    "doc108_qa24__after265": (0.5, "Insurance obligation concept correct; pred says bilateral vs Aimmune-only."),
    "doc123_qa5__after267": (0.75, "Year-to-year renewal and 60-day notice both correctly captured."),
    "doc171_qa7__after270": (0.75, "Anti-assignment consent with exceptions correctly captured; pred vague about exceptions."),
    "doc226_qa0__after276": (0.75, "Document name 'Cooperation Agreement' correct; pred adds 'on Mobile Game Business' subtitle."),
    "doc217_qa13__after277": (0.25, "License grant concept present; pred identifies Section 2 but no specific party/nature detail."),
    "doc84_qa4__after278": (0.5, "Anti-assignment concept correct; gold says 'no right to assign', pred says consent required."),
    "doc223_qa13__after279": (0.5, "Joint IP ownership concept correct; different mechanisms — 'to be decided' vs automatic equal share."),
    "doc154_qa14__after280": (0.5, "Perpetual license concept correct; different parties and provisions."),
    "doc183_qa9__after282": (0.75, "Anti-assignment with M&A exception correctly captured; pred adds subsidiary/JV exceptions."),
    "doc94_qa10__after286": (0.75, "Affiliate licensee concept correct; pred captures key elements."),
    "doc39_qa21__after286": (0.5, "Insurance obligation concept correct; pred gives one-party vs bilateral gold."),
    "doc156_qa9__after286": (0.5, "Consent requirement correct; pred adds termination/notice mechanism not in gold."),
    "doc227_qa6__after288": (1.0, "Near-exact match on 'may not be assigned by either party without prior written consent'."),
    "doc69_qa13__after291": (0.75, "Audit right correctly identified; pred lacks specific party names."),
    "doc103_qa7__after292": (0.5, "Consent-for-assignment concept present; different parties, pred adds Company free-assign exception."),
    "doc27_qa7__after292": (0.25, "CoC/assignment concept partially addressed; pred's specific Affiliate scenario differs."),
    "doc47_qa14__after292": (0.5, "Audit rights concept correct; gold is specific audit schedule provision."),
    "doc17_qa6__after293": (0.25, "Anti-assignment concept correct; gold says auto-terminate, pred says consent required."),
    "doc101_qa8__after295": (0.25, "Post-termination inventory disposal concept present; different specific mechanisms."),
    "doc286_qa17__after297": (0.75, "Audit right concept correctly captured; different specific scope."),
    "doc35_qa9__after301": (0.75, "Anti-assignment with void consequence correctly captured; pred adds consent detail."),
    "doc253_qa10__after301": (1.0, "Near-exact match on 'null and void' anti-assignment."),
    "doc0_qa0__after305": (1.0, "Exact match on 'DISTRIBUTOR AGREEMENT'."),
    "doc228_qa9__after306": (0.5, "Consent requirement correct; pred makes it bilateral vs Party B-only; adds exceptions."),
    "doc268_qa11__after307": (0.25, "TFC concept present; wrong parties and wrong specific context."),
    "doc129_qa20__after312": (0.75, "Non-transferable license correctly identified; pred slightly overstates restriction."),
    "doc156_qa9__after312": (1.0, "Near-exact match on bilateral consent for anti-assignment."),
    "doc300_qa1__after315": (0.75, "Correct party named (VERSO BACKHAUL SOLUTIONS) plus additional party."),
    "doc33_qa10__after317": (0.25, "Revenue sharing concept present; completely different parties."),
    "doc149_qa18__after318": (0.25, "Audit concept present; different parties and different aspects."),
    "doc271_qa16__after320": (0.25, "Audit right concept present; different parties and scope."),
    "doc295_qa5__after322": (0.5, "30-day notice correctly captured; gold is 15-year term + indefinite, pred is year-to-year."),
    "doc160_qa0__after323": (0.75, "Document name 'Services Agreement' correctly identified in context."),
    "doc84_qa0__after324": (1.0, "Exact match on 'SPONSORSHIP AGREEMENT'."),
    "doc81_qa8__after324": (0.5, "Non-transferable concept present; pred adds consent mechanism; gold allows Users sublicense."),
    "doc165_qa7__after325": (0.25, "Non-compete/competitive services restriction concept present; pred references sections without detail."),
    "doc67_qa8__after326": (0.5, "Anti-assignment consent concept present; different party scope and exception structure."),
    "doc162_qa26__after326": (0.5, "Insurance with notice of cancellation concept correct; different parties and coverage details."),
    "doc276_qa0__after327": (0.75, "Document name 'SPONSORSHIP AGREEMENT' correct; pred adds exhibit identifier."),
    # ── Entries 290–383 ─────────────────────────────────────────────────────
    "doc101_qa0__after327": (0.75, "Document name 'DISTRIBUTOR AGREEMENT' correct; pred adds exhibit identifier."),
    "doc33_qa8__after328": (0.25, "TFC concept correct; different notice period (30 vs 90 days) and trigger."),
    "doc82_qa5__after334": (0.25, "No-solicit-of-employees concept correct; wrong duration (6 months vs 12 months)."),
    "doc67_qa12__after334": (0.25, "Product liability insurance concept correct; wrong party scope and details."),
    "doc198_qa16__after335": (0.5, "Audit right concept present; pred is general but correct."),
    "doc281_qa0__after336": (1.0, "Exact match on 'CORPORATE SPONSORSHIP AGREEMENT'."),
    "doc314_qa7__after338": (0.25, "TFC concept correct; different parties and contract."),
    "doc250_qa9__after340": (0.25, "Non-transferable concept partially addressed through anti-assignment."),
    "doc267_qa20__after340": (0.25, "Insurance concept present; gold is truncated/fragmentary."),
    "doc277_qa7__after342": (0.25, "Non-compete/competitive restriction concept partially present; different mechanism."),
    "doc38_qa8__after342": (0.5, "Non-compete concept correct; pred gives broader restriction than gold's specific technology."),
    "doc277_qa22__after344": (0.5, "Audit rights concept present; different scope and parties."),
    "doc290_qa4__after344": (0.25, "Expiration concept present; 'Year 3' vs specific year 2006 — can't verify."),
    "doc170_qa15__after345": (0.5, "Non-transferable concept correct; pred cites wrong clause and different license type."),
    "doc286_qa16__after346": (0.25, "Non-transferable concept partially addressed; pred gives anti-assignment framing."),
    "doc329_qa17__after346": (0.25, "Audit right concept present; gold gives frequency limit; pred gives broad bilateral audit."),
    "doc39_qa8__after348": (0.25, "TFC concept correctly identified; pred has no specific details."),
    "doc124_qa11__after353": (0.5, "Non-transferable license concept correct through anti-assignment; wrong-contract specifics."),
    "doc273_qa7__after357": (0.5, "TFC concept correct; pred misses the 60-day notice requirement."),
    "doc78_qa8__after361": (0.25, "No-solicit-of-employees concept present; wrong duration and mechanism."),
    "doc224_qa14__after361": (0.5, "Insurance with named additional insured concept; wrong parties and different amounts."),
    "doc248_qa11__after362": (0.5, "Non-transferable concept present; pred gives general anti-transfer while gold is specific to marks."),
    "doc175_qa7__after365": (0.25, "TFC concept correct; bilateral vs Datec-only; wrong notice period."),
    "doc357_qa0__after366": (0.25, "Partial match — franchise agreement type captured; misses Attachment C/Addendum structure."),
    "doc359_qa11__after366": (0.75, "Anti-assignment with consent correctly captured; pred omits STAAR's one-sided exception."),
    "doc146_qa14__after367": (0.25, "IP ownership assignment concept present; different parties and context."),
    "doc360_qa12__after367": (0.5, "Anti-assignment concept correct; 'not assignable' vs 'assignable with consent'."),
    "doc81_qa4__after367": (1.0, "Exact match on '30 days' notice period."),
    "doc232_qa16__after372": (0.25, "Liquidated damages concept present; different specific clause and calculation."),
    "doc163_qa7__after373": (0.75, "Anti-assignment with consent correctly captured; pred bilateral vs Licensee-only."),
    "doc183_qa7__after378": (1.0, "Near-exact match on 'laws of the state of Delaware'."),
    "doc191_qa10__after378": (1.0, "Near-exact match on 'may not be assigned...without prior written consent...void'."),
    "doc233_qa7__after378": (0.25, "Consent concept correct; pred cites generic clauses from different contract."),
    "doc125_qa4__after381": (0.5, "1-year auto-renewal concept correct; wrong notice period (6 weeks vs 30 days)."),
    "doc164_qa9__after382": (0.75, "CoC termination right correctly captured; pred adds 50% threshold detail."),
    "doc341_qa17__after383": (0.25, "Insurance concept present; bilateral vs SAP AFRICA-only."),
    "doc136_qa14__after384": (0.75, "Audit right with record maintenance concept correct; different parties."),
    "doc40_qa7__after384": (0.25, "Liability cap concept present; gold is truncated."),
    "doc185_qa12__after386": (0.5, "Consent concept correct; sublicense to subsidiary vs general assignment."),
    "doc350_qa17__after387": (0.25, "Post-termination obligations concept present; gold is specifically about record retention."),
    "doc275_qa11__after388": (0.75, "Joint IP ownership concept correct; pred names specific parties Dexcel/Kitov."),
    "doc374_qa5__after388": (0.5, "1-year auto-renewal concept correct; pred adds conditions and 30-day notice not in gold."),
    # ── Entries 384–479 ─────────────────────────────────────────────────────
    "doc275_qa5__after389": (1.0, "Near-exact match on 'laws of the State of New York'."),
    "doc315_qa0__after391": (0.75, "Document name correct; pred abbreviates to 'FIRST AMEND TO SUPPLY AND MANUFACTURING AGREEMENT'."),
    "doc386_qa0__after392": (1.0, "Exact match on 'STRATEGIC ALLIANCE AGREEMENT'."),
    "doc86_qa9__after392": (0.75, "CoC consent concept correctly captured; pred identifies CoC as assignment triggering consent."),
    "doc129_qa13__after394": (0.25, "Void consequence concept present; pred gives wrong mechanism (Franchisee-only vs general)."),
    "doc346_qa8__after395": (0.5, "Consent requirement correct; pred omits Tickets' M&A exception."),
    "doc149_qa11__after397": (0.75, "Anti-assignment consent with M&A exception correctly captured; pred omits M&A exception."),
    "doc248_qa11__after401": (0.75, "Non-transferable for Constellation Marks correctly identified; pred identifies non-transferable nature."),
    "doc369_qa8__after402": (0.75, "Anti-assignment consent concept correct; pred notes exception in Section 8.01."),
    "doc193_qa10__after406": (0.5, "Anti-assignment consent concept correctly identified for Nantz Communications/Nantz; pred is vague."),
    "doc270_qa15__after406": (0.75, "Non-transferable/no-assignment for franchise concept correctly identified."),
    "doc321_qa5__after410": (1.0, "Near-exact match on 'law of the State of New York'."),
    "doc302_qa21__after410": (0.5, "Termination fee concept correct; different mechanism — termination fee schedule."),
    "doc153_qa0__after413": (0.25, "Partial match; pred says 'Distributor Agreement' missing 'NONEXCLUSIVE VALUE ADDED' part."),
    "doc148_qa8__after415": (1.0, "Near-exact match on bilateral consent requirement for assignment."),
    "doc139_qa8__after415": (0.75, "Anti-assignment consent correct; pred makes it bilateral vs Surgical-only."),
    "doc247_qa7__after417": (0.75, "Anti-assignment consent concept correct; pred adds M&A/affiliate exceptions not in gold."),
    "doc362_qa9__after418": (0.75, "Anti-assignment concept correct; pred adds consent requirement."),
    "doc253_qa6__after419": (0.25, "Notice period concept present; gold has redacted period, pred gives 30 days — unverifiable."),
    "doc299_qa15__after422": (0.5, "Uncapped liability for specific categories correctly identified; pred vaguely describes categories."),
    "doc9_qa21__after422": (0.25, "Uncapped liability concept partially addressed; different parties and scope."),
    "doc105_qa0__after424": (1.0, "Exact match on 'AGENCY AGREEMENT'."),
    "doc173_qa11__after424": (0.5, "Audit right concept present; gold gives quarterly limitation; pred says 'Section 7.8 Audits'."),
    "doc224_qa10__after426": (0.25, "Audit right concept present; pred cites wrong section."),
    "doc403_qa0__after427": (1.0, "Near-exact match on 'CO-BRANDING Agreement' (case variant)."),
    "doc279_qa21__after427": (0.25, "Liability cap concept present; wrong parties and different cap details."),
    "doc122_qa0__after428": (0.75, "Document name 'SERVICE AGREEMENT' correct; pred adds full exhibit identifier."),
    "doc117_qa8__after428": (0.5, "Consent concept correct; different exceptions — gold has franchise-specific exceptions; pred gives generic M&A exceptions."),
    "doc312_qa8__after428": (0.25, "Liability cap concept present; different contract/parties."),
    "doc286_qa0__after429": (1.0, "Near-exact match on 'CO-BRANDING AGREEMENT'."),
    "doc33_qa10__after431": (0.25, "Revenue sharing concept present; completely different parties and mechanism."),
    "doc112_qa0__after432": (1.0, "Near-exact match on 'CONTENT LICENSE AGREEMENT'."),
    "doc410_qa21__after433": (0.25, "Insurance certificate concept present; pred mentions additional insured; different parties."),
    "doc79_qa0__after436": (0.5, "Document name 'Corporate Sponsorship Agreement' partially captured; pred says 'Sponsorship Agreement' missing 'Corporate'."),
    "doc437_qa0__after439": (0.25, "Development Agreement partially matched; misses 'License and' prefix."),
    "doc120_qa5__after439": (0.5, "Non-transferable/anti-assignment concept correct; wrong parties."),
    "doc349_qa0__after439": (0.75, "RESELLER AGREEMENT correctly identified; pred adds exhibit identifier prefix."),
    # ── Entries 480–574 ─────────────────────────────────────────────────────
    "doc407_qa10__after441": (0.5, "Bilateral consent concept correct; gold is bilateral, pred is Customer-only (IBM)."),
    "doc192_qa15__after442": (0.25, "Post-termination transition concept present; different specific mechanisms."),
    "doc326_qa12__after442": (0.25, "Insurance cost-sharing concept present; different parties and mechanism."),
    "doc186_qa8__after443": (0.5, "Consent requirement correct; gold is mPhase-only; pred is bilateral with void consequence."),
    "doc126_qa18__after444": (0.25, "Insurance requirement concept present; gold is bilateral; pred is one-party with wrong entities."),
    "doc282_qa14__after445": (0.25, "Post-termination obligation concept present; different specific mechanisms."),
    "doc59_qa4__after446": (0.75, "Expiry follows referenced agreement — concept correctly captured; pred's paraphrase is accurate."),
    "doc154_qa17__after447": (0.25, "Audit right concept present; wrong parties and context."),
    "doc230_qa0__after448": (0.25, "Partial name match; pred says 'Content License Agreement' missing 'DISTRIBUTION AND'."),
    "doc149_qa9__after451": (0.5, "TFC concept correct; gold says 90 days; pred says [*] months — partially matches."),
    "doc281_qa0__after451": (1.0, "Exact match on 'CORPORATE SPONSORSHIP AGREEMENT'."),
    "doc280_qa0__after452": (1.0, "Case-variant match on 'TRADEMARK LICENSE AGREEMENT'."),
    "doc257_qa4__after455": (0.25, "Renewal/extension concept present; wrong mechanism and notice period."),
    "doc349_qa9__after456": (0.5, "Consent concept correct; gold is Reseller-only with successor exception; pred is bilateral without exception."),
    "doc271_qa13__after457": (0.25, "IP assignment concept partially present; different mechanism and direction."),
    "doc451_qa0__after457": (0.75, "Document name 'SPONSORSHIP AGREEMENT' correct; pred adds party names."),
    "doc261_qa0__after459": (1.0, "Case-variant match on 'ENDORSEMENT AGREEMENT'."),
    "doc340_qa4__after460": (0.75, "Auto-renewal with 1-year terms correct; wrong notice period — 60 vs 30 days."),
    "doc153_qa8__after461": (0.5, "TFC concept correct; gold is redacted; pred says 60 days — partially matches."),
    "doc52_qa11__after462": (0.25, "Consent present; pred misses the M&A exception which is the key finding."),
    "doc453_qa0__after463": (0.25, "Partial name match; pred says 'Co-Branding Agreement' missing amendment prefix."),
    "doc130_qa15__after463": (0.75, "Consequential damages exclusion correctly identified; pred adds Section 11 exception not in gold."),
    "doc398_qa8__after464": (0.5, "Non-transferable concept correct; wrong parties and different license context."),
    "doc316_qa2__after465": (0.75, "Year 2015 matches; pred gives complete date June 23, 2015 while gold only has the year."),
    "doc185_qa12__after466": (0.25, "General consent concept present; gold is specifically about sublicense to subsidiary."),
    "doc110_qa0__after469": (1.0, "Exact match on 'Strategic Alliance Agreement'."),
    "doc236_qa13__after470": (0.5, "Non-transferable with consent concept correct; gold has specific parties and merger exception; pred is bilateral without exception."),
    "doc324_qa12__after470": (0.5, "Audit right concept present; gold truncated; pred captures audit right concept."),
    "doc471_qa2__after471": (1.0, "Near-exact match on Comware effective date trigger."),
    "doc67_qa8__after473": (0.5, "Anti-assignment concept present; pred misses Permitted Assignee exception."),
    "doc380_qa8__after474": (0.5, "Bilateral consent correct; pred adds Licensee exception for affiliates not in gold."),
    "doc308_qa0__after477": (1.0, "Case-variant match on 'SPONSORSHIP AGREEMENT'."),
    "doc52_qa11__after479": (0.25, "Consent present; pred misses M&A exception."),
    "doc192_qa13__after479": (0.25, "Non-transferable concept partially present; wrong license context."),
    "doc154_qa17__after479": (0.25, "Audit right concept present; wrong parties."),
    "doc328_qa7__after480": (0.5, "Consent concept correct; gold Customer-only; pred bilateral with affiliate exception."),
    "doc52_qa11__after481": (0.25, "Consent present; pred misses M&A exception."),
    "doc322_qa18__after484": (0.25, "Audit right concept present; wrong parties and different audit scope."),
    "doc24_qa7__after484": (0.75, "Bilateral consent concept correct; pred adds 'not unreasonably withheld' not in gold."),
    # ── Entries 575–632 ─────────────────────────────────────────────────────
    "doc155_qa10__after486": (0.75, "Bilateral consent with reasonableness qualifier correct; pred omits voidable consequence."),
    "doc21_qa0__after486": (1.0, "Exact match on 'AGENCY AGREEMENT'."),
    "doc26_qa8__after487": (0.25, "Assignment condition concept partially present; pred gives general anti-assignment."),
    "doc108_qa14__after488": (0.25, "Joint IP ownership concept correct; wrong specific contract and mechanism."),
    "doc350_qa18__after488": (0.5, "Confidentiality-uncapped concept partially correct; pred adds license grant exception; different contract."),
    "doc185_qa12__after488": (0.25, "Consent concept present; gold is specifically sublicense to subsidiary with sole discretion."),
    "doc349_qa0__after489": (1.0, "Exact match on 'RESELLER AGREEMENT'."),
    "doc227_qa6__after490": (0.75, "Bilateral consent concept correct; pred adds reasonableness qualifier not in gold."),
    "doc108_qa14__after491": (0.25, "Joint IP ownership concept correct; wrong specific contract."),
    "doc143_qa13__after492": (0.25, "Warranty concept correct; different trigger — manufacture-to-expiry vs shipment."),
    "doc30_qa8__after492": (0.75, "30-day TFC concept correct; gold is bilateral; pred is Company-only."),
    "doc55_qa0__after495": (1.0, "Exact match on 'SERVICE AGREEMENT'."),
    "doc407_qa6__after496": (1.0, "Near-exact match on 30-day notice period to terminate renewal."),
    "doc11_qa9__after497": (0.5, "30-day TFC concept correct; gold is bilateral month-to-month; pred is Company-only at any time."),
    "doc121_qa9__after498": (0.5, "Audit right concept present; different parties but both state inspection access."),
    "doc70_qa11__after499": (0.5, "Confidentiality breach uncapped correctly identified; pred adds license grant + indemnity exceptions."),
    "doc185_qa15__after501": (0.25, "Joint IP ownership concept present; wrong contract and different specific provisions."),
    "doc428_qa19__after501": (0.5, "Post-termination obligations concept present; gold is truncated; pred describes reasonable survival."),
    "doc390_qa13__after502": (0.75, "Confidentiality + indemnification uncapped exceptions correctly identified; slight article numbering difference."),
    "doc221_qa0__after502": (0.75, "Document name 'First Amendment' correct; pred adds full exhibit identifier."),
    "doc40_qa7__after504": (0.25, "Liability cap concept present; gold is truncated so can't verify details."),
    "doc339_qa11__after505": (0.25, "Record access concept present; gold is LBIO's use rights; pred gives licensor inspection right."),
    "doc113_qa7__after505": (0.5, "Consent concept correct; gold is Company-only with specific competitor reasonableness provision; pred makes it bilateral."),
    "doc36_qa7__after505": (0.75, "One-party anti-assignment consent concept correct; parties differ but concept matches."),
    "doc466_qa5__after507": (0.75, "2-year/24-month term concept correct; different mechanism — gold has no notice period."),
    "doc182_qa11__after507": (0.25, "Post-termination asset return concept present; pred gives general obligations."),
    "doc338_qa13__after507": (0.5, "Audit right concept correct; gold is bilateral with limits; pred is one-directional."),
    "doc194_qa12__after509": (0.5, "No-consequential-damages with indemnification exception concept correct; different specific exceptions."),
}
