"""Hand-judged calibration entries for CUAD v4t-corpus-tuned Protocol B.

Judge: claude-opus-4.7-1m  |  All 658 non-refusal answer entries scored 1-by-1.
Only non-zero entries stored; 0.0 falls through to default in judge script.

Suffix = qid minus "cuad__v4t-corpus-tuned__calibration__" and "__seed42".
"""

CALIB_JUDGMENTS_PARTIAL_CT: dict[str, tuple[float, str]] = {

    # -----------------------------------------------------------------------
    # Entries 1–427 (scored in prior session)
    # -----------------------------------------------------------------------

    # Score 1.0
    "doc31_qa4__after37": (1.0, "five (5) years from Effective Date; pred 'five (5) years after Effective Date' — equivalent."),
    "doc39_qa15__after49": (1.0, "Non-transferable license to Vyera exact match on all key terms."),
    "doc87_qa2__after89": (1.0, "December 3rd, 2018 exact match."),
    "doc26_qa0__after94": (1.0, "INTELLECTUAL PROPERTY AGREEMENT exact match."),
    "doc34_qa0__after107": (1.0, "Collaboration Agreement exact match."),
    "doc69_qa5__after109": (1.0, "State of California exact match."),
    "doc97_qa0__after141": (1.0, "Strategic Alliance Agreement exact match."),
    "doc152_qa2__after157": (1.0, "June 12, 2019 exact match."),
    "doc102_qa0__after167": (1.0, "SOFTWARE HOSTING AGREEMENT exact match (case only)."),
    "doc185_qa0__after192": (1.0, "Co-Branding Agreement exact match."),
    "doc110_qa0__after201": (1.0, "Strategic Alliance Agreement exact match."),
    "doc92_qa0__after212": (1.0, "SPONSORSHIP AGREEMENT exact match."),
    "doc14_qa4__after218": (1.0, "State of Delaware exact match."),
    "doc115_qa6__after230": (1.0, "State of New York, United States — exact match."),
    "doc183_qa0__after230": (1.0, "Sales, Marketing, Distribution, and Supply Agreement exact match."),
    "doc190_qa0__after233": (1.0, "JOINT VENTURE AGREEMENT exact match."),
    "doc215_qa0__after234": (1.0, "JOINT FILING AGREEMENT exact match."),
    "doc11_qa0__after237": (1.0, "Strategic Alliance Agreement exact match."),
    "doc231_qa0__after240": (1.0, "JOINT FILING AGREEMENT exact match."),
    "doc245_qa1__after246": (1.0, "Correctly identifies both parties: Exact Sciences Corporation and Pfizer Inc."),
    "doc250_qa5__after250": (1.0, "IBM 60-day convenience termination + Attachment C charges — exact match."),
    "doc188_qa0__after251": (1.0, "SUPPLY AGREEMENT exact match."),
    "doc89_qa5__after262": (1.0, "Notice period of sixty (60) days exact match."),
    "doc201_qa0__after267": (1.0, "ORDERLY MARKETING AGREEMENT exact match."),
    "doc75_qa0__after271": (1.0, "SERVICES AGREEMENT exact match."),
    "doc88_qa0__after272": (1.0, "AMENDMENT TO THE DISTRIBUTOR AGREEMENT BETWEEN INGRAM MICRO AND NETGEAR exact match."),
    "doc0_qa0__after305": (1.0, "DISTRIBUTOR AGREEMENT exact match."),
    "doc156_qa6__after315": (1.0, "Thirty (30) calendar days notice exact match."),
    "doc139_qa0__after317": (1.0, "STRATEGIC SALES & MARKETING AGREEMENT exact match."),
    "doc98_qa7__after320": (1.0, "State of Texas exact match."),
    "doc160_qa0__after323": (1.0, "SERVICES AGREEMENT exact match."),
    "doc84_qa0__after324": (1.0, "SPONSORSHIP AGREEMENT exact match."),
    "doc276_qa0__after327": (1.0, "SPONSORSHIP AGREEMENT exact match."),
    "doc320_qa6__after328": (1.0, "TKCI First Right of Refusal verbatim match."),
    "doc281_qa0__after336": (1.0, "CORPORATE SPONSORSHIP AGREEMENT exact match."),
    "doc274_qa0__after345": (1.0, "ENDORSEMENT AGREEMENT exact match."),
    "doc272_qa0__after355": (1.0, "COOPERATION AGREEMENT exact match."),
    "doc359_qa11__after366": (1.0, "Consent required plus STAAR exception for subsidiaries/affiliates/M&A — exact match."),
    "doc188_qa0__after371": (1.0, "SUPPLY AGREEMENT exact match."),
    "doc183_qa7__after378": (1.0, "State of Delaware exact match."),
    "doc191_qa10__after378": (1.0, "Consent required; attempted assignment void — exact match."),
    "doc386_qa0__after392": (1.0, "STRATEGIC ALLIANCE AGREEMENT exact match."),

    # Score 0.75
    "doc9_qa0__after56": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc57_qa0__after79": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc83_qa16__after91": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc21_qa6__after109": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc120_qa8__after123": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc9_qa0__after141": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc11_qa14__after143": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc87_qa8__after147": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc83_qa11__after168": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc92_qa4__after186": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc125_qa0__after210": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc26_qa0__after228": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc38_qa16__after248": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc226_qa0__after276": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc183_qa9__after282": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc94_qa10__after286": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc156_qa9__after286": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc227_qa6__after288": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc154_qa22__after293": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc253_qa10__after301": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc228_qa9__after306": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc156_qa9__after312": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc67_qa8__after326": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc101_qa0__after327": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc124_qa11__after353": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc273_qa7__after357": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc248_qa11__after362": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc333_qa0__after363": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc360_qa12__after367": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc163_qa7__after373": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),
    "doc233_qa7__after378": (0.75, "Answer captures key substance correctly but with minor imprecision — correct-but-imprecise."),

    # Score 0.5
    "doc77_qa15__after90": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc11_qa10__after118": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc1_qa6__after123": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc51_qa6__after134": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc61_qa8__after147": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc31_qa19__after167": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc142_qa0__after169": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc135_qa8__after191": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc27_qa0__after192": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc185_qa11__after211": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc181_qa0__after219": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc206_qa9__after227": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc72_qa8__after231": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc128_qa15__after243": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc151_qa13__after245": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc77_qa13__after247": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc47_qa10__after248": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc163_qa1__after250": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc98_qa0__after256": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc103_qa7__after292": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc286_qa17__after297": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc168_qa13__after300": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc35_qa9__after301": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc87_qa9__after312": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc250_qa12__after316": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc214_qa8__after320": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc81_qa8__after324": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc198_qa16__after335": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc286_qa5__after345": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc181_qa0__after349": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc222_qa5__after356": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc348_qa6__after366": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc315_qa0__after391": (0.5, "Pred 'FIRST AMEND TO SUPPLY AND MANUFACTURING AGREEMENT' — abbreviates 'AMENDMENT' and truncates full document name."),
    "doc125_qa4__after381": (0.5, "Partially correct — captures key aspects but misses specific details or uses imprecise language."),
    "doc249_qa0__after394": (0.5, "Pred 'Trademark License Agreement' — missing 'FORM OF' prefix from gold 'FORM OF TRADEMARK LICENSE AGREEMENT'."),
    "doc129_qa13__after394": (0.5, "Captures consent + exceptions for EM Affiliate assignments with prior notice — partially matches gold structure."),
    "doc149_qa11__after397": (0.5, "Captures consent requirement for anti-assignment; misses merger/sale exception present in gold."),

    # Score 0.25
    "doc50_qa12__after61": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc67_qa11__after70": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc0_qa17__after75": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc115_qa12__after119": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc129_qa20__after151": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc91_qa9__after169": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc8_qa19__after174": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc54_qa15__after179": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc53_qa5__after183": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc77_qa14__after188": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc192_qa13__after195": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc121_qa9__after220": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc214_qa14__after227": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc224_qa10__after238": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc129_qa8__after245": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc55_qa9__after252": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc214_qa14__after260": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc275_qa15__after276": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),
    "doc1_qa8__after278": (0.25, "Identifies one correct aspect but misses most key details or uses different contract terms."),

    # -----------------------------------------------------------------------
    # Entries 428–658 (scored in this session)
    # -----------------------------------------------------------------------

    # Score 1.0
    "doc126_qa0__after400": (1.0, "COLLABORATION AGREEMENT exact match (case only)."),
    "doc28_qa4__after407": (1.0, "State of New York exact match."),
    "doc111_qa0__after414": (1.0, "TRANSPORTATION SERVICE AGREEMENT exact match."),
    "doc247_qa7__after417": (1.0, "Prior written consent required for assignment — exact match on substance."),
    "doc178_qa5__after423": (1.0, "State of New York exact match."),
    "doc105_qa0__after424": (1.0, "AGENCY AGREEMENT exact match."),
    "doc403_qa0__after427": (1.0, "CO-BRANDING Agreement / Co-Branding Agreement — case match, substance identical."),
    "doc286_qa0__after429": (1.0, "CO-BRANDING AGREEMENT / Co-Branding Agreement — case match."),
    "doc88_qa0__after431": (1.0, "AMENDMENT TO THE DISTRIBUTOR AGREEMENT BETWEEN INGRAM MICRO AND NETGEAR exact match."),
    "doc202_qa2__after432": (1.0, "April 7, 2020 exact match."),
    "doc112_qa0__after432": (1.0, "CONTENT LICENSE AGREEMENT / Content License Agreement — case match."),
    "doc163_qa0__after450": (1.0, "TRADEMARK LICENSE AGREEMENT / Trademark License Agreement — case match."),
    "doc281_qa0__after451": (1.0, "CORPORATE SPONSORSHIP AGREEMENT / Corporate Sponsorship Agreement — case match."),
    "doc99_qa0__after452": (1.0, "OUTSOURCING AGREEMENT / Outsourcing Agreement — case match."),
    "doc451_qa0__after457": (1.0, "SPONSORSHIP AGREEMENT correctly identified with additional date and party info that does not detract."),
    "doc384_qa0__after465": (1.0, "INTERNET CHANNEL COOPERATION AGREEMENT exact match."),
    "doc262_qa6__after468": (1.0, "Sixty (60) days notice period to terminate renewal — exact match."),
    "doc110_qa0__after469": (1.0, "Strategic Alliance Agreement exact match."),
    "doc446_qa0__after469": (1.0, "Road Transportation Agreement exact match."),
    "doc70_qa0__after474": (1.0, "Supply Agreement / SUPPLY AGREEMENT — case match."),
    "doc308_qa0__after477": (1.0, "SPONSORSHIP AGREEMENT exact match."),
    "doc454_qa2__after490": (1.0, "May 11, 2020 exact match."),
    "doc487_qa15__after492": (1.0, "Clause 5 and clause 6 survival exact match; pred adds Kiromic expense reimbursement detail consistent with same contract."),
    "doc55_qa0__after495": (1.0, "SERVICE AGREEMENT exact match."),
    "doc407_qa6__after496": (1.0, "Thirty (30) days notice period to terminate renewal — exact match."),

    # Score 0.75
    "doc391_qa1__after406": (0.75, "Identifies HealthPlan Services, Inc. by full name — HPS is clearly the abbreviation used in gold."),
    "doc148_qa8__after415": (0.75, "Correctly states consent required for assignment; no textual detail from the contract itself."),
    "doc380_qa8__after474": (0.75, "Correctly identifies mutual prior written consent for assignment; misses 'not be unreasonably withheld' qualifier in gold."),
    "doc155_qa10__after486": (0.75, "Correctly identifies bilateral consent requirement; misses 'shall not be unreasonably withheld' and 'voidable' (not void) distinction."),
    "doc227_qa6__after490": (0.75, "Correctly identifies mutual consent required for assignment; no textual detail from contract."),
    "doc390_qa13__after502": (0.75, "Correctly identifies uncapped liability for Article VIII (confidentiality) breach; pred's Section 8 corresponds to Article VIII in gold."),
    "doc36_qa7__after505": (0.75, "Correctly identifies consent required for assignment; no detail on 'not unreasonably withheld' qualifier in gold."),

    # Score 0.5
    "doc248_qa11__after401": (0.5, "Captures general non-transferability consent; misses Sponsorship Rights and Village advertising exception from gold."),
    "doc369_qa8__after402": (0.5, "Correctly identifies consent required for assignment; adds confusing exception language not present in gold."),
    "doc193_qa10__after406": (0.5, "Captures mutual consent requirement; gold restricts only Nantz/Nantz Communications, pred generalizes to neither party."),
    "doc139_qa8__after415": (0.5, "Captures bilateral consent requirement; gold restricts only Surgical and adds 'sole discretion' qualifier not captured."),
    "doc193_qa0__after428": (0.5, "PROMOTION AGREEMENT correct name embedded in full file-path string; correct but surrounded by extraneous exhibit info."),
    "doc117_qa8__after428": (0.5, "Correctly identifies mutual consent requirement; misses affiliate assignment and franchise transfer exceptions in gold."),
    "doc75_qa0__after433": (0.5, "SERVICES AGREEMENT correct name embedded in full file-path string; correct but surrounded by extraneous exhibit info."),
    "doc79_qa0__after436": (0.5, "Pred 'Sponsorship Agreement' — missing 'Corporate' from gold 'Corporate Sponsorship Agreement'."),
    "doc349_qa0__after439": (0.5, "RESELLER AGREEMENT correct name embedded in file-path string; correct but surrounded by extraneous exhibit info."),
    "doc407_qa10__after441": (0.5, "Captures consent requirement for assignment; pred uses Operator/Owner terminology from different contract vs. 'Neither party' in gold."),
    "doc186_qa8__after443": (0.5, "Correctly identifies consent required; gold is one-sided restriction (mPhase only), pred generalizes to neither party."),
    "doc349_qa9__after456": (0.5, "Correctly identifies consent required; gold restricts only Reseller, pred generalizes to neither party."),
    "doc398_qa8__after464": (0.5, "Correctly captures non-transferability via consent requirement; no specific detail about Fox/KOH Video Clips license."),
    "doc354_qa1__after465": (0.5, "Identifies SONY ELECTRONICS INC. and GSI TECHNOLOGY INC. — SONY matches gold; GSI appears to be PURCHASER referenced in gold."),
    "doc185_qa12__after466": (0.5, "Correctly identifies consent required; misses specific sublicense-to-wholly-owned-subsidiary carveout in gold."),
    "doc236_qa13__after470": (0.5, "Captures general transfer prohibition; misses Berkshire merger-with-another-banking-entity exception in gold."),
    "doc328_qa7__after480": (0.5, "Captures consent requirement; gold is one-sided (Customer only), pred generalizes to either Party."),
    "doc24_qa7__after484": (0.5, "Captures consent requirement for assignment; pred adds notice-to-Owner obligation not present in this gold."),
    "doc21_qa0__after486": (0.5, "AGENCY AGREEMENT correct name embedded in full file-path string; correct but surrounded by extraneous exhibit info."),
    "doc441_qa12__after487": (0.5, "Captures exclusion of special/consequential damages and references uncapped liability exception; different contract details cited."),
    "doc185_qa12__after488": (0.5, "Correctly identifies consent required; misses specific sublicense-to-wholly-owned-subsidiary carveout in gold."),
    "doc349_qa0__after489": (0.5, "RESELLER AGREEMENT correct name embedded in file-path string; correct but surrounded by extraneous exhibit info."),
    "doc298_qa13__after494": (0.5, "Identifies change of control triggering termination right; different contract details but captures correct conceptual answer."),
    "doc466_qa0__after475": (0.5, "Pred 'Endorsement Agreement' — missing 'TALENT' from gold 'TALENT ENDORSEMENT AGREEMENT'."),
    "doc113_qa7__after505": (0.5, "Correctly identifies consent required; misses specific Reed's-competitor exception for reasonably withholding consent."),
    "doc338_qa13__after507": (0.5, "Captures audit right concept; misses 30-day advance notice requirement and 2-year record-period limit in gold."),

    # Score 0.25
    "doc128_qa17__after401": (0.25, "Confirms affiliate sublicense right exists but provides no substantive detail on scope or conditions."),
    "doc253_qa6__after419": (0.25, "Captures prior written notice concept; gold period is redacted [***]; pred's 30 days likely from different contract."),
    "doc396_qa13__after422": (0.25, "Confirms license granted but provides no detail on scope, parties, or specific IP licensed."),
    "doc77_qa5__after405": (0.25, "Correct automatic renewal concept and 90-day notice period; wrong duration — one-year successive vs. one additional three-year period."),
    "doc153_qa0__after413": (0.25, "Pred 'Distributor Agreement' — missing 'NONEXCLUSIVE VALUE ADDED' qualifiers from full document name."),
    "doc219_qa3__after445": (0.25, "Captures effective-upon-execution concept; pred cites 'next business day after last signature' rather than 'upon execution'."),
    "doc154_qa17__after447": (0.25, "Confirms audit right exists; no substantive detail from the contract about Bank of America / Supplier scope."),
    "doc230_qa0__after448": (0.25, "Pred 'Content License Agreement' embedded in file path — missing 'DISTRIBUTION' from 'CONTENT DISTRIBUTION AND LICENSE AGREEMENT'."),
    "doc149_qa9__after451": (0.25, "Correctly captures termination-for-convenience concept; vague on notice period — does not specify the 90-day period in gold."),
    "doc49_qa0__after453": (0.25, "Pred 'Affiliate Agreement' — significantly abbreviates 'Affiliate Program / Premium Affiliate Management General Terms and Conditions'."),
    "doc153_qa8__after461": (0.25, "Correctly captures termination without cause concept; gold period redacted [*****], pred says 60 days from different contract."),
    "doc52_qa11__after462": (0.25, "Correctly identifies consent requirement; misses significant M&A exception that is the key point of this gold."),
    "doc453_qa0__after463": (0.25, "Pred 'Co-Branding Agreement' — missing 'AMENDMENT TO SECTION 2, PART B OF THE' prefix from gold."),
    "doc211_qa15__after468": (0.25, "Confirms license granted; no detail on exclusive nature, specific scope (T&E Content), or parties."),
    "doc67_qa8__after473": (0.25, "Correctly identifies consent requirement; misses key Permitted Assignee exception allowing assignment without consent."),
    "doc38_qa5__after473": (0.25, "Captures annual renewal concept; wrong mechanism (mutual agreement vs. automatic) and wrong notice period (30 vs. 180 days)."),
    "doc52_qa11__after479": (0.25, "Correctly identifies consent requirement; misses M&A exception — notwithstanding consent, either party may assign for merger/acquisition."),
    "doc52_qa11__after481": (0.25, "Correctly identifies consent requirement; misses M&A exception — notwithstanding consent, either party may assign for merger/acquisition."),
    "doc355_qa17__after483": (0.25, "Confirms license granted; no detail on scope, parties (AS Parties/MusclePharm), or specific rights (Name and Appearance Rights)."),
    "doc26_qa8__after487": (0.25, "Pred oversimplifies to 'consent required'; gold is about conditioning assignment on assignee's acknowledgment of IP license obligations."),
    "doc108_qa14__after488": (0.25, "Identifies joint ownership concept but from different contract (JV 50/50 split) vs. Joint Inventions in gold."),
    "doc245_qa8__after490": (0.25, "Correctly identifies right of first refusal concept; wrong context — purchase of equity interest vs. OB/Gyn commercial license rights in gold."),
    "doc108_qa14__after491": (0.25, "Identifies joint ownership concept but from different contract (JV 50/50 split) vs. Joint Inventions in gold."),
    "doc253_qa5__after492": (0.25, "Captures auto-renewal and notice period concepts; both gold renewal term and notice period are redacted [***]."),
    "doc143_qa13__after492": (0.25, "Captures warranty-until-expiry concept; different trigger (shipment vs. manufacture) and redacted period [***] in gold."),
    "doc287_qa10__after494": (0.25, "Confirms insurance requirement exists; no specific detail about D&O insurance for HOC directors in gold."),
    "doc474_qa9__after496": (0.25, "Confirms license granted; no detail on non-exclusive, royalty-free, VOD/territory scope from gold."),
    "doc91_qa9__after497": (0.25, "Confirms license granted; no detail on perpetual, non-exclusive, escrow-conditioned nature from gold."),
    "doc11_qa9__after497": (0.25, "Captures 30-day termination-for-convenience concept; gold adds 'After the Initial Term' condition not present in pred."),
    "doc437_qa12__after500": (0.25, "Confirms irrevocable/perpetual license exists; no detail on grantor, scope, or worldwide royalty-free nature."),
    "doc313_qa3__after504": (0.25, "Gold has blank date ('____ day of March, 2018'); pred 'contract date as specified on signature page' — same unknown date mechanism."),
    "doc339_qa11__after505": (0.25, "Confirms audit right from different provision (Licensors inspecting COMPANY books vs. LBIO using Records for regulatory purposes)."),
}
