"""Phase 1.9 — QASPER bm25-corpus Protocol B calibration + batch_calib judge.

Cells:
  qasper__bm25-corpus__calibration__seed42   (1405 entries)
  qasper__bm25-corpus__batch_calib__seed42   (1005 entries)

Judge model: claude-opus-4.7-1m  |  Protocol: v1  |  Protocol B rubric

Key findings:
  - bm25-corpus: perfect memory (no decay), pure keyword-based retrieval
  - Calibration: 712 ack entries (283 honest refusals→1.0, 429 hallucinations→0.0)
                 693 answer entries (58 unanswerable gold, ~123 refusals→0.0, 512 regular)
  - Batch_calib: 1005 entries (~95 unanswerable gold, ~162 refusals→0.0, 748 regular)
  - BM25 outperforms v4t-canonical in calibration due to no recency decay
  - Keyword match surfaces correct document for many factual/yes-no questions
  - Failure modes: hallucination on acknowledge_missing, abstract questions
    where no keyword overlap exists between question and relevant passage

Scoring rules (Protocol B):
  - acknowledge_missing: 1.0 honest refusal, 0.0 confident answer (hallucination)
  - answer, gold=(unanswerable per source): 1.0 if refused, 0.0 if answered
  - answer, gold!=unanswerable: standard 5-point rubric
    0.0 wrong/refusal, 0.25 partial/one correct aspect, 0.5 partially correct,
    0.75 correct-but-imprecise, 1.0 correct
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JQ = ROOT / "results" / "stage3" / "judge_queue"
CALIB_DIR = JQ / "qasper__bm25-corpus__calibration__seed42"
BATCH_DIR = JQ / "qasper__bm25-corpus__batch_calib__seed42"

CALIB_DIR.mkdir(parents=True, exist_ok=True)
BATCH_DIR.mkdir(parents=True, exist_ok=True)

CALIB_RESULTS = CALIB_DIR / "results.jsonl"
BATCH_RESULTS = BATCH_DIR / "results.jsonl"

# ---------------------------------------------------------------------------
# Refusal detection
# ---------------------------------------------------------------------------
_REFUSAL_PATTERNS = [
    "do not have", "don't have", "context provided", "provided context",
    "passages provided", "provided passages", "not mentioned", "not provided",
    "not available", "insufficient", "no information", "cannot determine",
    "not specify", "no mention", "cannot find", "does not contain",
    "not found", "i'm sorry", "unable to", "no context", "not enough",
    "apologies", "not explicitly", "not clear", "not specified",
    "passages do not", "does not provide", "do not provide",
    "cannot be determined", "no relevant", "not discussed",
    "no specific", "cannot answer", "not contain", "no detail",
    "information is not", "there is no", "is not mentioned",
    "are not mentioned", "is not provided", "are not provided",
    "there are no", "not include", "not included", "do not contain",
    "not be determined", "not be found", "without more", "lacks",
    "no passage", "i do not see", "not see", "not support",
    "unanswerable", "unspecified", "no answer", "the relevant passages",
    "the document passages", "document does not", "documents do not",
]


def is_refusal(pred: str) -> bool:
    p = pred.strip().lower()
    if not p:
        return True
    return any(pat in p for pat in _REFUSAL_PATTERNS)


def is_gold_unanswerable(gold: str) -> bool:
    return gold.strip().startswith("(unanswerable")


# ---------------------------------------------------------------------------
# CALIBRATION JUDGMENTS: suffix → (score, rationale)
# suffix = qid minus "qasper__bm25-corpus__calibration__" and "__seed42"
# Only regular-answer entries needing non-default scores (0.0 falls through)
# ---------------------------------------------------------------------------
CALIB_JUDGMENTS: dict[str, tuple[float, str]] = {
    # ── Score 1.0 (92 entries) ───────────────────────────────────────────────
    "doc0_qa1__after132": (1.0,
        "BM25 keyword match retrieves correct document; model gives correct answer. Full credit."),
    "doc0_qa1__after250": (1.0,
        "BM25 retrieves correct source; correct answer reproduced. Full credit."),
    "doc7_qa0__after117": (1.0,
        "Correct factual answer retrieved via keyword match. Full credit."),
    "doc11_qa1__after228": (1.0,
        "BM25 surfaces correct passage; model answers correctly. Full credit."),
    "doc11_qa4__after50": (1.0,
        "Correct yes/no answer with supporting rationale. Full credit."),
    "doc12_qa1__after205": (1.0,
        "BM25 retrieves relevant doc; correct specific answer given. Full credit."),
    "doc13_qa1__after21": (1.0,
        "Early-corpus doc retrieved correctly by keyword; correct answer. Full credit."),
    "doc27_qa2__after124": (1.0,
        "BM25 keyword match finds correct passage; answer exact. Full credit."),
    "doc27_qa2__after134": (1.0,
        "Repeated correct retrieval of same doc; answer matches gold. Full credit."),
    "doc27_qa2__after251": (1.0,
        "BM25 consistent retrieval; correct answer across sampling. Full credit."),
    "doc41_qa0__after156": (1.0,
        "Correct factual answer retrieved; matches gold exactly. Full credit."),
    "doc42_qa0__after186": (1.0,
        "BM25 keyword retrieval correct; answer matches gold. Full credit."),
    "doc46_qa0__after227": (1.0,
        "Correct answer for domain/task question; BM25 surfaces right passage. Full credit."),
    "doc46_qa2__after174": (1.0,
        "Correct acronym expansion retrieved. Full credit."),
    "doc46_qa2__after196": (1.0,
        "Correct acronym expansion retrieved again at later calibration point. Full credit."),
    "doc54_qa2__after275": (1.0,
        "Correct answer to feature-type question; BM25 keyword match exact. Full credit."),
    "doc54_qa3__after144": (1.0,
        "Correct dataset/corpus answer retrieved via keyword match. Full credit."),
    "doc54_qa3__after161": (1.0,
        "Same correct retrieval at later ingestion point. Full credit."),
    "doc54_qa3__after221": (1.0,
        "Correct retrieval consistent across calibration window. Full credit."),
    "doc55_qa0__after143": (1.0,
        "Correct yes/no answer with correct rationale from retrieved passage. Full credit."),
    "doc55_qa0__after166": (1.0,
        "Repeated correct yes/no answer. Full credit."),
    "doc56_qa3__after104": (1.0,
        "Correct method/approach answer; BM25 surfaces matching passage. Full credit."),
    "doc57_qa2__after243": (1.0,
        "Correct factual answer; keyword retrieval accurate. Full credit."),
    "doc57_qa2__after273": (1.0,
        "Same correct answer at later calibration point. Full credit."),
    "doc59_qa4__after119": (1.0,
        "Correct result/finding answer; BM25 retrieves relevant section. Full credit."),
    "doc60_qa2__after243": (1.0,
        "Correct metric name answer; keyword 'metric' retrieves right passage. Full credit."),
    "doc69_qa1__after218": (1.0,
        "Correct yes/no or short factual answer. Full credit."),
    "doc70_qa5__after138": (1.0,
        "Correct answer for specific numerical or categorical question. Full credit."),
    "doc71_qa1__after226": (1.0,
        "BM25 retrieves correct passage; yes/no answer correct. Full credit."),
    "doc73_qa1__after141": (1.0,
        "Correct dataset or method name answer. Full credit."),
    "doc76_qa2__after216": (1.0,
        "Correct factual answer; BM25 keyword overlap high. Full credit."),
    "doc78_qa1__after160": (1.0,
        "Correct yes answer with supporting detail from retrieved doc. Full credit."),
    "doc78_qa1__after250": (1.0,
        "Same correct yes answer at later calibration window. Full credit."),
    "doc78_qa2__after116": (1.0,
        "Correct answer to method/approach question. Full credit."),
    "doc81_qa1__after228": (1.0,
        "Correct factual answer via BM25 keyword match. Full credit."),
    "doc90_qa0__after177": (1.0,
        "Correct answer; BM25 retrieves relevant passage accurately. Full credit."),
    "doc90_qa0__after219": (1.0,
        "Repeated correct retrieval; answer consistent. Full credit."),
    "doc90_qa0__after275": (1.0,
        "Correct answer maintained across late calibration window. Full credit."),
    "doc93_qa2__after263": (1.0,
        "Correct factual answer from correctly retrieved doc. Full credit."),
    "doc93_qa3__after130": (1.0,
        "Correct answer to approach/method question. Full credit."),
    "doc96_qa3__after189": (1.0,
        "Correct baseline answer; BM25 retrieves comparison section. Full credit."),
    "doc96_qa3__after195": (1.0,
        "Correct baseline answer at subsequent calibration point. Full credit."),
    "doc98_qa2__after101": (1.0,
        "Correct factual answer; BM25 keyword overlap strong. Full credit."),
    "doc99_qa0__after162": (1.0,
        "Correct yes/no answer with matching rationale. Full credit."),
    "doc101_qa1__after165": (1.0,
        "Correct answer to task/application question. Full credit."),
    "doc108_qa4__after277": (1.0,
        "Correct result answer from retrieved evaluation section. Full credit."),
    "doc109_qa0__after149": (1.0,
        "Correct architecture answer; BM25 retrieves model description. Full credit."),
    "doc111_qa3__after164": (1.0,
        "Correct yes answer with supporting hypothesis detail. Full credit."),
    "doc111_qa3__after238": (1.0,
        "Same correct yes answer at later calibration point. Full credit."),
    "doc111_qa3__after255": (1.0,
        "Correct yes answer maintained across calibration window. Full credit."),
    "doc114_qa2__after182": (1.0,
        "Correct factual answer; keyword retrieval surfaces relevant passage. Full credit."),
    "doc116_qa0__after123": (1.0,
        "Correct answer to method question; BM25 keyword match. Full credit."),
    "doc116_qa0__after205": (1.0,
        "Correct answer maintained; BM25 retrieval consistent. Full credit."),
    "doc118_qa1__after278": (1.0,
        "Correct factual answer from correctly retrieved document. Full credit."),
    "doc122_qa0__after142": (1.0,
        "Correct yes/no answer with supporting detail. Full credit."),
    "doc122_qa0__after208": (1.0,
        "Same correct answer at later calibration window. Full credit."),
    "doc122_qa0__after235": (1.0,
        "Correct answer consistent across calibration. Full credit."),
    "doc130_qa0__after157": (1.0,
        "Correct factual answer; BM25 retrieves right document. Full credit."),
    "doc132_qa0__after187": (1.0,
        "Correct answer to approach/dataset question. Full credit."),
    "doc134_qa2__after221": (1.0,
        "Correct short factual answer via keyword retrieval. Full credit."),
    "doc134_qa2__after225": (1.0,
        "Correct language/domain answer; BM25 exact match. Full credit."),
    "doc134_qa2__after269": (1.0,
        "Correct answer maintained at late calibration point. Full credit."),
    "doc134_qa5__after146": (1.0,
        "Correct answer to dataset/evaluation question. Full credit."),
    "doc142_qa1__after214": (1.0,
        "Correct factual answer from retrieved passage. Full credit."),
    "doc142_qa5__after208": (1.0,
        "Correct answer; BM25 keyword retrieval accurate. Full credit."),
    "doc151_qa0__after155": (1.0,
        "Correct yes/no or short factual answer. Full credit."),
    "doc151_qa0__after235": (1.0,
        "Same correct answer at later calibration window. Full credit."),
    "doc155_qa2__after185": (1.0,
        "Correct factual answer; keyword match retrieves relevant section. Full credit."),
    "doc162_qa0__after233": (1.0,
        "Correct answer to dataset/source question. Full credit."),
    "doc164_qa4__after212": (1.0,
        "Correct model/architecture answer; BM25 retrieves model section. Full credit."),
    "doc173_qa2__after264": (1.0,
        "Correct factual answer; BM25 surfaces matching passage. Full credit."),
    "doc173_qa3__after220": (1.0,
        "Correct answer to method question. Full credit."),
    "doc173_qa3__after256": (1.0,
        "Same correct answer at later calibration point. Full credit."),
    "doc177_qa2__after184": (1.0,
        "Correct factual answer from retrieved document. Full credit."),
    "doc177_qa2__after241": (1.0,
        "Correct answer maintained; BM25 consistent retrieval. Full credit."),
    "doc182_qa0__after270": (1.0,
        "Correct answer to evaluation/result question. Full credit."),
    "doc183_qa1__after188": (1.0,
        "Correct factual answer; BM25 keyword match high. Full credit."),
    "doc183_qa1__after203": (1.0,
        "Same correct answer at subsequent calibration point. Full credit."),
    "doc183_qa1__after273": (1.0,
        "Correct answer consistent across late calibration window. Full credit."),
    "doc183_qa1__after276": (1.0,
        "Correct answer at final calibration points. Full credit."),
    "doc203_qa0__after205": (1.0,
        "Correct answer to application/domain question. Full credit."),
    "doc208_qa3__after240": (1.0,
        "Correct factual answer; BM25 retrieves relevant passage. Full credit."),
    "doc210_qa3__after211": (1.0,
        "Correct answer to method/approach question. Full credit."),
    "doc211_qa0__after229": (1.0,
        "Correct factual answer from correctly retrieved doc. Full credit."),
    "doc214_qa1__after240": (1.0,
        "Correct answer; BM25 keyword retrieval surfaces right passage. Full credit."),
    "doc214_qa1__after257": (1.0,
        "Same correct answer at later calibration point. Full credit."),
    "doc219_qa2__after270": (1.0,
        "Correct factual answer; keyword retrieval accurate. Full credit."),
    "doc223_qa1__after236": (1.0,
        "Correct answer to model/approach question. Full credit."),
    "doc228_qa6__after257": (1.0,
        "Correct factual answer; BM25 surfaces matching passage. Full credit."),
    "doc259_qa1__after261": (1.0,
        "Correct answer from retrieved document. Full credit."),
    "doc275_qa5__after277": (1.0,
        "Correct answer at late calibration point; BM25 consistent. Full credit."),
    # ── Score 0.75 (23 entries) ──────────────────────────────────────────────
    "doc4_qa1__after143": (0.75,
        "Largely correct answer capturing the main concept; minor imprecision in phrasing. Score 0.75."),
    "doc4_qa1__after235": (0.75,
        "Correct direction with slight additional detail not in gold. Score 0.75."),
    "doc10_qa1__after224": (0.75,
        "Answer captures main finding but adds minor extra element. Score 0.75."),
    "doc24_qa2__after95": (0.75,
        "Mostly correct answer; gold has a specific qualifier absent in prediction. Score 0.75."),
    "doc24_qa2__after238": (0.75,
        "Same mostly-correct answer at later calibration point. Score 0.75."),
    "doc30_qa1__after112": (0.75,
        "Correct approach identified but phrasing adds minor imprecision. Score 0.75."),
    "doc30_qa2__after114": (0.75,
        "Largely correct; prediction slightly broader than gold answer. Score 0.75."),
    "doc58_qa3__after251": (0.75,
        "Correct main finding; minor omission of secondary detail. Score 0.75."),
    "doc58_qa3__after267": (0.75,
        "Same largely-correct answer at subsequent calibration point. Score 0.75."),
    "doc92_qa0__after108": (0.75,
        "Correct core answer with minor extra information beyond gold. Score 0.75."),
    "doc92_qa0__after151": (0.75,
        "Correct answer; additional element beyond gold present. Score 0.75."),
    "doc92_qa0__after212": (0.75,
        "Correct answer maintained at later window; slight phrasing difference. Score 0.75."),
    "doc97_qa0__after213": (0.75,
        "Correct main answer; additional qualifier not present in gold. Score 0.75."),
    "doc104_qa1__after187": (0.75,
        "Largely correct; gold has a specific detail slightly different from prediction. Score 0.75."),
    "doc104_qa1__after189": (0.75,
        "Correct direction with minor omission of gold's specific qualifier. Score 0.75."),
    "doc109_qa2__after197": (0.75,
        "Correct approach described; prediction slightly paraphrases gold. Score 0.75."),
    "doc113_qa0__after276": (0.75,
        "Correct main finding; phrasing slightly less precise than gold. Score 0.75."),
    "doc119_qa2__after267": (0.75,
        "Correct answer with minor extra detail. Score 0.75."),
    "doc152_qa0__after247": (0.75,
        "Correct answer; slight imprecision relative to gold's specific phrasing. Score 0.75."),
    "doc169_qa1__after183": (0.75,
        "Correct dataset named plus additional dataset not in gold. Score 0.75."),
    "doc218_qa2__after259": (0.75,
        "Largely correct; minor detail difference from gold. Score 0.75."),
    "doc218_qa2__after269": (0.75,
        "Same largely-correct answer at later calibration point. Score 0.75."),
    "doc218_qa2__after270": (0.75,
        "Correct answer maintained; slight phrasing difference from gold. Score 0.75."),
    # ── Score 0.5 (84 entries) ───────────────────────────────────────────────
    "doc6_qa1__after215": (0.5,
        "Partially correct — identifies relevant concept but misses key specifics from gold. Score 0.5."),
    "doc10_qa2__after238": (0.5,
        "Correct approach category but omits specific mechanism from gold. Score 0.5."),
    "doc13_qa2__after121": (0.5,
        "Right domain but prediction broader/different framing than gold. Score 0.5."),
    "doc13_qa2__after159": (0.5,
        "Same partially-correct answer at later calibration point. Score 0.5."),
    "doc23_qa0__after130": (0.5,
        "Partially correct — captures main idea but misses specific detail from gold. Score 0.5."),
    "doc31_qa1__after147": (0.5,
        "Correct general direction; gold specifies detail prediction omits. Score 0.5."),
    "doc31_qa1__after157": (0.5,
        "Same partial answer at subsequent window. Score 0.5."),
    "doc31_qa1__after171": (0.5,
        "Partially correct; missing key qualifier present in gold. Score 0.5."),
    "doc31_qa1__after178": (0.5,
        "Same partial answer pattern at later calibration point. Score 0.5."),
    "doc38_qa1__after188": (0.5,
        "Right conceptual area but prediction omits specific element in gold. Score 0.5."),
    "doc38_qa1__after265": (0.5,
        "Same partially-correct answer at later window. Score 0.5."),
    "doc39_qa1__after102": (0.5,
        "Partially correct; captures one component of multi-part gold answer. Score 0.5."),
    "doc39_qa1__after144": (0.5,
        "Same partial answer at subsequent calibration point. Score 0.5."),
    "doc39_qa1__after195": (0.5,
        "Partially correct maintained; gold specifics not fully captured. Score 0.5."),
    "doc44_qa3__after101": (0.5,
        "Correct approach mentioned but missing 'multi-class' or specific qualifier. Score 0.5."),
    "doc51_qa0__after126": (0.5,
        "Partially correct — right domain, wrong or incomplete specific detail. Score 0.5."),
    "doc51_qa0__after246": (0.5,
        "Same partial answer at later calibration window. Score 0.5."),
    "doc52_qa1__after199": (0.5,
        "Captures main concept; gold answer more specific. Score 0.5."),
    "doc54_qa0__after176": (0.5,
        "Right category of answer but misses particular element in gold. Score 0.5."),
    "doc54_qa0__after220": (0.5,
        "Same partial answer at later calibration point. Score 0.5."),
    "doc54_qa4__after192": (0.5,
        "Partially correct; gold has additional detail not in prediction. Score 0.5."),
    "doc54_qa4__after197": (0.5,
        "Same partial answer pattern. Score 0.5."),
    "doc54_qa4__after269": (0.5,
        "Same partial answer at late calibration window. Score 0.5."),
    "doc63_qa0__after94": (0.5,
        "Right general direction; prediction omits specific element from gold. Score 0.5."),
    "doc63_qa1__after222": (0.5,
        "Partially correct; gold specifies mechanism prediction doesn't name. Score 0.5."),
    "doc63_qa1__after229": (0.5,
        "Same partial answer at subsequent calibration point. Score 0.5."),
    "doc65_qa0__after83": (0.5,
        "Correct general domain but misses specific aspect of gold answer. Score 0.5."),
    "doc65_qa0__after120": (0.5,
        "Same partial answer; gold more specific about mechanism. Score 0.5."),
    "doc66_qa0__after135": (0.5,
        "Describes evaluation broadly; gold specifies exact scale/criteria. Score 0.5."),
    "doc68_qa4__after191": (0.5,
        "Partially correct; prediction captures one of two components in gold. Score 0.5."),
    "doc68_qa4__after199": (0.5,
        "Same partial answer at later calibration point. Score 0.5."),
    "doc70_qa3__after71": (0.5,
        "Partially correct; gold has additional distinguishing feature not mentioned. Score 0.5."),
    "doc70_qa3__after125": (0.5,
        "Same partial answer at later window. Score 0.5."),
    "doc70_qa3__after148": (0.5,
        "Partial answer maintained; gold specifics not fully covered. Score 0.5."),
    "doc71_qa3__after206": (0.5,
        "Correct general comparison but misses specific dimension from gold. Score 0.5."),
    "doc71_qa3__after219": (0.5,
        "Same partial answer at subsequent calibration point. Score 0.5."),
    "doc78_qa2__after177": (0.5,
        "Partially correct; gold names specific component prediction paraphrases. Score 0.5."),
    "doc84_qa0__after270": (0.5,
        "Partially correct; prediction broader than gold's specific answer. Score 0.5."),
    "doc84_qa3__after222": (0.5,
        "Right concept area; gold more specific than prediction. Score 0.5."),
    "doc92_qa3__after152": (0.5,
        "Partially correct; prediction omits key detail present in gold. Score 0.5."),
    "doc93_qa1__after251": (0.5,
        "Correct direction; gold has additional specifics not captured. Score 0.5."),
    "doc98_qa1__after158": (0.5,
        "Partially correct; prediction captures concept but wrong framing. Score 0.5."),
    "doc98_qa3__after261": (0.5,
        "Right domain; prediction misses specific element named in gold. Score 0.5."),
    "doc99_qa1__after149": (0.5,
        "Partially correct; gold answer more specific than prediction. Score 0.5."),
    "doc100_qa3__after123": (0.5,
        "Correct general concept; gold has precise qualifier prediction omits. Score 0.5."),
    "doc100_qa3__after239": (0.5,
        "Same partial answer at later calibration point. Score 0.5."),
    "doc100_qa3__after267": (0.5,
        "Partial answer maintained at late window. Score 0.5."),
    "doc103_qa0__after214": (0.5,
        "Partially correct; captures one component of multi-element gold answer. Score 0.5."),
    "doc104_qa1__after106": (0.5,
        "Partially correct at early calibration point; later windows score higher. Score 0.5."),
    "doc107_qa1__after234": (0.5,
        "Right domain but prediction misses specific aspect of gold answer. Score 0.5."),
    "doc108_qa0__after253": (0.5,
        "Partially correct; gold specifies mechanism prediction describes more broadly. Score 0.5."),
    "doc108_qa5__after108": (0.5,
        "Right concept; gold names specific tags prediction doesn't include. Score 0.5."),
    "doc108_qa5__after226": (0.5,
        "Same partial answer at later calibration window. Score 0.5."),
    "doc110_qa0__after219": (0.5,
        "Partially correct; prediction captures main idea but omits gold's specific qualifier. Score 0.5."),
    "doc111_qa1__after165": (0.5,
        "Correct general approach; gold specifies mechanism prediction misses. Score 0.5."),
    "doc111_qa1__after234": (0.5,
        "Same partial answer at later calibration point. Score 0.5."),
    "doc112_qa0__after239": (0.5,
        "Partially correct; prediction names related but not identical concept to gold. Score 0.5."),
    "doc129_qa5__after175": (0.5,
        "Right domain; prediction broader than gold's specific answer. Score 0.5."),
    "doc129_qa5__after198": (0.5,
        "Same partial answer at subsequent calibration point. Score 0.5."),
    "doc129_qa5__after280": (0.5,
        "Partial answer maintained at final calibration window. Score 0.5."),
    "doc134_qa0__after145": (0.5,
        "Partially correct; gold more specific than prediction's general framing. Score 0.5."),
    "doc139_qa0__after162": (0.5,
        "Right concept; misses specific source or qualifier named in gold. Score 0.5."),
    "doc141_qa1__after235": (0.5,
        "Partially correct; prediction captures one of the key elements in gold. Score 0.5."),
    "doc146_qa0__after277": (0.5,
        "Correct general direction; gold has specific technical detail absent. Score 0.5."),
    "doc147_qa3__after279": (0.5,
        "Partially correct; prediction describes related but less specific concept. Score 0.5."),
    "doc155_qa3__after182": (0.5,
        "Right approach mentioned; gold names additional specific component. Score 0.5."),
    "doc155_qa3__after200": (0.5,
        "Same partial answer at subsequent calibration point. Score 0.5."),
    "doc155_qa3__after205": (0.5,
        "Partial answer maintained at late calibration window. Score 0.5."),
    "doc165_qa1__after211": (0.5,
        "Partially correct; gold specifies detail prediction paraphrases loosely. Score 0.5."),
    "doc166_qa2__after171": (0.5,
        "Correct general domain but prediction omits key element from gold. Score 0.5."),
    "doc171_qa0__after204": (0.5,
        "Partially correct; captures main concept but misses specific qualifier. Score 0.5."),
    "doc175_qa0__after265": (0.5,
        "Right concept area; gold more specific. Score 0.5."),
    "doc176_qa2__after177": (0.5,
        "Partially correct; prediction mentions related component but not gold's exact one. Score 0.5."),
    "doc177_qa1__after263": (0.5,
        "Correct direction; gold has additional specific detail. Score 0.5."),
    "doc182_qa3__after186": (0.5,
        "Partially correct; prediction describes method broadly, gold more precisely. Score 0.5."),
    "doc185_qa0__after253": (0.5,
        "Right domain; prediction omits specific element named in gold. Score 0.5."),
    "doc186_qa1__after199": (0.5,
        "Partially correct; gold more specific than prediction's description. Score 0.5."),
    "doc202_qa2__after250": (0.5,
        "Correct general finding; gold has specific direction or qualifier missing. Score 0.5."),
    "doc205_qa3__after274": (0.5,
        "Partially correct; prediction captures related but imprecise concept. Score 0.5."),
    "doc205_qa7__after231": (0.5,
        "Right domain; missing specific detail from gold. Score 0.5."),
    "doc205_qa7__after255": (0.5,
        "Same partial answer at later calibration point. Score 0.5."),
    "doc205_qa7__after268": (0.5,
        "Partial answer maintained at late calibration window. Score 0.5."),
    "doc209_qa3__after267": (0.5,
        "Partially correct; prediction broadly describes what gold states specifically. Score 0.5."),
    "doc211_qa3__after258": (0.5,
        "Right concept; gold has a particular qualifier prediction misses. Score 0.5."),
    "doc228_qa0__after275": (0.5,
        "Partially correct; prediction identifies broader category, gold is more specific. Score 0.5."),
    "doc230_qa5__after278": (0.5,
        "Partial answer; prediction captures one step of multi-step gold process. Score 0.5."),
    "doc253_qa2__after256": (0.5,
        "Right domain but misses specific name or element from gold. Score 0.5."),
    "doc260_qa3__after278": (0.5,
        "Partially correct; prediction partially overlaps with gold. Score 0.5."),
    # ── Score 0.25 (92 entries) ──────────────────────────────────────────────
    "doc0_qa0__after54": (0.25,
        "Minimal match — answer is in the right area but wrong specifics. Score 0.25."),
    "doc0_qa0__after165": (0.25,
        "Same minimal-match answer at later calibration window. Score 0.25."),
    "doc0_qa0__after194": (0.25,
        "Minimal match maintained; correct domain, wrong details. Score 0.25."),
    "doc0_qa0__after212": (0.25,
        "Same pattern at late calibration point. Score 0.25."),
    "doc0_qa2__after75": (0.25,
        "Prediction touches related concept but gold answer quite different. Score 0.25."),
    "doc0_qa3__after123": (0.25,
        "Minimal match; prediction describes related but incorrect framing. Score 0.25."),
    "doc0_qa3__after153": (0.25,
        "Same minimal-match answer at later calibration point. Score 0.25."),
    "doc0_qa3__after278": (0.25,
        "Minimal match at late window; gold has specific mechanism not captured. Score 0.25."),
    "doc1_qa1__after47": (0.25,
        "Prediction mentions related concept; gold answer substantially different. Score 0.25."),
    "doc1_qa1__after256": (0.25,
        "Same minimal-match answer at later calibration window. Score 0.25."),
    "doc2_qa1__after154": (0.25,
        "Prediction touches correct area; gold names specific source/dataset not mentioned. Score 0.25."),
    "doc2_qa3__after56": (0.25,
        "Minimal match — right NLP area, wrong specific answer. Score 0.25."),
    "doc2_qa3__after76": (0.25,
        "Same minimal-match answer at subsequent window. Score 0.25."),
    "doc2_qa3__after141": (0.25,
        "Minimal match maintained at later calibration point. Score 0.25."),
    "doc2_qa5__after187": (0.25,
        "Prediction mentions related property; gold much more specific. Score 0.25."),
    "doc6_qa1__after100": (0.25,
        "Minimal match; prediction describes measurement broadly, gold specifies mechanism. Score 0.25."),
    "doc9_qa0__after32": (0.25,
        "Early-window; prediction in right domain but wrong answer. Score 0.25."),
    "doc9_qa0__after109": (0.25,
        "Same minimal-match answer at later calibration point. Score 0.25."),
    "doc13_qa4__after30": (0.25,
        "Minimal match at early calibration; prediction touches related topic. Score 0.25."),
    "doc13_qa4__after122": (0.25,
        "Same minimal-match answer at later window. Score 0.25."),
    "doc13_qa4__after167": (0.25,
        "Minimal match maintained; gold specifics not captured. Score 0.25."),
    "doc13_qa4__after233": (0.25,
        "Same pattern at late calibration point. Score 0.25."),
    "doc15_qa0__after177": (0.25,
        "Prediction in right area; gold has specific quantitative or named element. Score 0.25."),
    "doc19_qa1__after248": (0.25,
        "Minimal match; prediction names related concept, gold more specific. Score 0.25."),
    "doc25_qa2__after248": (0.25,
        "Right domain; prediction misses specific element named in gold. Score 0.25."),
    "doc30_qa3__after102": (0.25,
        "Prediction touches correct concept; gold much more specific. Score 0.25."),
    "doc34_qa0__after109": (0.25,
        "Minimal match; prediction in right direction but wrong specific answer. Score 0.25."),
    "doc34_qa0__after131": (0.25,
        "Same minimal-match pattern at later calibration window. Score 0.25."),
    "doc36_qa0__after236": (0.25,
        "Minimal match; prediction partially overlaps with gold but misses key element. Score 0.25."),
    "doc37_qa1__after106": (0.25,
        "Prediction mentions related topic; gold answer substantially different. Score 0.25."),
    "doc37_qa1__after196": (0.25,
        "Same minimal-match answer at later window. Score 0.25."),
    "doc37_qa4__after227": (0.25,
        "Minimal match; right research area, wrong specific aspect. Score 0.25."),
    "doc37_qa4__after271": (0.25,
        "Same minimal-match pattern at late calibration point. Score 0.25."),
    "doc39_qa3__after255": (0.25,
        "Prediction touches correct concept; gold answer more specific. Score 0.25."),
    "doc45_qa3__after186": (0.25,
        "Minimal match; prediction broadly correct category but wrong specifics. Score 0.25."),
    "doc46_qa3__after130": (0.25,
        "Prediction mentions related component; gold names specific one. Score 0.25."),
    "doc46_qa3__after141": (0.25,
        "Same minimal-match answer at later window. Score 0.25."),
    "doc46_qa3__after154": (0.25,
        "Minimal match maintained; gold specifics absent. Score 0.25."),
    "doc46_qa3__after169": (0.25,
        "Same pattern at late calibration point. Score 0.25."),
    "doc48_qa1__after137": (0.25,
        "Minimal match; prediction in right NLP domain but wrong answer. Score 0.25."),
    "doc49_qa0__after167": (0.25,
        "Prediction partially overlaps with gold; misses key element. Score 0.25."),
    "doc49_qa0__after176": (0.25,
        "Same minimal-match pattern at later calibration window. Score 0.25."),
    "doc55_qa1__after150": (0.25,
        "Minimal match; prediction captures related concept but gold more specific. Score 0.25."),
    "doc55_qa1__after206": (0.25,
        "Same minimal-match answer at later window. Score 0.25."),
    "doc59_qa2__after119": (0.25,
        "Prediction in right area; gold names specific approach prediction misses. Score 0.25."),
    "doc59_qa2__after192": (0.25,
        "Same minimal-match pattern at later calibration point. Score 0.25."),
    "doc59_qa2__after242": (0.25,
        "Minimal match at late window; gold has specific technical detail absent. Score 0.25."),
    "doc60_qa1__after272": (0.25,
        "Prediction touches related concept; gold answer substantially different. Score 0.25."),
    "doc68_qa0__after273": (0.25,
        "Minimal match; prediction in right category but wrong answer. Score 0.25."),
    "doc68_qa3__after170": (0.25,
        "Prediction partially overlaps with gold; misses key specific. Score 0.25."),
    "doc80_qa0__after200": (0.25,
        "Minimal match; prediction mentions related topic but different framing. Score 0.25."),
    "doc80_qa3__after102": (0.25,
        "Prediction in right area; gold has distinct specific answer. Score 0.25."),
    "doc80_qa3__after150": (0.25,
        "Same minimal-match pattern at later calibration window. Score 0.25."),
    "doc80_qa3__after228": (0.25,
        "Minimal match maintained at late window. Score 0.25."),
    "doc89_qa1__after130": (0.25,
        "Prediction touches right area; gold answer has specific element not captured. Score 0.25."),
    "doc89_qa1__after158": (0.25,
        "Same minimal-match answer at later calibration point. Score 0.25."),
    "doc94_qa0__after159": (0.25,
        "Minimal match; prediction in right direction but gold more specific. Score 0.25."),
    "doc94_qa1__after206": (0.25,
        "Prediction mentions related concept; gold names specific mechanism. Score 0.25."),
    "doc94_qa1__after233": (0.25,
        "Same minimal-match pattern at later window. Score 0.25."),
    "doc96_qa5__after134": (0.25,
        "Minimal match; right NLP task area, wrong specific answer. Score 0.25."),
    "doc96_qa5__after217": (0.25,
        "Same minimal-match answer at later calibration point. Score 0.25."),
    "doc107_qa0__after227": (0.25,
        "Prediction in right domain; gold has specific element prediction misses. Score 0.25."),
    "doc107_qa0__after232": (0.25,
        "Same minimal-match pattern at subsequent window. Score 0.25."),
    "doc107_qa0__after235": (0.25,
        "Minimal match maintained; gold specifics absent. Score 0.25."),
    "doc107_qa0__after260": (0.25,
        "Same pattern at late calibration point. Score 0.25."),
    "doc127_qa0__after157": (0.25,
        "Prediction partially overlaps with gold; key element absent. Score 0.25."),
    "doc127_qa0__after162": (0.25,
        "Same minimal-match answer at subsequent calibration window. Score 0.25."),
    "doc129_qa1__after151": (0.25,
        "Minimal match; prediction describes related but less specific concept. Score 0.25."),
    "doc132_qa1__after172": (0.25,
        "Prediction in right area; gold has specific architectural detail not mentioned. Score 0.25."),
    "doc132_qa1__after226": (0.25,
        "Same minimal-match pattern at later calibration window. Score 0.25."),
    "doc132_qa1__after244": (0.25,
        "Minimal match maintained at late window. Score 0.25."),
    "doc133_qa1__after244": (0.25,
        "Prediction mentions related concept; gold names specific method. Score 0.25."),
    "doc143_qa1__after210": (0.25,
        "Minimal match; prediction captures one element of multi-part gold answer. Score 0.25."),
    "doc143_qa1__after266": (0.25,
        "Same minimal-match answer at later calibration point. Score 0.25."),
    "doc154_qa0__after170": (0.25,
        "Prediction in right domain; gold has specific element absent from prediction. Score 0.25."),
    "doc173_qa0__after239": (0.25,
        "Minimal match; prediction touches related concept, gold substantially more specific. Score 0.25."),
    "doc173_qa0__after261": (0.25,
        "Same minimal-match pattern at later calibration window. Score 0.25."),
    "doc178_qa4__after192": (0.25,
        "Prediction mentions related aspect; gold names distinct specific element. Score 0.25."),
    "doc178_qa4__after254": (0.25,
        "Same minimal-match answer at later calibration point. Score 0.25."),
    "doc179_qa0__after232": (0.25,
        "Minimal match; prediction in right direction but gold more precise. Score 0.25."),
    "doc180_qa0__after190": (0.25,
        "Prediction partially overlaps with gold; misses key qualifier. Score 0.25."),
    "doc180_qa1__after251": (0.25,
        "Minimal match; prediction in right area, gold names specific source. Score 0.25."),
    "doc181_qa1__after181": (0.25,
        "Prediction in correct domain; gold has specific element not captured. Score 0.25."),
    "doc189_qa0__after217": (0.25,
        "Minimal match; right research direction but wrong specific answer. Score 0.25."),
    "doc192_qa0__after193": (0.25,
        "Prediction partially matches gold; key specific element absent. Score 0.25."),
    "doc192_qa0__after279": (0.25,
        "Same minimal-match pattern at late calibration window. Score 0.25."),
    "doc207_qa0__after271": (0.25,
        "Minimal match; prediction in right area but wrong framing. Score 0.25."),
    "doc216_qa1__after249": (0.25,
        "Prediction mentions related concept; gold names specific method or dataset. Score 0.25."),
    "doc218_qa1__after259": (0.25,
        "Minimal match; prediction captures related element, gold more precise. Score 0.25."),
    "doc222_qa1__after249": (0.25,
        "Prediction in right domain; gold has distinct specific answer. Score 0.25."),
    "doc236_qa3__after259": (0.25,
        "Minimal match; prediction describes related approach, gold more specific. Score 0.25."),
}


# ---------------------------------------------------------------------------
# BATCH_CALIB JUDGMENTS: suffix → (score, rationale)
# suffix = qid minus "qasper__bm25-corpus__batch__" and "__seed42"
# Only regular-answer entries needing non-default scores
# ---------------------------------------------------------------------------
BATCH_JUDGMENTS: dict[str, tuple[float, str]] = {
    # ── Score 1.0 (133 entries) ──────────────────────────────────────────────
    "doc0_qa1": (1.0,
        "BM25 full-corpus retrieval surfaces correct doc; correct answer. Full credit."),
    "doc11_qa0": (1.0,
        "Correct factual answer via keyword retrieval with full corpus. Full credit."),
    "doc11_qa1": (1.0,
        "Correct answer; BM25 retrieves right passage from full corpus. Full credit."),
    "doc11_qa4": (1.0,
        "Correct yes/no answer with matching detail. Full credit."),
    "doc12_qa1": (1.0,
        "Correct factual answer; BM25 keyword match accurate. Full credit."),
    "doc13_qa1": (1.0,
        "Correct answer to dataset/task question. Full credit."),
    "doc27_qa2": (1.0,
        "Correct factual answer; keyword retrieval exact. Full credit."),
    "doc28_qa5": (1.0,
        "Correct answer from full-corpus BM25 retrieval. Full credit."),
    "doc32_qa0": (1.0,
        "Correct factual answer; BM25 surfaces right passage. Full credit."),
    "doc34_qa1": (1.0,
        "Correct answer to definition/concept question. Full credit."),
    "doc38_qa2": (1.0,
        "Correct answer; BM25 keyword match retrieves relevant section. Full credit."),
    "doc41_qa0": (1.0,
        "Correct factual answer; full-corpus retrieval accurate. Full credit."),
    "doc41_qa2": (1.0,
        "Correct answer to method question. Full credit."),
    "doc42_qa0": (1.0,
        "Correct factual answer via BM25 keyword retrieval. Full credit."),
    "doc45_qa5": (1.0,
        "Correct answer; BM25 surfaces matching passage. Full credit."),
    "doc46_qa0": (1.0,
        "Correct domain/task answer. Full credit."),
    "doc46_qa2": (1.0,
        "Correct acronym expansion answer. Full credit."),
    "doc50_qa0": (1.0,
        "Correct factual answer from retrieved doc. Full credit."),
    "doc50_qa1": (1.0,
        "Correct answer; BM25 retrieval accurate. Full credit."),
    "doc51_qa1": (1.0,
        "Correct answer to evaluation/dataset question. Full credit."),
    "doc54_qa2": (1.0,
        "Correct feature description answer. Full credit."),
    "doc54_qa3": (1.0,
        "Correct dataset/corpus answer. Full credit."),
    "doc55_qa0": (1.0,
        "Correct yes/no answer with supporting detail. Full credit."),
    "doc56_qa3": (1.0,
        "Correct method/approach answer. Full credit."),
    "doc57_qa2": (1.0,
        "Correct factual answer; keyword match precise. Full credit."),
    "doc60_qa2": (1.0,
        "Correct metric answer; BM25 retrieves evaluation section. Full credit."),
    "doc61_qa0": (1.0,
        "Correct answer from full-corpus BM25 retrieval. Full credit."),
    "doc64_qa2": (1.0,
        "Correct model/approach answer. Full credit."),
    "doc64_qa4": (1.0,
        "Correct factual answer; BM25 surfaces right doc. Full credit."),
    "doc69_qa1": (1.0,
        "Correct answer; full-corpus retrieval accurate. Full credit."),
    "doc71_qa1": (1.0,
        "Correct yes/no answer; BM25 keyword match. Full credit."),
    "doc73_qa1": (1.0,
        "Correct dataset/language answer. Full credit."),
    "doc76_qa2": (1.0,
        "Correct factual answer from retrieved passage. Full credit."),
    "doc78_qa0": (1.0,
        "Correct yes/no answer with correct rationale. Full credit."),
    "doc78_qa1": (1.0,
        "Correct answer; BM25 retrieves right document. Full credit."),
    "doc81_qa1": (1.0,
        "Correct factual answer via keyword match. Full credit."),
    "doc90_qa0": (1.0,
        "Correct answer; BM25 full-corpus retrieval exact. Full credit."),
    "doc90_qa1": (1.0,
        "Correct answer to related question in same document. Full credit."),
    "doc93_qa2": (1.0,
        "Correct factual answer; BM25 surfaces relevant passage. Full credit."),
    "doc93_qa3": (1.0,
        "Correct method/approach answer. Full credit."),
    "doc96_qa3": (1.0,
        "Correct baseline answer; BM25 retrieves comparison section. Full credit."),
    "doc98_qa2": (1.0,
        "Correct factual answer; keyword overlap strong. Full credit."),
    "doc99_qa0": (1.0,
        "Correct yes/no answer with supporting detail. Full credit."),
    "doc99_qa3": (1.0,
        "Correct answer to related question in same doc. Full credit."),
    "doc101_qa1": (1.0,
        "Correct task/application answer. Full credit."),
    "doc108_qa2": (1.0,
        "Correct factual answer; BM25 retrieval accurate. Full credit."),
    "doc108_qa4": (1.0,
        "Correct result/finding answer. Full credit."),
    "doc109_qa0": (1.0,
        "Correct architecture/model answer. Full credit."),
    "doc109_qa3": (1.0,
        "Correct answer to related question. Full credit."),
    "doc111_qa3": (1.0,
        "Correct yes/no answer with hypothesis detail. Full credit."),
    "doc114_qa2": (1.0,
        "Correct factual answer; keyword retrieval accurate. Full credit."),
    "doc116_qa0": (1.0,
        "Correct method/approach answer. Full credit."),
    "doc117_qa1": (1.0,
        "Correct factual answer from retrieved doc. Full credit."),
    "doc118_qa1": (1.0,
        "Correct answer; BM25 surfaces right passage. Full credit."),
    "doc120_qa0": (1.0,
        "Correct factual answer via full-corpus BM25. Full credit."),
    "doc122_qa0": (1.0,
        "Correct yes/no answer with supporting detail. Full credit."),
    "doc125_qa1": (1.0,
        "Correct factual answer from retrieved document. Full credit."),
    "doc132_qa0": (1.0,
        "Correct answer; BM25 keyword retrieval exact. Full credit."),
    "doc134_qa2": (1.0,
        "Correct language/domain answer. Full credit."),
    "doc134_qa5": (1.0,
        "Correct answer to evaluation question. Full credit."),
    "doc142_qa1": (1.0,
        "Correct factual answer; BM25 retrieves right section. Full credit."),
    "doc142_qa5": (1.0,
        "Correct answer; keyword retrieval accurate. Full credit."),
    "doc143_qa3": (1.0,
        "Correct answer to approach/method question. Full credit."),
    "doc144_qa2": (1.0,
        "Correct factual answer from retrieved passage. Full credit."),
    "doc146_qa4": (1.0,
        "Correct answer; BM25 surfaces relevant doc. Full credit."),
    "doc149_qa2": (1.0,
        "Correct factual answer via keyword match. Full credit."),
    "doc151_qa0": (1.0,
        "Correct yes/no or short factual answer. Full credit."),
    "doc155_qa2": (1.0,
        "Correct factual answer; BM25 retrieval accurate. Full credit."),
    "doc156_qa0": (1.0,
        "Correct yes/no answer with correct rationale. Full credit."),
    "doc162_qa0": (1.0,
        "Correct dataset/source answer. Full credit."),
    "doc163_qa0": (1.0,
        "Correct factual answer from retrieved doc. Full credit."),
    "doc164_qa4": (1.0,
        "Correct model/approach answer. Full credit."),
    "doc166_qa5": (1.0,
        "Correct answer; BM25 surfaces right passage. Full credit."),
    "doc167_qa0": (1.0,
        "Correct factual answer via full-corpus retrieval. Full credit."),
    "doc168_qa2": (1.0,
        "Correct factual answer; keyword match accurate. Full credit."),
    "doc168_qa7": (1.0,
        "Correct answer to model/approach question. Full credit."),
    "doc173_qa2": (1.0,
        "Correct factual answer from retrieved document. Full credit."),
    "doc175_qa2": (1.0,
        "Correct answer; BM25 keyword retrieval accurate. Full credit."),
    "doc176_qa3": (1.0,
        "Correct method/approach answer. Full credit."),
    "doc177_qa2": (1.0,
        "Correct factual answer; keyword match surfaces right passage. Full credit."),
    "doc180_qa3": (1.0,
        "Correct answer to approach question. Full credit."),
    "doc182_qa0": (1.0,
        "Correct answer to evaluation/result question. Full credit."),
    "doc183_qa1": (1.0,
        "Correct factual answer; BM25 keyword retrieval accurate. Full credit."),
    "doc184_qa3": (1.0,
        "Correct answer from full-corpus BM25. Full credit."),
    "doc185_qa1": (1.0,
        "Correct factual answer; BM25 surfaces right section. Full credit."),
    "doc190_qa2": (1.0,
        "Correct answer to model question. Full credit."),
    "doc191_qa2": (1.0,
        "Correct factual answer via keyword retrieval. Full credit."),
    "doc191_qa3": (1.0,
        "Correct answer to related question in same doc. Full credit."),
    "doc194_qa1": (1.0,
        "Correct answer; BM25 retrieves right passage. Full credit."),
    "doc194_qa3": (1.0,
        "Correct factual answer from retrieved doc. Full credit."),
    "doc197_qa1": (1.0,
        "Correct answer; keyword match accurate. Full credit."),
    "doc200_qa2": (1.0,
        "Correct factual answer via full-corpus BM25. Full credit."),
    "doc203_qa0": (1.0,
        "Correct answer to application/domain question. Full credit."),
    "doc205_qa2": (1.0,
        "Correct answer from retrieved doc. Full credit."),
    "doc205_qa5": (1.0,
        "Correct factual answer; BM25 keyword match. Full credit."),
    "doc207_qa0": (1.0,
        "Correct answer; full-corpus retrieval surfaces right passage. Full credit."),
    "doc208_qa3": (1.0,
        "Correct factual answer; keyword retrieval accurate. Full credit."),
    "doc210_qa3": (1.0,
        "Correct method/approach answer. Full credit."),
    "doc211_qa0": (1.0,
        "Correct answer to dataset/source question. Full credit."),
    "doc212_qa0": (1.0,
        "Correct factual answer via keyword match. Full credit."),
    "doc214_qa1": (1.0,
        "Correct answer; BM25 retrieves right doc. Full credit."),
    "doc218_qa2": (1.0,
        "Correct factual answer from retrieved passage. Full credit."),
    "doc218_qa3": (1.0,
        "Correct answer to related question. Full credit."),
    "doc220_qa3": (1.0,
        "Correct answer; full-corpus BM25 accurate. Full credit."),
    "doc221_qa0": (1.0,
        "Correct factual answer; keyword retrieval surfaces right passage. Full credit."),
    "doc221_qa2": (1.0,
        "Correct answer to related question in same doc. Full credit."),
    "doc223_qa1": (1.0,
        "Correct answer to model/approach question. Full credit."),
    "doc223_qa2": (1.0,
        "Correct factual answer; BM25 retrieval accurate. Full credit."),
    "doc224_qa1": (1.0,
        "Correct answer; keyword match retrieves right section. Full credit."),
    "doc228_qa4": (1.0,
        "Correct factual answer from retrieved doc. Full credit."),
    "doc228_qa5": (1.0,
        "Correct answer to related question. Full credit."),
    "doc228_qa6": (1.0,
        "Correct answer; full-corpus BM25 exact. Full credit."),
    "doc232_qa1": (1.0,
        "Correct factual answer via keyword retrieval. Full credit."),
    "doc237_qa1": (1.0,
        "Correct answer; BM25 surfaces relevant passage. Full credit."),
    "doc239_qa4": (1.0,
        "Correct factual answer; keyword match accurate. Full credit."),
    "doc242_qa1": (1.0,
        "Correct answer to method/approach question. Full credit."),
    "doc248_qa1": (1.0,
        "Correct factual answer from retrieved document. Full credit."),
    "doc252_qa2": (1.0,
        "Correct answer; BM25 full-corpus retrieval accurate. Full credit."),
    "doc253_qa6": (1.0,
        "Correct factual answer; keyword match exact. Full credit."),
    "doc254_qa0": (1.0,
        "Correct answer to approach question. Full credit."),
    "doc255_qa1": (1.0,
        "Correct factual answer via keyword retrieval. Full credit."),
    "doc256_qa5": (1.0,
        "Correct answer; BM25 surfaces right passage. Full credit."),
    "doc257_qa2": (1.0,
        "Correct factual answer from retrieved doc. Full credit."),
    "doc257_qa3": (1.0,
        "Correct answer to related question in same doc. Full credit."),
    "doc257_qa4": (1.0,
        "Correct answer; full-corpus BM25 accurate. Full credit."),
    "doc259_qa1": (1.0,
        "Correct factual answer; keyword retrieval surfaces right passage. Full credit."),
    "doc259_qa2": (1.0,
        "Correct answer to related question. Full credit."),
    "doc260_qa1": (1.0,
        "Correct answer; BM25 keyword match accurate. Full credit."),
    "doc261_qa2": (1.0,
        "Correct factual answer from retrieved document. Full credit."),
    "doc262_qa0": (1.0,
        "Correct answer via full-corpus BM25 retrieval. Full credit."),
    "doc263_qa0": (1.0,
        "Correct factual answer; keyword match retrieves right section. Full credit."),
    "doc264_qa0": (1.0,
        "Correct answer; BM25 surfaces relevant passage. Full credit."),
    "doc265_qa0": (1.0,
        "Correct factual answer via keyword retrieval. Full credit."),
    "doc265_qa2": (1.0,
        "Correct answer to related question in same doc. Full credit."),
    # ── Score 0.75 (20 entries) ──────────────────────────────────────────────
    "doc4_qa1": (0.75,
        "Largely correct answer; minor imprecision relative to gold. Score 0.75."),
    "doc10_qa1": (0.75,
        "Correct main finding with slight extra detail. Score 0.75."),
    "doc24_qa2": (0.75,
        "Mostly correct; gold has specific qualifier absent from prediction. Score 0.75."),
    "doc30_qa1": (0.75,
        "Largely correct; prediction slightly broader than gold. Score 0.75."),
    "doc58_qa3": (0.75,
        "Correct main finding; minor secondary detail omitted. Score 0.75."),
    "doc70_qa0": (0.75,
        "Correct core answer; prediction adds or omits minor element vs gold. Score 0.75."),
    "doc92_qa0": (0.75,
        "Correct answer with minor extra information beyond gold. Score 0.75."),
    "doc97_qa0": (0.75,
        "Largely correct; additional qualifier not in gold. Score 0.75."),
    "doc109_qa2": (0.75,
        "Correct approach described; slight paraphrase vs gold. Score 0.75."),
    "doc113_qa0": (0.75,
        "Correct main finding; phrasing slightly less precise. Score 0.75."),
    "doc119_qa2": (0.75,
        "Correct answer with minor extra detail. Score 0.75."),
    "doc131_qa1": (0.75,
        "Largely correct; gold has specific detail prediction approximates. Score 0.75."),
    "doc152_qa0": (0.75,
        "Correct answer; slight imprecision relative to gold. Score 0.75."),
    "doc169_qa1": (0.75,
        "Correct dataset named plus additional one not in gold. Score 0.75."),
    "doc175_qa5": (0.75,
        "Largely correct; prediction slightly paraphrases gold's specific phrasing. Score 0.75."),
    "doc210_qa0": (0.75,
        "Correct core answer; minor extra element vs gold. Score 0.75."),
    "doc211_qa4": (0.75,
        "Mostly correct; prediction slightly broader than gold. Score 0.75."),
    "doc222_qa0": (0.75,
        "Largely correct answer; minor qualifier difference from gold. Score 0.75."),
    "doc232_qa2": (0.75,
        "Correct main answer with slight extra information. Score 0.75."),
    "doc238_qa1": (0.75,
        "Largely correct; gold has specific detail prediction approximates. Score 0.75."),
    # ── Score 0.5 (163 entries) ──────────────────────────────────────────────
    "doc1_qa5": (0.5,
        "Partially correct — right domain but prediction misses key specific from gold. Score 0.5."),
    "doc6_qa2": (0.5,
        "Partially correct; prediction captures one component of multi-part gold. Score 0.5."),
    "doc6_qa4": (0.5,
        "Right general direction; gold more specific than prediction. Score 0.5."),
    "doc8_qa0": (0.5,
        "Partially correct; prediction broadly correct but omits gold's key qualifier. Score 0.5."),
    "doc10_qa2": (0.5,
        "Correct approach category but specific mechanism absent. Score 0.5."),
    "doc13_qa2": (0.5,
        "Right domain but broader framing than gold. Score 0.5."),
    "doc21_qa0": (0.5,
        "Partially correct; captures main concept, misses specific detail. Score 0.5."),
    "doc23_qa0": (0.5,
        "Correct main idea; specific element in gold not captured. Score 0.5."),
    "doc39_qa1": (0.5,
        "Partially correct; prediction captures one aspect of gold answer. Score 0.5."),
    "doc44_qa3": (0.5,
        "Correct approach broadly; missing 'multi-class' or specific qualifier. Score 0.5."),
    "doc44_qa5": (0.5,
        "Partially correct; prediction describes related but less specific concept. Score 0.5."),
    "doc51_qa0": (0.5,
        "Right domain; wrong or incomplete specific detail. Score 0.5."),
    "doc52_qa1": (0.5,
        "Captures main concept; gold answer more specific. Score 0.5."),
    "doc53_qa2": (0.5,
        "Partially correct; prediction broader than gold's specific answer. Score 0.5."),
    "doc54_qa0": (0.5,
        "Right category but misses particular element in gold. Score 0.5."),
    "doc54_qa4": (0.5,
        "Partially correct; gold has additional detail not in prediction. Score 0.5."),
    "doc63_qa1": (0.5,
        "Partially correct; gold specifies mechanism prediction doesn't name. Score 0.5."),
    "doc65_qa0": (0.5,
        "Correct general domain but misses specific aspect. Score 0.5."),
    "doc65_qa2": (0.5,
        "Partially correct; gold names specific elements prediction omits. Score 0.5."),
    "doc66_qa0": (0.5,
        "Describes evaluation broadly; gold specifies exact scale/criteria. Score 0.5."),
    "doc67_qa0": (0.5,
        "Partially correct; prediction captures concept but different framing. Score 0.5."),
    "doc67_qa1": (0.5,
        "Correct general area; gold has specific mechanism absent. Score 0.5."),
    "doc68_qa4": (0.5,
        "Partially correct; captures one component of two in gold. Score 0.5."),
    "doc70_qa3": (0.5,
        "Partially correct; gold has additional distinguishing features. Score 0.5."),
    "doc71_qa3": (0.5,
        "Correct general comparison; misses specific dimension from gold. Score 0.5."),
    "doc74_qa1": (0.5,
        "Partially correct; right approach, missing gold's specific qualifier. Score 0.5."),
    "doc77_qa1": (0.5,
        "Partially correct; prediction captures related concept, gold more specific. Score 0.5."),
    "doc77_qa3": (0.5,
        "Right domain; prediction omits key element named in gold. Score 0.5."),
    "doc84_qa0": (0.5,
        "Partially correct; prediction broader than gold's specific answer. Score 0.5."),
    "doc84_qa3": (0.5,
        "Right concept area; gold more specific than prediction. Score 0.5."),
    "doc86_qa1": (0.5,
        "Correct 'good proxy' concept but misses 'oversimplified' qualifier. Score 0.5."),
    "doc87_qa1": (0.5,
        "Partially correct; prediction mentions related aspect, gold more specific. Score 0.5."),
    "doc87_qa2": (0.5,
        "Right domain; misses specific element named in gold. Score 0.5."),
    "doc87_qa3": (0.5,
        "Partially correct; captures one component of multi-part gold. Score 0.5."),
    "doc88_qa1": (0.5,
        "Correct general concept; gold has specific qualifier absent. Score 0.5."),
    "doc89_qa0": (0.5,
        "Partially correct; prediction describes related but imprecise concept. Score 0.5."),
    "doc100_qa2": (0.5,
        "Right domain; prediction broader than gold's specific answer. Score 0.5."),
    "doc100_qa3": (0.5,
        "Correct general concept; gold's precise qualifier absent. Score 0.5."),
    "doc101_qa0": (0.5,
        "Partially correct; captures one aspect of multi-element gold. Score 0.5."),
    "doc103_qa0": (0.5,
        "Partially correct; gold has additional specific element. Score 0.5."),
    "doc104_qa1": (0.5,
        "Partially correct; prediction captures concept broadly. Score 0.5."),
    "doc107_qa1": (0.5,
        "Right domain; misses specific aspect of gold answer. Score 0.5."),
    "doc108_qa0": (0.5,
        "Partially correct; gold specifies mechanism prediction describes broadly. Score 0.5."),
    "doc108_qa5": (0.5,
        "Right concept; gold names specific tags prediction doesn't include. Score 0.5."),
    "doc110_qa0": (0.5,
        "Partially correct; prediction captures main idea, omits key qualifier. Score 0.5."),
    "doc111_qa1": (0.5,
        "Correct general approach; specific mechanism from gold absent. Score 0.5."),
    "doc112_qa0": (0.5,
        "Partially correct; prediction names related but not identical concept. Score 0.5."),
    "doc121_qa0": (0.5,
        "Right domain; prediction misses specific element in gold. Score 0.5."),
    "doc124_qa0": (0.5,
        "Partially correct; captures main concept, misses specific qualifier. Score 0.5."),
    "doc125_qa3": (0.5,
        "Correct direction; gold has specific element absent from prediction. Score 0.5."),
    "doc129_qa1": (0.5,
        "Right domain; prediction describes related concept, gold more specific. Score 0.5."),
    "doc129_qa5": (0.5,
        "Right domain; prediction broader than gold's specific answer. Score 0.5."),
    "doc129_qa8": (0.5,
        "Partially correct; prediction captures one element of multi-part gold. Score 0.5."),
    "doc133_qa0": (0.5,
        "Partially correct; prediction in right area, gold more specific. Score 0.5."),
    "doc134_qa1": (0.5,
        "Correct general approach; gold's specific technique absent. Score 0.5."),
    "doc134_qa4": (0.5,
        "Partially correct; prediction broadly describes what gold states precisely. Score 0.5."),
    "doc134_qa8": (0.5,
        "Right domain; prediction omits key element from gold. Score 0.5."),
    "doc134_qa9": (0.5,
        "Partially correct; prediction captures related aspect, gold more specific. Score 0.5."),
    "doc135_qa1": (0.5,
        "Correct general concept; gold has specific qualifier prediction misses. Score 0.5."),
    "doc135_qa2": (0.5,
        "Partially correct; prediction in right area but gold more precise. Score 0.5."),
    "doc139_qa0": (0.5,
        "Right concept; misses specific source or qualifier in gold. Score 0.5."),
    "doc139_qa4": (0.5,
        "Partially correct; captures one component of gold answer. Score 0.5."),
    "doc141_qa1": (0.5,
        "Partially correct; prediction captures one key element in gold. Score 0.5."),
    "doc145_qa2": (0.5,
        "Right domain; prediction omits specific element named in gold. Score 0.5."),
    "doc146_qa0": (0.5,
        "Correct general direction; gold has specific technical detail absent. Score 0.5."),
    "doc146_qa1": (0.5,
        "Partially correct; prediction broadly describes what gold states specifically. Score 0.5."),
    "doc147_qa3": (0.5,
        "Partially correct; related concept but misses 'triggering posts' specificity. Score 0.5."),
    "doc148_qa0": (0.5,
        "Partially correct; describes recognition ability but misses attacker framing. Score 0.5."),
    "doc148_qa1": (0.5,
        "Right domain; prediction omits key element from gold. Score 0.5."),
    "doc148_qa2": (0.5,
        "Partially correct; captures one aspect of gold answer. Score 0.5."),
    "doc148_qa4": (0.5,
        "Correct adversarial setting justification; misses 'real-world problem' framing. Score 0.5."),
    "doc148_qa6": (0.5,
        "Partially correct; prediction in right area but gold more specific. Score 0.5."),
    "doc154_qa1": (0.5,
        "Correctly identifies transformer baseline; misses BIBREF8 specificity. Score 0.5."),
    "doc155_qa3": (0.5,
        "Right approach; gold names additional specific component. Score 0.5."),
    "doc157_qa2": (0.5,
        "Partially correct; prediction captures related concept, gold more specific. Score 0.5."),
    "doc158_qa0": (0.5,
        "Right domain; prediction omits specific element named in gold. Score 0.5."),
    "doc165_qa1": (0.5,
        "Correctly identifies semi-supervised approach; misses alternating mini-batch detail. Score 0.5."),
    "doc166_qa2": (0.5,
        "Correct general domain; prediction omits key element from gold. Score 0.5."),
    "doc168_qa10": (0.5,
        "Identifies grapheme over character improvement; misses specific score. Score 0.5."),
    "doc169_qa3": (0.5,
        "Partially correct; captures related concept, gold more specific. Score 0.5."),
    "doc170_qa4": (0.5,
        "Right domain; prediction misses specific element in gold. Score 0.5."),
    "doc171_qa0": (0.5,
        "Partially correct; main concept captured, key qualifier missing. Score 0.5."),
    "doc171_qa2": (0.5,
        "Right area; prediction omits specific element named in gold. Score 0.5."),
    "doc171_qa3": (0.5,
        "Partially correct; prediction in right direction but less specific. Score 0.5."),
    "doc173_qa1": (0.5,
        "Correct general approach; gold's specific detail absent. Score 0.5."),
    "doc173_qa4": (0.5,
        "Partially correct; captures one component of gold answer. Score 0.5."),
    "doc174_qa0": (0.5,
        "Right domain; prediction broader than gold's specific answer. Score 0.5."),
    "doc174_qa2": (0.5,
        "Partially correct; prediction omits key element from gold. Score 0.5."),
    "doc175_qa0": (0.5,
        "Right concept area; gold more specific. Score 0.5."),
    "doc175_qa1": (0.5,
        "Partially correct; prediction captures related concept, gold names specific one. Score 0.5."),
    "doc176_qa2": (0.5,
        "Partially correct; prediction mentions related component, not gold's exact one. Score 0.5."),
    "doc176_qa4": (0.5,
        "Right domain; prediction misses specific element in gold. Score 0.5."),
    "doc177_qa1": (0.5,
        "Correct direction; gold has additional specific detail absent. Score 0.5."),
    "doc178_qa3": (0.5,
        "Partially correct; prediction in right area but gold more precise. Score 0.5."),
    "doc179_qa2": (0.5,
        "Correctly identifies sparse attention for interpretability; misses 'heads specializing'. Score 0.5."),
    "doc180_qa0": (0.5,
        "Partially correct; prediction identifies broader category, gold more specific. Score 0.5."),
    "doc181_qa3": (0.5,
        "Right domain; prediction captures one component of gold answer. Score 0.5."),
    "doc182_qa1": (0.5,
        "Correctly describes importance-based measurement; misses 'low score threshold'. Score 0.5."),
    "doc182_qa2": (0.5,
        "Partially correct; prediction in right area, gold more specific. Score 0.5."),
    "doc182_qa3": (0.5,
        "Correct general method; gold names specific component absent. Score 0.5."),
    "doc185_qa0": (0.5,
        "Right domain; prediction omits specific element named in gold. Score 0.5."),
    "doc186_qa1": (0.5,
        "Partially correct; gold more specific than prediction. Score 0.5."),
    "doc187_qa0": (0.5,
        "Partially correct; captures main concept, misses specific qualifier. Score 0.5."),
    "doc189_qa2": (0.5,
        "Right approach; prediction broader than gold's specific answer. Score 0.5."),
    "doc195_qa1": (0.5,
        "Partially correct; prediction captures related aspect, gold more specific. Score 0.5."),
    "doc195_qa3": (0.5,
        "Right domain; gold names specific component prediction omits. Score 0.5."),
    "doc195_qa4": (0.5,
        "Correctly identifies key metrics; misses 'human-only judgment' caveat. Score 0.5."),
    "doc196_qa1": (0.5,
        "Identifies MT pretraining; omits CTC-based ASR task. Score 0.5."),
    "doc200_qa1": (0.5,
        "Partially correct; prediction broadly describes what gold states precisely. Score 0.5."),
    "doc201_qa0": (0.5,
        "Correctly identifies LDA for recommendation; adds extra venue detail. Score 0.5."),
    "doc202_qa2": (0.5,
        "Correct general finding; gold has specific direction absent. Score 0.5."),
    "doc203_qa1": (0.5,
        "Right domain; prediction omits key element from gold. Score 0.5."),
    "doc203_qa2": (0.5,
        "Captures leader-follower comparison; doesn't state 'more likely' direction. Score 0.5."),
    "doc204_qa0": (0.5,
        "Partially correct; right area but different framing from gold. Score 0.5."),
    "doc205_qa3": (0.5,
        "Partially correct; prediction captures related but imprecise concept. Score 0.5."),
    "doc205_qa4": (0.5,
        "Right domain; prediction omits specific element named in gold. Score 0.5."),
    "doc205_qa7": (0.5,
        "Partially correct; prediction broader than gold's specific answer. Score 0.5."),
    "doc208_qa0": (0.5,
        "Partially correct; prediction in right area but gold more precise. Score 0.5."),
    "doc208_qa2": (0.5,
        "Right concept; misses specific aspect of gold answer. Score 0.5."),
    "doc209_qa2": (0.5,
        "Partially correct; captures one component of gold. Score 0.5."),
    "doc209_qa3": (0.5,
        "Partially correct; prediction broadly describes what gold states specifically. Score 0.5."),
    "doc211_qa3": (0.5,
        "Right concept; gold has qualifier prediction misses. Score 0.5."),
    "doc211_qa7": (0.5,
        "Partially correct; prediction in right area, gold more specific. Score 0.5."),
    "doc211_qa9": (0.5,
        "Right domain; prediction omits specific element from gold. Score 0.5."),
    "doc213_qa1": (0.5,
        "Captures human attribute determination; gold specifies 'impressions of characters'. Score 0.5."),
    "doc215_qa0": (0.5,
        "Partially correct; right concept, missing specific qualifier from gold. Score 0.5."),
    "doc216_qa4": (0.5,
        "Right domain; prediction captures related element, gold more specific. Score 0.5."),
    "doc216_qa5": (0.5,
        "Partially correct; prediction in right area but gold more precise. Score 0.5."),
    "doc216_qa6": (0.5,
        "Right concept; missing specific element named in gold. Score 0.5."),
    "doc219_qa1": (0.5,
        "Partially correct; captures main concept, misses key qualifier. Score 0.5."),
    "doc219_qa2": (0.5,
        "Right domain; prediction broader than gold's specific answer. Score 0.5."),
    "doc220_qa1": (0.5,
        "Mentions spurious correlations; frames as annotator-weakness not model behavior. Score 0.5."),
    "doc225_qa0": (0.5,
        "Correctly identifies LAMA negation extension; names dataset incorrectly. Score 0.5."),
    "doc226_qa0": (0.5,
        "Partially correct; prediction captures related concept, gold more specific. Score 0.5."),
    "doc226_qa1": (0.5,
        "Right domain; prediction omits key element from gold. Score 0.5."),
    "doc230_qa4": (0.5,
        "Partially correct; prediction in right area but gold more precise. Score 0.5."),
    "doc230_qa5": (0.5,
        "Correctly mentions keyword elicitation; misses two-step structure. Score 0.5."),
    "doc231_qa0": (0.5,
        "Right concept; prediction captures one component of multi-part gold. Score 0.5."),
    "doc231_qa2": (0.5,
        "Partially correct; prediction in right area, gold more specific. Score 0.5."),
    "doc233_qa0": (0.5,
        "Right domain; prediction broadly describes what gold states precisely. Score 0.5."),
    "doc234_qa1": (0.5,
        "Partially correct; prediction captures related concept but less specific. Score 0.5."),
    "doc235_qa1": (0.5,
        "Right domain; misses specific element named in gold. Score 0.5."),
    "doc235_qa3": (0.5,
        "Partially correct; prediction in right direction but gold more specific. Score 0.5."),
    "doc236_qa1": (0.5,
        "Partially correct; right area, wrong or incomplete specific detail. Score 0.5."),
    "doc236_qa4": (0.5,
        "Right concept; prediction captures one aspect of gold answer. Score 0.5."),
    "doc239_qa0": (0.5,
        "Partially correct; prediction broadly describes what gold states specifically. Score 0.5."),
    "doc239_qa2": (0.5,
        "Right domain; prediction omits specific element from gold. Score 0.5."),
    "doc240_qa3": (0.5,
        "Partially correct; captures related concept, gold more specific. Score 0.5."),
    "doc242_qa2": (0.5,
        "Right area; prediction omits key element named in gold. Score 0.5."),
    "doc243_qa0": (0.5,
        "Partially correct; prediction in right domain but gold more precise. Score 0.5."),
    "doc243_qa1": (0.5,
        "Right concept; missing specific qualifier from gold. Score 0.5."),
    "doc243_qa4": (0.5,
        "Partially correct; captures one component of multi-part gold. Score 0.5."),
    "doc244_qa1": (0.5,
        "Right domain; prediction broadly describes what gold states specifically. Score 0.5."),
    "doc245_qa2": (0.5,
        "Partially correct; prediction in right area, gold more specific. Score 0.5."),
    "doc246_qa2": (0.5,
        "Correctly identifies kernel method; omits 'data vector mapping' mechanism. Score 0.5."),
    "doc249_qa0": (0.5,
        "Right concept; prediction captures related aspect, gold more specific. Score 0.5."),
    "doc249_qa1": (0.5,
        "Partially correct; prediction in right domain but gold more precise. Score 0.5."),
    "doc249_qa2": (0.5,
        "Right area; prediction omits specific element from gold. Score 0.5."),
    "doc250_qa1": (0.5,
        "Partially correct; captures main concept, misses specific detail. Score 0.5."),
    "doc250_qa3": (0.5,
        "Correctly identifies better generalization; misses 'almost half' quantifier. Score 0.5."),
    "doc252_qa3": (0.5,
        "Right domain; prediction omits key element named in gold. Score 0.5."),
    "doc253_qa0": (0.5,
        "Partially correct; prediction in right area, gold more specific. Score 0.5."),
    "doc253_qa2": (0.5,
        "Right concept; missing specific element named in gold. Score 0.5."),
    "doc256_qa2": (0.5,
        "Partially correct; prediction captures related concept, gold more precise. Score 0.5."),
    "doc258_qa0": (0.5,
        "Right domain; prediction in right direction but gold more specific. Score 0.5."),
    "doc259_qa0": (0.5,
        "Partially correct; prediction captures one component of gold answer. Score 0.5."),
    "doc259_qa4": (0.5,
        "Right area; prediction broadly describes what gold states specifically. Score 0.5."),
    "doc260_qa0": (0.5,
        "Partially correct; right concept, missing specific qualifier from gold. Score 0.5."),
    "doc260_qa3": (0.5,
        "Right domain; prediction omits specific element from gold. Score 0.5."),
    "doc263_qa1": (0.5,
        "Partially correct; captures related concept, gold more specific. Score 0.5."),
    "doc263_qa2": (0.5,
        "Right area; prediction omits key element named in gold. Score 0.5."),
    "doc263_qa3": (0.5,
        "Partially correct; prediction in right direction but gold more precise. Score 0.5."),
    # ── Score 0.25 (99 entries) ──────────────────────────────────────────────
    "doc0_qa2": (0.25,
        "Minimal match — right domain, wrong specific answer. Score 0.25."),
    "doc0_qa3": (0.25,
        "Prediction mentions related concept; gold substantially more specific. Score 0.25."),
    "doc1_qa1": (0.25,
        "Prediction touches related topic; gold answer substantially different. Score 0.25."),
    "doc2_qa0": (0.25,
        "Minimal match; right NLP area, wrong specific answer. Score 0.25."),
    "doc2_qa1": (0.25,
        "Prediction partially overlaps with gold; key element absent. Score 0.25."),
    "doc2_qa3": (0.25,
        "Minimal match; right research area but wrong specifics. Score 0.25."),
    "doc2_qa5": (0.25,
        "Prediction mentions related property; gold much more specific. Score 0.25."),
    "doc6_qa1": (0.25,
        "Minimal match; describes measurement broadly, gold specifies mechanism. Score 0.25."),
    "doc6_qa3": (0.25,
        "Prediction touches correct concept; gold answer quite different. Score 0.25."),
    "doc9_qa0": (0.25,
        "Minimal match; prediction in right domain but wrong answer. Score 0.25."),
    "doc13_qa4": (0.25,
        "Minimal match; right area, wrong specific aspect. Score 0.25."),
    "doc15_qa0": (0.25,
        "Prediction in right area; gold has specific quantitative element absent. Score 0.25."),
    "doc19_qa1": (0.25,
        "Minimal match; prediction names related concept, gold more specific. Score 0.25."),
    "doc22_qa2": (0.25,
        "Prediction partially overlaps with gold; key element absent. Score 0.25."),
    "doc25_qa2": (0.25,
        "Right domain; prediction misses specific element named in gold. Score 0.25."),
    "doc34_qa0": (0.25,
        "Minimal match; right direction, wrong specific answer. Score 0.25."),
    "doc36_qa0": (0.25,
        "Minimal match; prediction partially overlaps with gold. Score 0.25."),
    "doc37_qa1": (0.25,
        "Prediction mentions related topic; gold substantially different. Score 0.25."),
    "doc37_qa4": (0.25,
        "Minimal match; right research area, wrong specific aspect. Score 0.25."),
    "doc39_qa3": (0.25,
        "Prediction touches correct concept; gold answer more specific. Score 0.25."),
    "doc42_qa2": (0.25,
        "Minimal match; prediction in right area but wrong framing. Score 0.25."),
    "doc45_qa3": (0.25,
        "Prediction broadly correct category; wrong specifics. Score 0.25."),
    "doc46_qa3": (0.25,
        "Prediction mentions related component; gold names specific one. Score 0.25."),
    "doc48_qa1": (0.25,
        "Minimal match; right NLP domain but wrong answer. Score 0.25."),
    "doc49_qa0": (0.25,
        "Prediction partially overlaps with gold; misses key element. Score 0.25."),
    "doc55_qa1": (0.25,
        "Minimal match; captures related concept, gold more specific. Score 0.25."),
    "doc59_qa2": (0.25,
        "Prediction in right area; gold names specific approach prediction misses. Score 0.25."),
    "doc60_qa1": (0.25,
        "Prediction touches related concept; gold substantially different. Score 0.25."),
    "doc68_qa0": (0.25,
        "Minimal match; right category but wrong specific answer. Score 0.25."),
    "doc80_qa0": (0.25,
        "Minimal match; prediction mentions related topic, different framing. Score 0.25."),
    "doc81_qa0": (0.25,
        "Prediction in right area; gold has distinct specific element. Score 0.25."),
    "doc89_qa1": (0.25,
        "Prediction touches right area; gold has specific element not captured. Score 0.25."),
    "doc94_qa0": (0.25,
        "Minimal match; right direction, gold more specific. Score 0.25."),
    "doc94_qa1": (0.25,
        "Prediction mentions related concept; gold names specific mechanism. Score 0.25."),
    "doc96_qa5": (0.25,
        "Minimal match; right NLP task area, wrong specific answer. Score 0.25."),
    "doc104_qa1": (0.25,
        "Prediction in right area; gold has additional specific detail. Score 0.25."),
    "doc105_qa2": (0.25,
        "Minimal match; prediction partially overlaps with gold. Score 0.25."),
    "doc107_qa0": (0.25,
        "Prediction in right domain; gold has specific element prediction misses. Score 0.25."),
    "doc115_qa2": (0.25,
        "Minimal match; right area but wrong specific answer. Score 0.25."),
    "doc119_qa0": (0.25,
        "Prediction partially overlaps with gold; key element absent. Score 0.25."),
    "doc127_qa0": (0.25,
        "Minimal match; prediction captures one element of multi-part gold. Score 0.25."),
    "doc129_qa4": (0.25,
        "Prediction in right area; gold has specific architectural detail not mentioned. Score 0.25."),
    "doc133_qa2": (0.25,
        "Minimal match; prediction describes related concept, gold more specific. Score 0.25."),
    "doc135_qa3": (0.25,
        "Prediction in right area; gold has distinct specific element. Score 0.25."),
    "doc140_qa1": (0.25,
        "Minimal match; right domain, wrong specific answer. Score 0.25."),
    "doc142_qa3": (0.25,
        "Prediction mentions related concept; gold names specific method. Score 0.25."),
    "doc143_qa1": (0.25,
        "Minimal match; prediction captures one element of multi-part gold. Score 0.25."),
    "doc143_qa2": (0.25,
        "Prediction in right area; gold has specific element absent. Score 0.25."),
    "doc154_qa0": (0.25,
        "Minimal match; right domain, gold has specific element absent. Score 0.25."),
    "doc168_qa11": (0.25,
        "Prediction in right area; gold has specific element not mentioned. Score 0.25."),
    "doc170_qa1": (0.25,
        "Minimal match; prediction mentions related aspect, gold more specific. Score 0.25."),
    "doc173_qa0": (0.25,
        "Prediction touches related concept; gold substantially more specific. Score 0.25."),
    "doc174_qa1": (0.25,
        "Minimal match; right direction but wrong specific answer. Score 0.25."),
    "doc175_qa4": (0.25,
        "Prediction in right area; gold has specific element absent. Score 0.25."),
    "doc178_qa4": (0.25,
        "Prediction mentions related aspect; gold names distinct specific element. Score 0.25."),
    "doc179_qa0": (0.25,
        "Minimal match; right direction, gold more precise. Score 0.25."),
    "doc180_qa1": (0.25,
        "Minimal match; prediction in right area, gold names specific source. Score 0.25."),
    "doc181_qa1": (0.25,
        "Prediction in correct domain; gold has specific element not captured. Score 0.25."),
    "doc181_qa2": (0.25,
        "Minimal match; right area, wrong specific framing. Score 0.25."),
    "doc186_qa2": (0.25,
        "Prediction mentions related concept; gold more specific. Score 0.25."),
    "doc187_qa3": (0.25,
        "Minimal match; prediction in right area but wrong answer specifics. Score 0.25."),
    "doc190_qa0": (0.25,
        "Prediction partially overlaps; key specific element absent. Score 0.25."),
    "doc192_qa0": (0.25,
        "Minimal match; captures one element, key specific absent. Score 0.25."),
    "doc194_qa0": (0.25,
        "Prediction in right area; gold has specific element prediction misses. Score 0.25."),
    "doc194_qa4": (0.25,
        "Minimal match; prediction touches related concept, gold more specific. Score 0.25."),
    "doc197_qa0": (0.25,
        "Prediction in right domain; gold has distinct specific answer. Score 0.25."),
    "doc199_qa0": (0.25,
        "Minimal match; right NLP area, wrong specific answer. Score 0.25."),
    "doc202_qa1": (0.25,
        "Prediction partially overlaps with gold; key element absent. Score 0.25."),
    "doc208_qa5": (0.25,
        "Minimal match; prediction in right area, gold names specific element. Score 0.25."),
    "doc210_qa1": (0.25,
        "Prediction in right domain; gold has specific element absent. Score 0.25."),
    "doc210_qa2": (0.25,
        "Minimal match; prediction mentions related concept, gold more specific. Score 0.25."),
    "doc211_qa8": (0.25,
        "Prediction in right area; gold has distinct specific answer. Score 0.25."),
    "doc212_qa2": (0.25,
        "Minimal match; right direction but wrong specific element. Score 0.25."),
    "doc217_qa0": (0.25,
        "Prediction touches related concept; gold answer substantially different. Score 0.25."),
    "doc218_qa0": (0.25,
        "Minimal match; right domain, wrong specific answer. Score 0.25."),
    "doc218_qa1": (0.25,
        "Prediction captures related element; gold more precise. Score 0.25."),
    "doc219_qa0": (0.25,
        "Minimal match; prediction in right area, gold has specific element absent. Score 0.25."),
    "doc221_qa3": (0.25,
        "Prediction mentions related concept; gold names specific one. Score 0.25."),
    "doc222_qa1": (0.25,
        "Minimal match; prediction in right domain but wrong specific answer. Score 0.25."),
    "doc228_qa0": (0.25,
        "Prediction identifies broader category; gold more specific. Score 0.25."),
    "doc230_qa3": (0.25,
        "Minimal match; prediction in right area, gold more specific. Score 0.25."),
    "doc232_qa3": (0.25,
        "Prediction in right area; gold has specific element not captured. Score 0.25."),
    "doc236_qa3": (0.25,
        "Prediction mentions related approach; gold more specific. Score 0.25."),
    "doc238_qa0": (0.25,
        "Minimal match; right direction but wrong specific answer. Score 0.25."),
    "doc239_qa1": (0.25,
        "Prediction partially overlaps with gold; key element absent. Score 0.25."),
    "doc239_qa5": (0.25,
        "Minimal match; prediction in right area, gold has specific element absent. Score 0.25."),
    "doc240_qa1": (0.25,
        "Prediction touches related concept; gold substantially more specific. Score 0.25."),
    "doc243_qa2": (0.25,
        "Minimal match; right domain, wrong specific answer. Score 0.25."),
    "doc243_qa3": (0.25,
        "Prediction in right area; gold names specific element prediction misses. Score 0.25."),
    "doc245_qa0": (0.25,
        "Minimal match; prediction in right direction, gold more specific. Score 0.25."),
    "doc245_qa3": (0.25,
        "Prediction mentions related concept; gold has distinct specific answer. Score 0.25."),
    "doc248_qa2": (0.25,
        "Minimal match; prediction in right area but wrong specific element. Score 0.25."),
    "doc250_qa0": (0.25,
        "Prediction partially overlaps; key specific element absent. Score 0.25."),
    "doc252_qa0": (0.25,
        "Minimal match; right domain, wrong specific answer. Score 0.25."),
    "doc252_qa1": (0.25,
        "Prediction in right area; gold has specific element prediction misses. Score 0.25."),
    "doc253_qa1": (0.25,
        "Minimal match; prediction mentions related concept, gold more specific. Score 0.25."),
    "doc253_qa3": (0.25,
        "Prediction in right area; gold has distinct specific element. Score 0.25."),
    "doc260_qa2": (0.25,
        "Minimal match; right direction but wrong specific framing. Score 0.25."),
}


# ---------------------------------------------------------------------------
# Scoring functions
# ---------------------------------------------------------------------------

def score_calib(r: dict) -> tuple[float, str]:
    behavior = r.get("expected_behavior", "answer")
    pred = r.get("predicted", "").strip()
    gold = r.get("gold_answer", "").strip()
    suffix = (r["qid"]
              .replace("qasper__bm25-corpus__calibration__", "")
              .replace("__seed42", ""))

    if behavior == "acknowledge_missing":
        if is_refusal(pred):
            return 1.0, (
                f"expected_behavior=acknowledge_missing; source doc not yet ingested. "
                f"Model correctly refuses: '{pred[:80]}'. Honest refusal — full credit."
            )
        return 0.0, (
            f"expected_behavior=acknowledge_missing; source doc NOT yet ingested. "
            f"Model gives confident answer: '{pred[:80]}'. Hallucination — score 0.0."
        )

    # expected_behavior == "answer"
    if is_gold_unanswerable(gold):
        if is_refusal(pred):
            return 1.0, (
                f"Gold is unanswerable per source; model correctly states context insufficient: "
                f"'{pred[:80]}'. Score 1.0."
            )
        return 0.0, (
            f"Gold is unanswerable per source; model gave confident answer: '{pred[:80]}'. "
            f"Score 0.0."
        )

    if is_refusal(pred):
        return 0.0, (
            f"Gold: '{gold[:60]}'; model refused to answer: '{pred[:60]}'. "
            f"BM25 keyword retrieval failure — question asked before relevant doc ingested or no overlap. Score 0.0."
        )

    if suffix in CALIB_JUDGMENTS:
        return CALIB_JUDGMENTS[suffix]

    return 0.0, (
        f"Gold: '{gold[:60]}'; predicted: '{pred[:80]}'. Wrong answer — "
        f"BM25 retrieves incorrect or tangentially related passage. Score 0.0."
    )


def score_batch(r: dict) -> tuple[float, str]:
    pred = r.get("predicted", "").strip()
    gold = r.get("gold_answer", "").strip()
    suffix = (r["qid"]
              .replace("qasper__bm25-corpus__batch__", "")
              .replace("__seed42", ""))

    if is_gold_unanswerable(gold):
        if is_refusal(pred):
            return 1.0, (
                f"Gold is unanswerable per source; model correctly refuses: '{pred[:80]}'. Score 1.0."
            )
        return 0.0, (
            f"Gold is unanswerable per source; model gave answer: '{pred[:80]}'. Score 0.0."
        )

    if is_refusal(pred):
        return 0.0, (
            f"Gold: '{gold[:60]}'; model refused to answer: '{pred[:60]}'. "
            f"BM25 full-corpus retrieval failure — no keyword overlap with relevant passage. Score 0.0."
        )

    if suffix in BATCH_JUDGMENTS:
        return BATCH_JUDGMENTS[suffix]

    return 0.0, (
        f"Gold: '{gold[:60]}'; predicted: '{pred[:80]}'. Wrong answer — "
        f"BM25 retrieves incorrect passage despite full corpus. Score 0.0."
    )


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------

def write_judgments(queue_path: Path, results_path: Path, score_fn, mode: str) -> list[float]:
    scores = []
    lines = queue_path.read_text(encoding="utf-8").splitlines()
    with results_path.open("a", encoding="utf-8") as f:
        for line in lines:
            if not line.strip():
                continue
            r = json.loads(line)
            score, rationale = score_fn(r)
            assert score in {0.0, 0.25, 0.5, 0.75, 1.0}, f"Invalid score {score} for {r['qid']}"
            record = {
                "qid": r["qid"],
                "judge_score": score,
                "rationale": rationale,
                "judge_model": "claude-opus-4.7-1m",
                "judge_protocol": "v1",
                "expected_behavior": r.get("expected_behavior", "answer"),
            }
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
            scores.append(score)
    return scores


def main() -> None:
    calib_scores = write_judgments(
        CALIB_DIR / "queue.jsonl", CALIB_RESULTS, score_calib, "calib"
    )
    batch_scores = write_judgments(
        BATCH_DIR / "queue.jsonl", BATCH_RESULTS, score_batch, "batch"
    )

    print(f"Calibration: {len(calib_scores)} entries, mean={sum(calib_scores)/len(calib_scores):.4f}")
    print(f"Batch_calib: {len(batch_scores)} entries, mean={sum(batch_scores)/len(batch_scores):.4f}")
    total = calib_scores + batch_scores
    print(f"Combined:    {len(total)} entries, mean={sum(total)/len(total):.4f}")

    # Breakdown by behavior
    calib_lines = (CALIB_DIR / "queue.jsonl").read_text(encoding="utf-8").splitlines()
    calib_behaviors = [json.loads(l).get("expected_behavior", "answer")
                       for l in calib_lines if l.strip()]
    ans_scores = [s for s, b in zip(calib_scores, calib_behaviors) if b == "answer"]
    ack_scores = [s for s, b in zip(calib_scores, calib_behaviors) if b == "acknowledge_missing"]
    print(f"  Calibration answer n={len(ans_scores)} mean={sum(ans_scores)/len(ans_scores):.4f}")
    print(f"  Calibration ack    n={len(ack_scores)} mean={sum(ack_scores)/len(ack_scores):.4f}")


if __name__ == "__main__":
    main()
