"""Apply Claude 1-by-1 judgments for cuad__bm25-corpus-tuned__batch__seed42 (n=644).

Each (sfx -> (score, rationale)) below is a hand judgment by Claude against the
CUAD highlight/extraction rubric: 1.0 the gold clause/value is correctly
surfaced (or a correct 'unanswerable' when gold is empty); 0.75 substantially
correct, minor omission; 0.5 partial (right clause type, incomplete); 0.25 weakly
related / right category but wrong specific clause or no concrete extraction;
0.0 wrong value/clause, a clause pulled from a DIFFERENT contract, or a
refusal/abstention when the gold answer exists. NO heuristics.

Because n=644 is large, judgments are filled in resumable chunks (entries judged
~96 at a time). main() writes results.jsonl ONLY when every queue sfx is covered;
otherwise it reports how many remain so the next chunk can continue.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CELL = ROOT / "results" / "stage3" / "judge_queue" / "cuad__bm25-corpus-tuned__batch__seed42"

# sfx (doc{D}_qa{Q}) -> (judge_score, rationale)
J: dict[str, tuple[float, str]] = {
 # ---- chunk 0: entries 000-095 (docs 0-8) ----
 "doc0_qa0": (0.0, "Gold doc name 'DISTRIBUTOR AGREEMENT'; pred abstains though answer exists."),
 "doc0_qa1": (0.0, "Pred quotes a signature clause from a different (ADAMS GOLF) contract; gold party 'Distributor' not identified."),
 "doc0_qa2": (0.0, "Gold '7 Sept 1999'; pred abstains though date exists."),
 "doc0_qa3": (0.25, "Right category (effective date) but cites wrong clause 9.4 (contract-year def), not the gold commencement-on-last-Sample term."),
 "doc0_qa4": (0.25, "Right category (expiration) but asserts a fixed 2009 date; gold term runs 10yr from last-Sample delivery."),
 "doc0_qa5": (0.0, "Renewal terms quoted (7/5/15-yr, 'EKR') are from other contracts; gold = annual renewal up to 10yr."),
 "doc0_qa6": (0.0, "Gold governing law Illinois; pred abstains though clause exists."),
 "doc0_qa7": (0.0, "Gold exclusivity (no purchase from other source); pred abstains."),
 "doc0_qa8": (0.0, "Gold no-solicit-of-customers clause exists; pred abstains."),
 "doc0_qa9": (0.0, "Gold 12-month no-solicit-of-employees clause exists; pred abstains."),
 "doc0_qa10": (0.0, "Pred fabricates a 'Section 14.8 ROFR' from another contract; gold = 30-day exclusive-distributor option."),
 "doc0_qa11": (0.5, "Core right (assignment needs prior written consent) but adds an Affiliate carve-out not in this contract's gold (absolute consent)."),
 "doc0_qa12": (0.75, "Captures CPI-based price changes, uniform application to all distributors, cost/market reflection, profit-margin protection -- substantially matches gold."),
 "doc0_qa13": (1.0, "Matches gold: $250,000 PO by first of each month for 12 months."),
 "doc0_qa14": (0.25, "On-topic (license) but cites a 'License Grant Restrictions' section, not the gold exclusive-distributor appointment/grant."),
 "doc0_qa15": (0.25, "Right category (post-termination) but lists generic survival items; misses the gold 30-day product-repurchase option."),
 "doc0_qa16": (0.0, "Pred fabricates '24 months'; gold = warranty-work performance clause."),
 "doc0_qa17": (0.5, "Captures product-liability insurance + cancellation notice (gold) but adds extra insurance types and misses 'additional insured'/30-day."),
 "doc0_qa18": (0.0, "Gold covenant-not-to-sue (3yr IP) exists; pred abstains."),
 "doc1_qa0": (1.0, "Matches gold doc name 'Promotion and Distribution Agreement'."),
 "doc1_qa1": (0.75, "Correctly names the parties (Whitesmoke, Google); gold label 'Distributor' = Whitesmoke's role."),
 "doc1_qa2": (1.0, "Matches gold effective date 1 August 2011."),
 "doc1_qa3": (0.0, "Pred says expires 1 Aug 2012; gold term ends 31 Jul 2013 / on commitment -- wrong."),
 "doc1_qa4": (0.0, "Gold governing law = English law; pred abstains."),
 "doc1_qa5": (0.0, "Pred describes Change-of-Control from a different (ENERGOUS/DIALOG) contract; wrong contract."),
 "doc1_qa6": (0.0, "Gold anti-assignment clause exists; pred abstains."),
 "doc1_qa7": (0.0, "Gold Google-trademark license grant exists; pred abstains."),
 "doc1_qa8": (1.0, "Matches gold audit-rights clause (Google may audit Distributor records during Term + period after)."),
 "doc1_qa9": (0.25, "On-topic but speculative; does not extract the gold liability clause, reasons about confidentiality carve-out instead."),
 "doc1_qa10": (0.0, "Gold cap-on-liability formula exists; pred says no cap found -- abstains."),
 "doc1_qa11": (0.0, "Pred fabricates '24 months'; gold warranty period is redacted '[*]'."),
 "doc2_qa0": (0.5, "Gold 'SUPPLY CONTRACT'; pred 'Supply Agreement' -- right subject, wrong instrument noun."),
 "doc2_qa1": (0.75, "Identifies buyer + seller (gold = 'The seller:')."),
 "doc2_qa2": (0.0, "Gold term '5 years' exists; pred abstains."),
 "doc2_qa3": (0.0, "Gold governing law = PRC law/CISG; pred abstains."),
 "doc2_qa4": (0.0, "Pred fabricates '24 months'; gold = 7-day post-arrival nonconformity claim."),
 "doc2_qa5": (0.0, "Gold insurance (Seller 110% All Risks/War Risk) exists; pred abstains."),
 "doc3_qa0": (1.0, "Matches gold 'WEB SITE HOSTING AGREEMENT'."),
 "doc3_qa1": (1.0, "Names gold party 'Centrack International' plus i-on -- complete."),
 "doc3_qa2": (0.0, "Gold agreement date 6 April 1999; pred says 29 Oct 1999 -- wrong."),
 "doc3_qa3": (0.0, "Gold effective 1 April 1999; pred says 29 Oct 1999 -- wrong."),
 "doc3_qa4": (0.0, "Gold 6-month term; pred says expires 10yr after effective date -- wrong."),
 "doc3_qa5": (0.0, "Gold 1-month renewal periods; pred asserts 1-year renewals/5-yr term from another contract."),
 "doc3_qa6": (0.0, "Pred asserts 180-day notice; gold renewal-termination notice is the 1-month-renewal clause -- wrong specific."),
 "doc3_qa7": (1.0, "Matches gold governing law = Florida."),
 "doc3_qa8": (0.0, "Gold termination-for-convenience (30-day notice) exists; pred abstains."),
 "doc3_qa9": (0.25, "On-topic (limitation of liability) but says 'no cap'; misses gold 1-month-fees cap."),
 "doc4_qa0": (1.0, "Matches gold 'JOINT FILING AGREEMENT'."),
 "doc4_qa1": (0.0, "Gold party 'Co-Trustee' exists; pred abstains."),
 "doc4_qa2": (0.0, "Gold date 27 March 2020 exists; pred abstains."),
 "doc5_qa0": (1.0, "Matches gold 'ENDORSEMENT AGREEMENT'."),
 "doc5_qa1": (0.75, "Names ADAMS GOLF (gold) + CONSULTANT as parties, via signature clause."),
 "doc5_qa2": (0.0, "Gold date 13 Jan 2005 exists; pred abstains."),
 "doc5_qa3": (0.25, "Vague ('effective after signed'); misses gold commencement 1 Sept 2004."),
 "doc5_qa4": (0.0, "Pred says expires 21 Mar 2006; gold termination date redacted, commences 1 Sept 2004 -- wrong."),
 "doc5_qa5": (0.0, "Gold governing law = Kansas; pred says Delaware -- wrong."),
 "doc5_qa6": (0.0, "Gold non-compete clause exists; pred abstains."),
 "doc5_qa7": (0.0, "Gold exclusivity (exclusively play MANDATORY PRODUCT) exists; pred abstains."),
 "doc5_qa8": (0.0, "Pred cites 'Member' covenants from another contract; gold = 4A/4B/4C exception."),
 "doc5_qa9": (0.25, "Right category (anti-assignment) but gold is an absolute bar (no assignment/sublicense); pred says assignable with consent."),
 "doc5_qa10": (1.0, "Matches gold minimum-commitment (min events/yr on SPGA/PGA, repay if short)."),
 "doc5_qa11": (0.0, "Gold volume restriction (max [*] appearance days) exists; pred abstains."),
 "doc5_qa12": (0.0, "Gold license grant (CONSULTANT grants ADAMS GOLF endorsement rights) exists; pred abstains."),
 "doc6_qa0": (1.0, "Matches gold 'CONSULTING AGREEMENT'."),
 "doc6_qa1": (0.25, "Generic ('identify parties/addresses'); does not name gold party 'Gianluca Rotino'."),
 "doc6_qa2": (0.0, "Gold date 20 Jul 2018; pred says 11 May 2020 -- wrong."),
 "doc6_qa3": (0.0, "Gold effective 1 Jul 2018; pred says 11 May 2020 -- wrong."),
 "doc6_qa4": (0.0, "Pred asserts expiry 11 May 2021; gold has no fixed expiry (until termination) -- wrong."),
 "doc6_qa5": (0.0, "Gold governing law = Texas; pred says Delaware -- wrong."),
 "doc6_qa6": (0.0, "Gold non-compete (best-efforts segregate) exists; pred abstains."),
 "doc6_qa7": (0.0, "Gold termination-for-convenience (prior written notice) exists; pred abstains."),
 "doc6_qa8": (0.0, "Gold anti-assignment (no assign without Company consent) exists; pred abstains."),
 "doc6_qa9": (0.0, "Gold volume restriction (19hr/month cap) exists; pred abstains."),
 "doc6_qa10": (0.0, "Gold IP-ownership assignment (Consultant assigns inventions) exists; pred abstains."),
 "doc6_qa11": (0.0, "Gold license grant (non-excl perpetual license to Items) exists; pred abstains."),
 "doc6_qa12": (0.75, "Correctly affirms an irrevocable + perpetual license exists (gold attributes); no full span quote."),
 "doc6_qa13": (0.0, "Pred lists post-termination items from other contracts (Vyera/DIALOG); gold = deliver Invention property."),
 "doc7_qa0": (0.5, "Captures 'Joint Venture Agreement' but misses gold prefix 'Amendment and Termination of'."),
 "doc7_qa1": (1.0, "Names gold party 'Nissin Kogyo Co., Ltd.' plus all parties."),
 "doc7_qa2": (0.0, "Gold date 30 Oct 2019 exists; pred abstains."),
 "doc7_qa3": (0.0, "Gold effective upon VNBJ/VNBZ closings; pred says 30 Oct 2019 -- wrong."),
 "doc7_qa4": (0.0, "Pred asserts expiry 21 Feb 2021; gold tied to SPA closings/termination -- wrong."),
 "doc7_qa5": (0.0, "Gold governing law = Japan; pred says New York -- wrong."),
 "doc8_qa0": (0.5, "Gold 'CO-PROMOTION AGREEMENT'; pred 'Promotion Agreement' -- drops 'Co-'."),
 "doc8_qa1": (0.0, "Gold party 'Valeant' exists; pred abstains."),
 "doc8_qa2": (0.0, "Gold date 26 Sept 2018 exists; pred abstains."),
 "doc8_qa3": (0.0, "Gold effective-date definitional clause exists; pred abstains."),
 "doc8_qa4": (0.0, "Gold 4-year term; pred says 10 years -- wrong."),
 "doc8_qa5": (0.25, "Governing-law clause exists but state redacted '[***]'; pred abstains (lenient, state unknowable)."),
 "doc8_qa6": (0.0, "Gold non-compete clause exists; pred abstains."),
 "doc8_qa7": (0.0, "Gold co-exclusive promotion right exists; pred abstains."),
 "doc8_qa8": (0.0, "Gold competitive-restriction exception (2.3.2 carve-out) exists; pred abstains."),
 "doc8_qa9": (0.0, "Gold no-solicit-of-employees clause exists; pred abstains."),
 "doc8_qa10": (0.0, "Gold termination-for-convenience clause exists; pred abstains."),
 "doc8_qa11": (0.25, "On-topic (change of control) but generic; misses gold Affiliate-assignment + Dova successor specifics."),
 "doc8_qa12": (0.0, "Gold anti-assignment notice/consent procedure exists; pred abstains."),
 # ---- chunk 1: entries 096-195 (docs 8-16) ----
 "doc8_qa13": (0.0, "Gold detailed Net-Sales promotion-fee tiers exist; pred abstains."),
 "doc8_qa14": (0.75, "Captures the gold mechanism (Details below Quarterly Minimum -> reduced Applicable Percentage/fee); minor 'consecutive' overstatement."),
 "doc8_qa15": (0.0, "Gold IP-ownership (Dova owns Product Materials/Labeling) exists; pred abstains."),
 "doc8_qa16": (0.0, "Gold co-exclusive license grant exists; pred abstains."),
 "doc8_qa17": (0.5, "Right concept (license is non-transferable) but generic 'Licensee'; misses gold Valeant/Section-2.1 Affiliate carve-out."),
 "doc8_qa18": (0.0, "Gold Valeant->Dova affiliate license exists; pred abstains."),
 "doc8_qa19": (0.75, "Captures gold audit right (Dova may audit Valeant records) plus once/yr detail."),
 "doc8_qa20": (0.75, "Captures gold carve-out: liability limit does not apply to indemnification/confidentiality breaches (uncapped)."),
 "doc8_qa21": (0.25, "Generic limitation-of-liability; misses gold sole-remedy cap (fee adjustment + termination right)."),
 "doc8_qa22": (0.0, "Pred cites Section 16.4 lump-sum/60-month LD from another contract; gold = Tail-Period payment on 12.3.1 termination."),
 "doc8_qa23": (0.0, "Gold mutual insurance-maintenance clause exists; pred abstains."),
 "doc8_qa24": (0.5, "Captures the no-contest-IP covenant concept; not the specific gold span (Valeant not to impair Dova trademark rights)."),
 "doc9_qa0": (1.0, "Matches gold 'Amended and Restated Strategic Licensing, Distribution and Marketing Agreement'."),
 "doc9_qa1": (0.75, "Names actual parties Pacira + EKR (gold 'f/k/a SkyePharma' = Pacira)."),
 "doc9_qa2": (1.0, "Matches gold agreement date 15 Oct 2009."),
 "doc9_qa3": (0.0, "Gold effective 10 Aug 2007; pred says 15 Oct 2009 -- wrong."),
 "doc9_qa4": (0.0, "Gold 15yr-from-launch term; pred says expires 15 Oct 2012 -- wrong."),
 "doc9_qa5": (1.0, "Matches gold renewal: consecutive 2-year periods."),
 "doc9_qa6": (0.75, "Captures gold 180-day termination notice; minor end-of-term vs beginning-of-renewal wording."),
 "doc9_qa7": (1.0, "Matches gold governing law = New York."),
 "doc9_qa8": (0.0, "Pred pulls a Pizza-Fusion franchise non-compete from another contract; gold = PPI Competing-Product restriction."),
 "doc9_qa9": (0.0, "Gold exclusivity (EKR exclusive distributor) exists; pred abstains."),
 "doc9_qa10": (0.0, "Gold termination/repurchase right (after Jul 2015, 60-day notice) exists; pred abstains."),
 "doc9_qa11": (0.25, "Generic change-of-control; misses gold 'ceases to carry on business' trigger."),
 "doc9_qa12": (0.25, "Says 'no anti-assignment found' but gestures at assignment/consent; gold = consent-required-with-Affiliate-exception."),
 "doc9_qa13": (0.0, "Gold per-vial royalty + price-increase share exists; pred abstains."),
 "doc9_qa14": (0.0, "Pred cites Commerce One/Corio Developments assignment from another contract; gold = EKR transfers NDA to PPI."),
 "doc9_qa15": (0.0, "Gold joint-IP ownership (Joint Improvements owned jointly) exists; pred abstains."),
 "doc9_qa16": (0.75, "Captures gold PPI->EKR exclusive distribution license."),
 "doc9_qa17": (0.0, "Pred cites NICE proprietary-info clause from another contract; gold = EKR sub-distributor appointment."),
 "doc9_qa18": (0.75, "Correctly affirms an irrevocable license exists (gold: EKR Improvements licensed irrevocably)."),
 "doc9_qa19": (0.25, "Generic post-termination survival list; misses gold Step-in-Right reimbursement (30-day)."),
 "doc9_qa20": (0.0, "Pred cites Retail-Impressions/CNET-Sales audit from another contract; gold = re-inspection limitation."),
 "doc9_qa21": (0.25, "Right category (uncapped carve-out) but pred's indemnification/confidentiality carve-out != gold third-party-judgment/7.2.12 carve-out."),
 "doc9_qa22": (0.25, "Generic limitation-of-liability; does not extract gold carve-out specifics."),
 "doc9_qa23": (0.5, "Affirms insurance required (general liability overlaps gold) but lists workers'-comp; misses product-liability/business-interruption + $ limits."),
 "doc10_qa0": (1.0, "Matches gold doc name 'Remarketing Agreement'."),
 "doc10_qa1": (1.0, "Names gold party 'Deutsche Bank Trust Company Americas' plus others."),
 "doc10_qa2": (1.0, "Matches gold agreement date 26 Aug 2014."),
 "doc10_qa3": (0.0, "Gold termination tied to Remarketing Settlement Date conditions; pred asserts fixed 8 Oct 2014 -- wrong."),
 "doc10_qa4": (1.0, "Matches gold governing law = New York."),
 "doc10_qa5": (0.0, "Pred cites 503(b)(9)/Stub-Rent caps from a bankruptcy contract; gold = Remarketing-Agent contribution cap."),
 "doc10_qa6": (0.0, "Pred pulls product-liability insurance language from another contract; gold = Insurance Subsidiary licensing."),
 "doc11_qa0": (1.0, "Matches gold 'STRATEGIC ALLIANCE AGREEMENT'."),
 "doc11_qa1": (1.0, "Names gold party 'FTE Networks, Inc.' plus EDGE."),
 "doc11_qa2": (1.0, "Captures gold agreement date 17 Feb 2016."),
 "doc11_qa3": (1.0, "Matches gold effective date 17 Feb 2016."),
 "doc11_qa4": (1.0, "Matches gold expiration 16 Feb 2019."),
 "doc11_qa5": (1.0, "Matches gold renewal: month-to-month until 30-day notice."),
 "doc11_qa6": (0.0, "Gold 30-day renewal-termination notice; pred says 180 days -- wrong."),
 "doc11_qa7": (0.0, "Gold governing law = Texas; pred says New York -- wrong."),
 "doc11_qa8": (0.0, "Gold no-solicit-of-employees (2x-salary LD) exists; pred abstains."),
 "doc11_qa9": (0.75, "Captures gold termination-for-convenience (either party, 30-day notice)."),
 "doc11_qa10": (0.5, "Correct direction (assignment needs EDGE consent) but cites a possibly-wrong 'Section 6.2 IP Agreement'."),
 "doc11_qa11": (0.5, "Captures PO-obligation survival post-termination; misses gold 'remaining Work completed under terms then in effect'."),
 "doc11_qa12": (0.0, "Gold audit/inspection right (EDGE inspect Work) exists; pred abstains."),
 "doc11_qa13": (0.25, "Affirms liquidated damages exist but cites wrong Section 16.4/16.5; gold = 2x-salary employee LD."),
 "doc11_qa14": (0.0, "Pred fabricates '24 months'; gold warranty period = 1 year."),
 "doc11_qa15": (0.5, "Captures commercial general liability insurance requirement; misses gold $1M/$2M limits."),
 "doc12_qa0": (1.0, "Matches gold 'SPONSORSHIP AGREEMENT'."),
 "doc12_qa1": (0.0, "Pred quotes EDGE/FTE parties from another contract (doc11); gold party = 'Trust'."),
 "doc12_qa2": (0.0, "Gold date 4 Feb 2005 exists; pred abstains."),
 "doc12_qa3": (0.0, "Gold effective-date clause exists; pred abstains."),
 "doc12_qa4": (0.0, "Pred asserts 16 Feb 2019 from another contract; gold = effective-on-execution clause."),
 "doc12_qa5": (0.0, "Gold governing law = Massachusetts; pred says New York -- wrong."),
 "doc12_qa6": (0.5, "Captures termination-for-convenience (either party, without cause); misses gold 60-day notice."),
 "doc12_qa7": (0.0, "Gold 0.50%-of-net-assets fee exists; pred abstains."),
 "doc12_qa8": (0.0, "Gold 'Limitation of Liability of the Sponsor' exists; pred abstains."),
 "doc13_qa0": (0.0, "Gold 'SAMPLE OF NON-DISCLOSURE AND NON-COMPETITION AGREEMENT'; pred says 'Franchise Agreement' -- wrong."),
 "doc13_qa1": (0.25, "Names Franchisee/Franchisor (related) but not gold party 'Member'."),
 "doc13_qa2": (0.5, "Gold date is a blank template; pred reasonably notes no concrete date provided."),
 "doc13_qa3": (0.75, "Captures gold Member non-compete (Competitive Business, geographic radius) -- correct for this franchise contract."),
 "doc13_qa4": (0.0, "Gold no-solicit-of-customers clause exists; pred abstains."),
 "doc13_qa5": (0.0, "Gold no-solicit-of-employees clause exists; pred abstains."),
 "doc13_qa6": (0.0, "Gold third-party-beneficiary (Franchisor) clause exists; pred abstains."),
 "doc14_qa0": (1.0, "Matches gold 'Intellectual Property Agreement'."),
 "doc14_qa1": (0.0, "Gold party 'CERENCE INC.' exists; pred abstains."),
 "doc14_qa2": (0.0, "Gold date 30 Sept 2019 exists; pred abstains."),
 "doc14_qa3": (0.0, "Gold counterparts-effective clause exists; pred abstains with filler."),
 "doc14_qa4": (0.0, "Gold governing law = Delaware; pred says New York -- wrong."),
 "doc14_qa5": (0.0, "Gold termination-for-convenience (Nuance, prior to Distribution) exists; pred abstains."),
 "doc14_qa6": (0.0, "Pred cites ENERGOUS/DIALOG change-of-control from another contract; gold = merger/asset-transfer trigger."),
 "doc14_qa7": (1.0, "Matches gold: assignment without consent shall be void."),
 "doc14_qa8": (0.25, "On-topic IP but focuses on assignment-needs-consent; misses gold 'execute IP assignments to record transfers'."),
 "doc14_qa9": (0.0, "Gold divested-entity license-retention clause exists; pred abstains."),
 "doc14_qa10": (0.0, "Pred cites Purchaser/Seller third-party-IP terms from another contract; gold = Nuance-Group sublicense scope."),
 "doc14_qa11": (0.0, "Pred cites SINA-Leju affiliate-assignment from another contract; gold = Nuance->SpinCo perpetual license."),
 "doc14_qa12": (0.75, "Correctly affirms a perpetual + irrevocable license (gold: Nuance->SpinCo perpetual/irrevocable)."),
 "doc14_qa13": (0.25, "Generic monetary cap; gold = consequential/indirect-damages exclusion (no monetary cap)."),
 "doc14_qa14": (0.75, "Captures gold covenant-not-to-challenge (SpinCo won't contest Nuance IP)."),
 "doc15_qa0": (1.0, "Matches gold 'ENDORSEMENT'."),
 "doc15_qa1": (0.0, "Gold party 'Thrivent Financial for Lutherans' exists; pred abstains."),
 "doc15_qa2": (0.0, "Gold date 1 Jul 2019 exists; pred abstains."),
 "doc15_qa3": (0.0, "Gold effective 1 Jul 2019 exists; pred abstains."),
 "doc15_qa4": (0.0, "Pred pulls IP-Agreement assignment clause from another contract; gold = Society membership rights non-transferable."),
 "doc16_qa0": (0.5, "Gold 'MASTER SUPPLY AGREEMENT'; pred 'Supply Agreement' -- drops 'Master'."),
 "doc16_qa1": (0.0, "Gold party 'Seller' exists; pred abstains."),
 "doc16_qa2": (0.0, "Gold date 1 Nov 2019 exists; pred abstains."),
 "doc16_qa3": (0.0, "Gold effective 1 Nov 2019 exists; pred abstains."),
 "doc16_qa4": (0.0, "Gold condition-based term-end; pred asserts fixed 31 Dec 2019 -- wrong."),
 # ---- chunk 2: entries 196-295 (docs 16-26) ----
 "doc16_qa5": (0.0, "Gold governing law = Illinois; pred says New York -- wrong."),
 "doc16_qa6": (0.25, "Generic change-of-control; misses gold Reynolds-Group common-parent carve-out."),
 "doc16_qa7": (0.5, "Captures consent-required anti-assignment (void on transfer); not the exact gold CoC carve-out."),
 "doc16_qa8": (0.5, "Captures 2 of 4 gold uncapped carve-outs (confidentiality + payments); misses indemnification/IP."),
 "doc16_qa9": (0.0, "Pred quotes EKR/PPI liability cap from another contract; gold = direct-damages-only."),
 "doc16_qa10": (0.0, "Pred pulls product-liability insurance from another contract; gold = $10M employers' liability."),
 "doc17_qa0": (1.0, "Matches gold 'DISTRIBUTION AND SERVICES AGREEMENT'."),
 "doc17_qa1": (1.0, "Names gold party 'Integrity Short Term Government Fund' plus distributor."),
 "doc17_qa2": (0.0, "Gold date 18 Jan 2020 exists; pred abstains."),
 "doc17_qa3": (0.0, "Pred asserts 16 Feb 2019 from another contract; gold term to 18 Jan 2022."),
 "doc17_qa4": (0.0, "Pred gives 5yr/1yr renewal from another contract; gold = annual renewal with Board approval."),
 "doc17_qa5": (0.0, "Gold governing law = Kansas; pred says Delaware -- wrong."),
 "doc17_qa6": (0.0, "Gold auto-termination-on-assignment clause exists; pred abstains."),
 "doc17_qa7": (0.0, "Gold revenue clause (excess of sales price over NAV) exists; pred abstains."),
 "doc17_qa8": (0.0, "Pred cites Retail-Impressions/CNET audit from another contract; gold = Fund furnishes audits/statements."),
 "doc18_qa0": (1.0, "Matches gold 'Intellectual Property Agreement'."),
 "doc18_qa1": (1.0, "Names gold party 'Marv Enterprises, LLC' plus others."),
 "doc18_qa2": (1.0, "Matches gold agreement date 12 May 2020."),
 "doc18_qa3": (1.0, "Matches gold effective date 12 May 2020."),
 "doc18_qa4": (0.0, "Gold governing law = Pennsylvania; pred says Delaware -- wrong."),
 "doc18_qa5": (0.5, "Captures the exclusive license/exclusivity; misses gold revert-on-payment-default specific."),
 "doc18_qa6": (0.0, "Gold 5%+5%-to-shareholders-until-$40M revenue share exists; pred abstains."),
 "doc18_qa7": (0.5, "Captures a license grant incl. Appendix A; party direction (Marv->Premier) differs from gold (THI rights)."),
 "doc18_qa8": (0.0, "Pred cites Licensed-Domain-Names affiliate license from another contract; gold = retroactive sublicense to Related Company."),
 "doc19_qa0": (1.0, "Matches gold 'Strategic Alliance Agreement'."),
 "doc19_qa1": (1.0, "Names gold party 'Sibannac, Inc.' plus Bravatek."),
 "doc19_qa2": (1.0, "Matches gold agreement date 30 Nov 2017."),
 "doc19_qa3": (0.0, "Gold 12-month term; pred says expires 30 Nov 2027 -- wrong."),
 "doc19_qa4": (0.0, "Gold auto-renewal (one 12-month period) exists; pred says no renewal term -- wrong."),
 "doc19_qa5": (0.0, "Gold 90-day renewal-termination notice; pred says 180 days -- wrong."),
 "doc19_qa6": (0.0, "Gold governing law = Texas; pred says Colorado -- wrong."),
 "doc19_qa7": (0.0, "Gold termination-for-convenience (90-day notice) exists; pred abstains."),
 "doc19_qa8": (0.75, "Conveys the gold answer (assignment requires prior written consent) despite a hedged preamble."),
 "doc19_qa9": (0.0, "Gold lead-finder-fee (10-20% revenue) exists; pred abstains."),
 "doc19_qa10": (0.0, "Pred cites Schoolpop $52M minimum from another contract; gold = lead-finder-fee clause."),
 "doc20_qa0": (1.0, "Matches gold 'Strategic Alliance Agreement'."),
 "doc20_qa1": (0.25, "Generic ('identify parties'); does not name gold party 'Dynamic Hearing Pty Ltd'."),
 "doc20_qa2": (0.0, "Gold date 1 Oct 2008 exists; pred abstains."),
 "doc20_qa3": (0.0, "Gold effective 1 Oct 2008 exists; pred abstains."),
 "doc20_qa4": (0.0, "Pred asserts last-Purchase-Schedule term from another contract; gold = 5-year initial term."),
 "doc20_qa5": (0.0, "Gold governing law = Victoria, Australia; pred says Delaware -- wrong."),
 "doc20_qa6": (0.75, "Captures gold exclusivity (IntriCon license exclusive for Hearing Aids while payments continue)."),
 "doc20_qa7": (0.5, "Captures an exclusivity exception (3.14 manufacturer carve-out); gold = pre-Jan-2009-agreements exception."),
 "doc20_qa8": (0.25, "Describes termination-for-cause (30-day cure); gold = Dynamic Hearing 3-month convenience termination."),
 "doc20_qa9": (0.25, "Gestures at assignment/consent but extracts nothing; gold = IntriCon needs DH consent."),
 "doc20_qa10": (0.0, "Gold 2%-royalty-per-DSP-feature exists; pred abstains."),
 "doc20_qa11": (0.5, "Captures minimum-payment obligation; misses gold $300k Access Fee specifics."),
 "doc20_qa12": (0.75, "Captures gold license grant (Dynamic Hearing -> IntriCon, Technology/Software)."),
 "doc20_qa13": (0.25, "Generic post-termination survival; gold span = audit notice/expense/5%/annual-limit provisions."),
 "doc20_qa14": (0.5, "Affirms audit rights over payment calculations; misses gold >5%-underpayment reimbursement specific."),
 "doc20_qa15": (0.5, "Captures the consequential/indirect-damages exclusion (gold) but leads with a wrong-contract EKR/PPI cap."),
 "doc21_qa0": (1.0, "Matches gold 'AGENCY AGREEMENT'."),
 "doc21_qa1": (0.0, "Pred quotes ADAMS GOLF signature clause from another contract; gold party = 'Notes Trustee'."),
 "doc21_qa2": (0.0, "Gold date 18 Apr 2018 exists; pred abstains."),
 "doc21_qa3": (1.0, "Matches gold governing law = Delaware."),
 "doc21_qa4": (0.0, "Pred cites Dynamic-Hearing exclusivity from another contract; gold = Asset Designation Rights."),
 "doc21_qa5": (0.25, "Generic termination-by-notice; gold = Agent option to end E-Commerce Platform after four weeks."),
 "doc21_qa6": (0.5, "Captures consent-required anti-assignment + an exception; gold exception = GA/Tiger collateral assignment to lenders."),
 "doc21_qa7": (0.0, "Gold limited IP license for GOB Sale exists; pred abstains."),
 "doc21_qa8": (0.25, "Generic post-termination survival; gold = Remaining Merchandise transferred to Agent free and clear."),
 "doc21_qa9": (0.0, "Pred cites Retail-Impressions/CNET audit from another contract; gold = Merchant makes books available to Purchaser."),
 "doc21_qa10": (0.25, "Affirms liquidated damages exist but generic; gold = Merchant retains Deposit on Purchaser breach."),
 "doc21_qa11": (0.5, "Captures insurance-maintenance requirement generically; gold = Merchant maintains specified liability policies."),
 "doc22_qa0": (1.0, "Matches gold 'SUPPORT AND MAINTENANCE AGREEMENT'."),
 "doc22_qa1": (0.0, "Pred quotes ADAMS GOLF signature clause from another contract; gold party = 'On2'."),
 "doc22_qa2": (1.0, "Captures gold agreement date 'April __, 2005' (blank template)."),
 "doc22_qa3": (1.0, "Captures gold effective date 'April __, 2005'."),
 "doc22_qa4": (0.0, "Pred asserts last-Purchase-Schedule term from another contract; gold = 18-month term."),
 "doc22_qa5": (0.0, "Gold governing law = New York; pred says Delaware -- wrong."),
 "doc22_qa6": (0.5, "Captures the anti-assignment structure (consent, void, exceptions); quotes another contract's 'IP Agreement' wording."),
 "doc22_qa7": (0.0, "Pred cites Dova Speaker-Program threshold from another contract; gold = Wildform 20hr/125-email cap."),
 "doc22_qa8": (0.0, "Pred cites Commerce One/Corio assignment from another contract; gold = Incorporated Tech Works sole property of On2."),
 "doc23_qa0": (0.5, "Gold 'Website Design, Development and Hosting Agreement'; pred 'Hosting Agreement' -- partial."),
 "doc23_qa1": (0.25, "Generic ('identify parties'); does not name gold party 'FreeCook'."),
 "doc23_qa2": (0.0, "Gold date 11 Jan 2018 exists; pred abstains."),
 "doc23_qa3": (0.0, "Gold 12-week term (Feb-May 2018); pred says 10yr after effective -- wrong."),
 "doc23_qa4": (0.0, "Gold termination-for-convenience (cease Customer Service at discretion) exists; pred abstains."),
 "doc23_qa5": (0.0, "Gold license (Company may display Client website as examples) exists; pred abstains."),
 "doc24_qa0": (1.0, "Matches gold 'Service Agreement'."),
 "doc24_qa1": (1.0, "Quotes full parties clause incl. gold 'PC Financial' plus Mobimagic."),
 "doc24_qa2": (1.0, "Matches gold agreement date 1 Apr 2019."),
 "doc24_qa3": (1.0, "Matches gold effective date 1 Apr 2019."),
 "doc24_qa4": (0.0, "Gold = Service-Period term; pred asserts fixed 30 Mar 2020 -- wrong."),
 "doc24_qa5": (0.0, "Pred gives 5yr/1yr renewal from another contract; gold span is a data-protection clause."),
 "doc24_qa6": (0.0, "Gold governing law = India; pred says New York -- wrong."),
 "doc24_qa7": (0.75, "Captures gold anti-assignment (no transfer without prior written consent, void)."),
 "doc24_qa8": (0.0, "Gold RBI inspection/audit right exists; pred abstains."),
 "doc24_qa9": (0.25, "Generic uncapped carve-out (confidentiality/indemnification); gold = Mobimagic data-liability disclaimer."),
 "doc24_qa10": (0.0, "Gold consequential-damages exclusion exists; pred says no cap found -- abstains."),
 "doc25_qa0": (1.0, "Matches gold 'JOINT VENTURE AGREEMENT'."),
 "doc25_qa1": (0.0, "Pred quotes Valeant/Dova relationship from another contract; gold party = 'JVLS, LLC'."),
 "doc25_qa2": (1.0, "Matches gold agreement date 20 March 2020."),
 "doc25_qa3": (0.0, "Pred cites 12 May 2020 from another contract; gold term begins 1 Mar 2020."),
 "doc25_qa4": (0.0, "Pred asserts last-Purchase-Schedule term from another contract; gold to 28 Feb 2025."),
 "doc25_qa5": (1.0, "Matches gold governing law = Florida."),
 "doc25_qa6": (0.25, "Loosely matches consent-for-assignment concept but quotes another contract's IP-Agreement clause; gold = all-Members consent."),
 "doc25_qa7": (0.0, "Pred cites Dova/Valeant audit from another contract; gold = GAAP books open to any Member."),
 "doc25_qa8": (0.75, "Captures gold (Venture may acquire insurance for Members/agents acting in good faith) despite hedged preamble."),
 "doc26_qa0": (1.0, "Matches gold 'INTELLECTUAL PROPERTY AGREEMENT'."),
 "doc26_qa1": (0.0, "Pred discusses alliance-managers/language clauses; does not name gold party 'Zebra Technologies Corporation'."),
 # ---- chunk 3: entries 296-395 (docs 26-32) ----
 "doc26_qa2": (1.0, "Matches gold agreement date 14 Apr 2014."),
 "doc26_qa3": (1.0, "Matches gold effective date 14 Apr 2014."),
 "doc26_qa4": (0.0, "Gold term = until IP in public domain; pred asserts fixed 10yr -- wrong."),
 "doc26_qa5": (1.0, "Matches gold governing law = Delaware."),
 "doc26_qa6": (0.0, "Pred cites Dynamic-Hearing exclusivity from another contract; gold = Assigned-IP transfer clause."),
 "doc26_qa7": (0.25, "Generic change-of-control termination; gold = license rights don't extend to the Buyer post-CoC."),
 "doc26_qa8": (0.25, "Generic consent-for-assignment; gold = condition assignment on assignee acknowledging license grants."),
 "doc26_qa9": (0.0, "Pred cites Commerce One/Corio assignment from another contract; gold = arbitrator-ordered patent assignment."),
 "doc26_qa10": (0.0, "Pred cites ENERGOUS/DIALOG Deposit-Materials license; gold = make/use/sell equipment license."),
 "doc26_qa11": (0.0, "Pred cites ENERGOUS/DIALOG non-transferable Deposit-Materials license from another contract."),
 "doc26_qa12": (0.0, "Pred cites Zynga/WPT and abstains; gold = Purchaser-Licensee sublicense rights."),
 "doc26_qa13": (0.75, "Correctly affirms an irrevocable + perpetual license (gold: Seller->Purchaser Licensees)."),
 "doc26_qa14": (0.0, "Pred cites EKR/PPI cap from another contract; gold sole remedy = Acquisition Agreement Art. 8."),
 "doc27_qa0": (0.5, "Gold 'Domain Name and Content License Agreement'; pred 'Content License Agreement' -- partial."),
 "doc27_qa1": (0.0, "Gold party 'Beijing Yisheng Leju...' exists; pred abstains."),
 "doc27_qa2": (0.0, "Gold effective-date (Closing Date in SPA) clause exists; pred abstains."),
 "doc27_qa3": (0.0, "Pred asserts 16 Feb 2019 from another contract; gold = 10yr Initial Term."),
 "doc27_qa4": (0.0, "Gold governing law = PRC; pred says Delaware (and wrong-contract ref) -- wrong."),
 "doc27_qa5": (0.0, "Gold most-favored-nation (E-House royalty) clause exists; pred abstains."),
 "doc27_qa6": (0.0, "Pred cites Dynamic-Hearing exclusivity from another contract; gold = Licensee exclusive domain-name license."),
 "doc27_qa7": (0.25, "Generic change-of-control; misses gold SINA-Leju assignment carve-outs."),
 "doc27_qa8": (0.75, "Captures gold SINA-Leju assignment/sublicense carve-outs (Licensor->Affiliates, Licensee->SINA Leju)."),
 "doc27_qa9": (0.0, "Gold Licensor->Licensee domain-name license exists; pred abstains."),
 "doc27_qa10": (0.5, "Affirms the license is non-transferable; misses gold SINA-Leju sublicense specifics."),
 "doc27_qa11": (0.25, "Captures the license but says no affiliate license; gold = SINA-Leju affiliate sublicense."),
 "doc27_qa12": (0.25, "Generic post-termination survival; gold = 90-day post-termination domain-name transition use."),
 "doc27_qa13": (0.5, "Captures the no-contest-IP covenant concept; misses gold tarnish/SINA-domain specifics."),
 "doc28_qa0": (1.0, "Matches gold 'INTELLECTUAL PROPERTY AGREEMENT'."),
 "doc28_qa1": (1.0, "Identifies the parties (Hertz Corp, Hertz System, Herc Rentals) -- gold 'Parties' annotation."),
 "doc28_qa2": (1.0, "Matches gold agreement date 30 Jun 2016."),
 "doc28_qa3": (1.0, "Matches gold effective date 30 Jun 2016."),
 "doc28_qa4": (1.0, "Matches gold governing law = New York."),
 "doc28_qa5": (1.0, "Matches gold non-compete (HERC won't rent/lease cars in THC territories without consent), incl. survival."),
 "doc28_qa6": (0.5, "Captures consent-required anti-assignment (core matches); exceptions differ from gold (void-without-HSI-consent)."),
 "doc28_qa7": (0.0, "Pred cites Corio/Seller-Entity assignment from another contract; gold = THC assigns ERB Domains to HERC."),
 "doc28_qa8": (0.0, "Gold HSI->HERC trademark license exists; pred abstains."),
 "doc28_qa9": (0.25, "On-topic insurance-notice but wrong specifics (30-day + wrong types); gold = HERC 10-day notice."),
 "doc28_qa10": (0.75, "Captures gold covenant-not-to-challenge (neither party shall attack the other's title)."),
 "doc29_qa0": (1.0, "Matches gold 'Consulting Agreement'."),
 "doc29_qa1": (1.0, "Quotes full parties clause incl. gold 'Consultant' (Timothy Cabrera) + Company."),
 "doc29_qa2": (1.0, "Matches gold agreement date 2 Jan 2020."),
 "doc29_qa3": (1.0, "Matches gold effective date 2 Jan 2020."),
 "doc29_qa4": (0.75, "Captures the 1-year term (expires 2 Jan 2021); omits 'or until services completed' qualifier."),
 "doc29_qa5": (0.0, "Gold governing law = Florida; pred says Delaware -- wrong."),
 "doc29_qa6": (0.0, "Gold no-solicit-of-customers (Opportunity) clause exists; pred abstains."),
 "doc29_qa7": (0.75, "Captures gold anti-assignment (no assignment/delegation without other party's consent)."),
 "doc30_qa0": (0.5, "Gold 'FORM OF FRANCHISE AGREEMENT'; pred 'Franchise Agreement' -- drops 'Form of'."),
 "doc30_qa1": (0.25, "Generic ('Franchisor/Franchisee roles'); does not name gold party 'Pizza Fusion Holding, Inc.'."),
 "doc30_qa2": (0.75, "Captures gold 10-year term; minor Agreement-Date vs Effective-Date wording."),
 "doc30_qa3": (0.0, "Pred gives annual/180-day renewal from another contract; gold = two additional 10-year terms."),
 "doc30_qa4": (0.0, "Gold governing law = Florida; pred says New York -- wrong."),
 "doc30_qa5": (0.5, "Captures a non-compete restriction during the term; 'Member' framing is generic/cross-contract."),
 "doc30_qa6": (0.0, "Gold no-solicit-of-customers clause exists; pred abstains."),
 "doc30_qa7": (0.0, "Gold no-solicit-of-employees (induce to leave) clause exists; pred abstains."),
 "doc30_qa8": (0.0, "Gold termination-for-convenience (Major Account, 30-day notice) exists; pred abstains."),
 "doc30_qa9": (0.25, "Affirms a purchase/ROFR-type right but cites fabricated Section 14.8; gold = option to buy Franchised-Business assets."),
 "doc30_qa10": (0.25, "Generic change-of-control; gold = no operation/control by another without consent."),
 "doc30_qa11": (0.75, "Captures gold anti-assignment (no Transfer without our prior written consent)."),
 "doc30_qa12": (0.0, "Gold Regional-Fund 2%-vote revenue share exists; pred abstains."),
 "doc30_qa13": (0.0, "Pred cites Schoolpop $52M minimum from another contract; gold = $12k Grand Opening ad spend."),
 "doc30_qa14": (0.0, "Pred cites Commerce One/Corio assignment from another contract; gold = test-market item becomes our property."),
 "doc30_qa15": (0.0, "Gold license (Proprietary Marks/System to operate Restaurant) exists; pred abstains."),
 "doc30_qa16": (0.5, "Affirms a non-transferable license; cites cross-contract Section 10.7; gold = no sublicense of Marks/System."),
 "doc30_qa17": (0.25, "Generic post-termination survival; gold = 30-day post-termination purchase option."),
 "doc30_qa18": (0.0, "Pred cites Retail-Impressions/CNET audit from another contract; gold = reinspect approved-supplier facilities."),
 "doc30_qa19": (0.0, "Gold consequential-damages waiver (actual damages only) exists; pred abstains."),
 "doc30_qa20": (0.5, "Captures the liquidated-damages-not-a-penalty concept (Sec 16.4/16.5); formula specifics uncertain."),
 "doc30_qa21": (0.5, "Affirms insurance must be maintained (gold concept); adds extra specifics not in gold."),
 "doc30_qa22": (0.25, "On-category covenant-not-to-sue but gold = general release of claims; pred = IP-no-contest."),
 "doc31_qa0": (1.0, "Matches gold 'License and Hosting Agreement'."),
 "doc31_qa1": (0.0, "Pred cites Seller/Purchaser from another contract; gold party = 'CORIO'."),
 "doc31_qa2": (0.0, "Gold date 29 Oct 1999 exists; pred abstains."),
 "doc31_qa3": (0.25, "Vague 'effective after signed'; misses gold date 29 Oct 1999."),
 "doc31_qa4": (0.0, "Gold 5-year initial term; pred says 10 years -- wrong."),
 "doc31_qa5": (0.0, "Pred gives 2-year/180-day renewal from another contract; gold = 1-year/30-day."),
 "doc31_qa6": (0.0, "Gold 30-day renewal-termination notice; pred says 180 days -- wrong."),
 "doc31_qa7": (0.0, "Gold governing law = California; pred says Delaware -- wrong."),
 "doc31_qa8": (0.5, "Captures the merger/acquisition assignment + competitor-consent exception (gold); muddied with ENERGOUS/DIALOG names."),
 "doc31_qa9": (0.5, "Core matches (no assignment without consent) but adds cross-contract affiliate exceptions that contradict gold."),
 "doc31_qa10": (0.0, "Gold MarketSite.net revenue-share clause exists; pred abstains."),
 "doc31_qa11": (0.75, "Captures gold IP ownership (Developments owned by Corio)."),
 "doc31_qa12": (0.0, "Gold joint-IP-ownership negotiation clause exists; pred abstains."),
 "doc31_qa13": (0.5, "Captures a Commerce One->Corio license grant; gold span is the Source-Code license specifically."),
 "doc31_qa14": (0.25, "Affirms a non-transferable license (correct for this contract) but cites ENERGOUS/DIALOG Deposit Materials."),
 "doc31_qa15": (0.25, "Pred denies an all-you-can-eat license; gold flags the perpetual/irrevocable license as the relevant span (ambiguous category)."),
 "doc31_qa16": (0.75, "Correctly affirms a perpetual + irrevocable license (gold: Commerce One->Corio)."),
 "doc31_qa17": (0.75, "Captures gold source-code-escrow arrangement (deposit + release conditions)."),
 "doc31_qa18": (0.25, "Generic post-termination survival; gold = continued support/maintenance obligation post-termination."),
 "doc31_qa19": (0.75, "Captures gold audit right + reimbursement when underpayment exceeds threshold (5%)."),
 "doc31_qa20": (0.25, "On-topic but mixes doc8 DOVA/VALEANT; misses gold 12-month-payment liability cap + Section-8 carve-out."),
 "doc31_qa21": (0.25, "Generic limitation-of-liability; misses gold sole-remedy-for-warranty-breach."),
 "doc31_qa22": (0.0, "Pred fabricates '24 months'; gold = replace defective media during Warranty Period."),
 "doc31_qa23": (0.25, "On-category covenant-not-to-sue but cites VerticalNet/Impresse from another contract; gold = patent-infringement no-sue."),
 "doc32_qa0": (0.75, "Captures 'Cooperation Agreement'; omits gold '(2014 Amendment)'."),
 "doc32_qa1": (0.0, "Gold party 'Nanjing Tuniu Technology...' exists; pred abstains."),
 "doc32_qa2": (0.0, "Gold date 24 Jan 2014; pred merely echoes the label 'Agreement Date' with no date."),
 "doc32_qa3": (0.75, "Captures gold effective-on-execution-by-both-Parties."),
 "doc32_qa4": (0.0, "Pred asserts fixed 10yr from another contract; gold tied to Party B operation term."),
 "doc32_qa5": (0.0, "Gold governing law = PRC; pred says Delaware -- wrong."),
 "doc32_qa6": (0.0, "Gold non-compete (Party A) clause exists; pred abstains."),
 # ---- chunk 4: entries 396-495 (docs 32-38) ----
 "doc32_qa7": (0.0, "Pred cites Dynamic-Hearing exclusivity from another contract; gold = Party B exclusive-partner undertaking."),
 "doc32_qa8": (0.0, "Pred cites ENERGOUS 180-day termination from another contract; gold = Party B may terminate, Party A may not."),
 "doc32_qa9": (0.25, "Concept overlap (assignment with affiliate carve-out) but pred quotes SINA-Leju from another contract; gold = Party B affiliate transfer."),
 "doc32_qa10": (0.0, "Pred cites Commerce One/Corio assignment from another contract; gold = IP owned by Party B."),
 "doc32_qa11": (0.5, "Captures the indirect-damages exclusion (gold) despite a wrong-contract EKR/PPI lead-in."),
 "doc32_qa12": (0.25, "Affirms liquidated damages exist but cites wrong Section 16.4/16.5; gold = 0.03%/day on overdue Service Fee."),
 "doc33_qa0": (0.0, "Pred gives a confidential-treatment boilerplate, not the gold doc name 'Promotion Agreement'."),
 "doc33_qa1": (0.0, "Pred cites Seller/Purchaser from another contract; gold party = 'Cyberian Outpost, Inc.'."),
 "doc33_qa2": (0.0, "Gold date 26 Jan 1998; pred says 1 Feb 1998 (Term start) -- wrong."),
 "doc33_qa3": (0.0, "Gold effective/Term-begin 1 Feb 1998 exists; pred abstains."),
 "doc33_qa4": (0.75, "Captures gold expiration = first anniversary (1 Feb 1999)."),
 "doc33_qa5": (0.0, "Gold governing law = California; pred says Delaware -- wrong."),
 "doc33_qa6": (0.0, "Gold non-compete (CNET two-agreement limit) exists; pred abstains."),
 "doc33_qa7": (0.0, "Pred cites Dynamic-Hearing exception from another contract; gold = CNET competitive-restriction carve-out."),
 "doc33_qa8": (0.5, "Captures termination-for-convenience (either party, by notice); misses gold 3-month/30-day specifics."),
 "doc33_qa9": (0.5, "Captures restricted assignment (consent); gold exceptions (business transfer/common control) differ."),
 "doc33_qa10": (0.25, "Affirms revenue-sharing exists but cites Impresse/VerticalNet from another contract; gold = monthly cash + % of CNET Sales."),
 "doc33_qa11": (0.0, "Gold minimum monthly payment exists; pred abstains."),
 "doc33_qa12": (0.0, "Gold license (Company trademarks to CNET) exists; pred abstains."),
 "doc33_qa13": (1.0, "Matches gold audit right (engage third party to audit Retail Impressions/CNET Sales) -- correct contract."),
 "doc33_qa14": (0.0, "Gold CNET indemnification clause exists; pred abstains."),
 "doc34_qa0": (1.0, "Matches gold 'Collaboration Agreement'."),
 "doc34_qa1": (1.0, "Names the parties (Didi, Hunan Ruixi) and the gold Party/Parties definition."),
 "doc34_qa2": (0.0, "Gold date 17 Dec 2018 exists; pred abstains."),
 "doc34_qa3": (0.5, "Highlights the effective-on-execution clause; does not give the gold date 17 Dec 2018."),
 "doc34_qa4": (0.25, "Captures ~1-year horizon but asserts wrong date 31 Dec 2019; gold = one year from effective date."),
 "doc34_qa5": (0.0, "Gold governing law = China; pred says Delaware -- wrong."),
 "doc34_qa6": (0.0, "Gold most-favored (most-favorable leasing scheme) clause exists; pred abstains."),
 "doc34_qa7": (0.0, "Gold non-compete (cooperate with Didi competitors) clause exists; pred abstains."),
 "doc34_qa8": (0.0, "Gold termination-for-convenience (Party A, 3 months) exists; pred abstains."),
 "doc34_qa9": (0.75, "Captures gold anti-assignment (no assignment without other party's consent)."),
 "doc34_qa10": (0.25, "Generic post-termination survival; gold = Party B performs Financial Leasing Agreement until lease expires."),
 "doc34_qa11": (0.0, "Gold indirect-damages exclusion exists; pred says no cap found -- abstains."),
 "doc34_qa12": (0.25, "Affirms liquidated damages but cites NICE from another contract; gold = additional deposit equal to LD."),
 "doc35_qa0": (1.0, "Matches gold 'Walabot-HOME Reseller Agreement'."),
 "doc35_qa1": (1.0, "Quotes parties clause incl. Vayyar (Supplier) + Inde Living (Reseller) and the Parties definition."),
 "doc35_qa2": (1.0, "Matches gold agreement date 31 Jul 2019."),
 "doc35_qa3": (1.0, "Matches gold effective date 31 Jul 2019."),
 "doc35_qa4": (0.0, "Gold 1-year initial term; pred says 10 years -- wrong."),
 "doc35_qa5": (0.5, "Captures annual auto-renewal (gold) but adds a wrong 180-day non-renewal notice."),
 "doc35_qa6": (0.0, "Gold 3-month termination notice; pred says 180 days -- wrong."),
 "doc35_qa7": (0.0, "Gold governing law = New York; pred says Delaware -- wrong."),
 "doc35_qa8": (1.0, "Matches gold termination-for-convenience (either party, 3-month notice)."),
 "doc35_qa9": (0.25, "Concept overlap (assignment void/consent) but pred quotes SINA-Leju from another contract; gold = purported assignment void."),
 "doc35_qa10": (0.75, "Captures gold MOQ minimum-order-quantity definition."),
 "doc35_qa11": (0.5, "Acknowledges the reseller-rights grant (= gold) but hedges it is 'not a license'."),
 "doc35_qa12": (1.0, "Matches gold non-transferable reseller license verbatim."),
 "doc35_qa13": (0.0, "Pred cites Vyera/CytoDyn transition from another contract; gold = sell remaining inventory at termination."),
 "doc35_qa14": (0.25, "Says no cap; gold = Supplier aggregate-liability cap (lesser of two amounts)."),
 "doc36_qa0": (0.25, "Gold 'Distribution Agreement'; pred 'Reseller Agreement' -- related but mismatched name."),
 "doc36_qa1": (0.0, "Gold party 'Schoolpop' exists; pred abstains."),
 "doc36_qa2": (1.0, "Matches gold effective date 1 Aug 2004."),
 "doc36_qa3": (0.0, "Gold terminates 31 Jul 2009; pred says one year from effective -- wrong."),
 "doc36_qa4": (0.0, "Gold governing law = Missouri; pred says Delaware -- wrong."),
 "doc36_qa5": (0.0, "Gold exclusivity (Schoolpop exclusive resale in NPO Marketplace) exists; pred abstains."),
 "doc36_qa6": (0.0, "Gold competitive-restriction exception (no exclusivity outside NPO) exists; pred abstains."),
 "doc36_qa7": (0.75, "Captures gold anti-assignment (Schoolpop needs AEIS consent)."),
 "doc36_qa8": (0.5, "Captures a real minimum commitment of this contract ($52M Cards) but not the gold 70%-coverage span; adds wrong $250k."),
 "doc36_qa9": (0.0, "Gold volume restriction (AEIS ceases fulfilling on excess) exists; pred abstains."),
 "doc36_qa10": (0.25, "Generic survival incl. 'unsold units'; misses gold 3-month post-termination Card-sale right."),
 "doc36_qa11": (0.0, "Pred cites Retail-Impressions/CNET audit from another contract; gold = AEIS inspects safekeeping facilities."),
 "doc36_qa12": (0.25, "Says no cap; gold = $50k / 12-month-payment cumulative-liability cap."),
 "doc36_qa13": (0.25, "On-category insurance but wrong specifics (product-liability template); gold = Schoolpop workers'-comp/employer's-liability."),
 "doc37_qa0": (1.0, "Matches gold 'Licensing and Web Site Hosting Agreement'."),
 "doc37_qa1": (0.0, "Pred cites Centrack/i-on from another contract; gold party = 'TrueLink, Inc.'."),
 "doc37_qa2": (0.0, "Gold date 26 Feb 1999 exists; pred abstains."),
 "doc37_qa3": (0.0, "Pred cites 29 Oct 1999 from another contract; gold effective 26 Feb 1999."),
 "doc37_qa4": (0.0, "Gold 1-year term; pred says 10 years -- wrong."),
 "doc37_qa5": (0.75, "Captures gold renewal (successive 1-year periods, 30-day non-renewal notice); spurious 5-year-initial mention."),
 "doc37_qa6": (0.0, "Gold 30-day renewal-termination notice; pred says 180 days -- wrong."),
 "doc37_qa7": (0.0, "Gold governing law = California; pred says Delaware -- wrong."),
 "doc37_qa8": (0.5, "Captures consent-required anti-assignment; misses gold affiliate exception."),
 "doc37_qa9": (0.0, "Pred cites Schoolpop $52M from another contract; gold = per-month Hosting/Support fee minimum."),
 "doc37_qa10": (0.0, "Gold TrueLink->Client Interface license exists; pred abstains."),
 "doc37_qa11": (0.25, "Says no cap; gold = TrueLink liability capped at 12-month compensation."),
 "doc38_qa0": (1.0, "Matches gold 'STRATEGIC ALLIANCE AGREEMENT'."),
 "doc38_qa1": (0.25, "Generic ('identify parties'); does not name gold party 'Dialog Semiconductor (UK) Ltd.'."),
 "doc38_qa2": (0.0, "Gold date 6 Nov 2016 exists; pred abstains."),
 "doc38_qa3": (0.0, "Pred cites 1 Oct 2008 from another contract; gold effective 6 Nov 2016."),
 "doc38_qa4": (0.0, "Gold 7-year initial term; pred asserts fixed 16 Mar 2027 -- wrong."),
 "doc38_qa5": (0.0, "Pred says indefinite 'Extended Term' from another contract; gold = annual renewal periods."),
 "doc38_qa6": (1.0, "Matches gold renewal-termination notice (180 days) -- correct contract."),
 "doc38_qa7": (0.0, "Gold governing law = California; pred says Delaware -- wrong."),
 "doc38_qa8": (0.0, "Gold non-compete (DIALOG won't develop competing UPT products) exists; pred abstains."),
 "doc38_qa9": (0.0, "Gold exclusivity (cease on Product discontinuance) exists; pred abstains."),
 "doc38_qa10": (0.0, "Gold no-solicit-of-customers (ENERGOUS won't supply customers) exists; pred abstains."),
 "doc38_qa11": (0.0, "Pred cites Dynamic-Hearing carve-outs from another contract; gold = ENERGOUS Semiconductor-Supplier exception."),
 "doc38_qa12": (0.0, "Gold no-solicit-of-employees clause exists; pred abstains."),
 "doc38_qa13": (1.0, "Matches gold termination-for-convenience (ENERGOUS, after 3rd anniversary, 180-day notice)."),
 "doc38_qa14": (0.25, "Affirms a ROFR-type right but cites fabricated Section 14.8; gold = DIALOG New-Product add-on right."),
 "doc38_qa15": (1.0, "Matches gold change-of-control (ENERGOUS terminate if DIALOG CoC involving/acquiring a competitor; DIALOG notice)."),
 "doc38_qa16": (0.5, "Captures consent-required anti-assignment; misses gold CoC-successor exception."),
 "doc38_qa17": (0.0, "Gold royalty/service-fee revenue clause exists; pred abstains."),
 "doc38_qa18": (0.0, "Gold minimum (design-win pipeline/Net Sales termination trigger) exists; pred abstains."),
 "doc38_qa19": (0.0, "Pred cites Commerce One/Corio assignment from another contract; gold = Tooling transfers to ENERGOUS."),
 "doc38_qa20": (0.0, "Gold license (ENERGOUS->DIALOG Deposit-Materials license) exists; pred abstains."),
 "doc38_qa21": (1.0, "Matches gold non-transferable Product-IP license to DIALOG -- correct contract."),
 "doc38_qa22": (0.25, "Generic affiliate-definition/assignment; misses gold ENERGOUS->DIALOG repackaging license."),
 "doc38_qa23": (0.25, "Concept overlap (affiliate sublicense) but cites SINA-Leju from another contract; gold = DIALOG sublicense to Affiliates."),
 "doc38_qa24": (0.75, "Correctly affirms an irrevocable license (gold: ENERGOUS->DIALOG Product-IP license)."),
 # ---- chunk 5: entries 496-595 (docs 38-45) ----
 "doc38_qa25": (0.75, "Captures gold source-code-escrow arrangement (three-party deposit + release conditions)."),
 "doc38_qa26": (0.5, "Captures Wind-Down continued-sales framing (correct contract); doesn't pin the Continuing-Obligation specific."),
 "doc38_qa27": (0.25, "Affirms audit rights but cites Retail-Impressions/CNET from another contract; gold = ENERGOUS auditor of DIALOG Records."),
 "doc38_qa28": (0.5, "Captures the confidentiality carve-out to the liability cap (gold); some section refs off."),
 "doc38_qa29": (0.0, "Gold consequential-damages exclusion exists; pred abstains."),
 "doc38_qa30": (0.25, "Notes warranty survives/Warranty Period but gives no duration; gold = [*] from shipment."),
 "doc38_qa31": (0.0, "Gold insurance-maintenance (Term + 3yr) clause exists; pred abstains."),
 "doc39_qa0": (0.5, "Gold 'Commercialization and License Agreement'; pred 'License Agreement' -- partial."),
 "doc39_qa1": (0.0, "Gold party 'Vyera' exists; pred abstains."),
 "doc39_qa2": (0.0, "Gold date 17 Dec 2019 exists; pred abstains."),
 "doc39_qa3": (0.0, "Gold effective 17 Dec 2019 exists; pred abstains."),
 "doc39_qa4": (0.0, "Gold term = last day of Royalty Term; pred asserts fixed 10yr -- wrong."),
 "doc39_qa5": (0.0, "Gold governing law = New York; pred says Delaware -- wrong."),
 "doc39_qa6": (0.0, "Gold non-compete (Section 2.6 Competitive Products) exists; pred abstains."),
 "doc39_qa7": (0.0, "Gold exclusivity (Vyera buys exclusively from CytoDyn) exists; pred abstains."),
 "doc39_qa8": (0.5, "Captures termination-for-convenience (either party by notice); misses gold 2nd-anniversary/180-day specifics."),
 "doc39_qa9": (0.0, "Pred cites ENERGOUS/DIALOG change-of-control from another contract; gold = Vyera CoC subject to Section 2.6."),
 "doc39_qa10": (0.5, "Captures consent-required anti-assignment with an exception (gold = CytoDyn may assign to capable Third Party)."),
 "doc39_qa11": (0.25, "Gestures at royalties to CytoDyn but does not extract the gold 50%-of-Net-Sales royalty."),
 "doc39_qa12": (0.0, "Pred cites Schoolpop $52M from another contract; gold = Minimum-Requirements termination trigger."),
 "doc39_qa13": (0.0, "Pred cites Commerce One/Corio assignment from another contract; gold = Vyera executes assignments for CytoDyn Inventions."),
 "doc39_qa14": (0.0, "Gold license (Vyera exclusive Commercialization right) exists; pred abstains."),
 "doc39_qa15": (0.0, "Gold non-transferable-without-consent license exists; pred says none found."),
 "doc39_qa16": (0.75, "Correctly affirms a perpetual + irrevocable license (gold: post-Royalty-Term)."),
 "doc39_qa17": (0.75, "Captures gold post-termination Transition Services Agreement + wind-down (correct contract)."),
 "doc39_qa18": (0.25, "Affirms audit rights but cites ENERGOUS/DIALOG from another contract; gold = CytoDyn audits Vyera records."),
 "doc39_qa19": (0.5, "Captures the uncapped carve-out (confidentiality/indemnification); some section refs cross-contract."),
 "doc39_qa20": (0.5, "Captures the consequential-damages exclusion (gold); hedges about a cap."),
 "doc39_qa21": (0.5, "Captures provide-evidence-of-insurance (gold) amid cross-contract noise."),
 "doc39_qa22": (0.5, "Captures the no-challenge-patent covenant concept; gold frames it as a CytoDyn termination trigger."),
 "doc40_qa0": (0.0, "Pred gives SEC-filing boilerplate, not the gold doc name 'Intellectual Property Agreement'."),
 "doc40_qa1": (0.0, "Pred gives amendment/patent-review boilerplate; gold party = '(MSCI)'."),
 "doc40_qa2": (0.0, "Gold date 20 Nov 2007 exists; pred abstains."),
 "doc40_qa3": (0.0, "Pred cites online/offline-execution clause from another contract; gold effective 20 Nov 2007."),
 "doc40_qa4": (1.0, "Matches gold governing law = New York."),
 "doc40_qa5": (0.0, "Gold MSCI->MS license exists; pred abstains."),
 "doc40_qa6": (0.75, "Correctly affirms a perpetual + irrevocable license (gold: MSCI->MS)."),
 "doc40_qa7": (0.25, "On-topic liability but cites doc35 'supplier aggregate' wording; gold = MSCI-provider liability span."),
 "doc41_qa0": (0.0, "Pred gives indemnification/insurance section refs, not the gold doc name 'Manufacturing Outsourcing Agreement'."),
 "doc41_qa1": (0.0, "Gold party 'CONTRACTOR' exists; pred abstains."),
 "doc41_qa2": (0.0, "Gold date 21 Jan 2002 exists; pred abstains."),
 "doc41_qa3": (0.25, "Generic effective-on-signing (with cross-contract '5 years'); misses gold date 21 Jan 2002."),
 "doc41_qa4": (0.0, "Gold 3-year initial term; pred asserts fixed 10yr -- wrong."),
 "doc41_qa5": (0.25, "Right category (automatic renewal) but pred says annual/180-day; gold = indefinite Extended Term."),
 "doc41_qa6": (0.5, "Notice period ~6 months matches (pred '180 days'); framing from another contract's template."),
 "doc41_qa7": (0.0, "Gold governing law = Israel; pred says New York -- wrong."),
 "doc41_qa8": (0.25, "Affirms termination-without-cause-by-notice but cites ENERGOUS/DIALOG; gold = Contractor 6-month notice."),
 "doc41_qa9": (0.5, "Captures anti-assignment + affiliate exception (gold = NICE may assign to Affiliate)."),
 "doc41_qa10": (0.0, "Pred cites Impresse/VerticalNet revenue share from another contract; gold = 10/90 dead-inventory split."),
 "doc41_qa11": (0.75, "Correctly affirms a perpetual license (gold: Contractor grants NICE perpetual license to manufacturing methods)."),
 "doc41_qa12": (0.25, "Affirms audit rights but cites ENERGOUS/DIALOG from another contract; gold = NICE audits Contractor."),
 "doc41_qa13": (0.25, "Affirms a cap but cites doc36 $50k/Schoolpop; gold = Contractor $5M aggregate cap."),
 "doc41_qa14": (0.25, "Affirms liquidated damages but generic/cross-contract; gold = LD capped at 5% of Product Price."),
 "doc41_qa15": (0.0, "Gold warranty = 13 months from shipment; pred says not stated."),
 "doc41_qa16": (0.5, "Affirms insurance-maintenance requirement (gold concept); specifics from a cross-contract template."),
 "doc42_qa0": (1.0, "Matches gold 'CO-BRANDING AGREEMENT'."),
 "doc42_qa1": (0.0, "Gold party 'VerticalNet, Inc.' exists; pred abstains."),
 "doc42_qa2": (0.0, "Gold date 3 Mar 2000 exists; pred abstains."),
 "doc42_qa3": (0.0, "Gold effective 3 Mar 2000 exists; pred abstains."),
 "doc42_qa4": (0.0, "Pred cites Royalty Term from another contract; gold = 15 months from Effective Date."),
 "doc42_qa5": (0.0, "Gold governing law = Delaware; pred says PRC -- wrong."),
 "doc42_qa6": (0.0, "Gold non-compete (no competing-printer ads on Co-Branded Site) exists; pred abstains."),
 "doc42_qa7": (0.5, "Captures consent-required anti-assignment; misses gold Affiliate/merger exception."),
 "doc42_qa8": (0.25, "Gestures at Section 4.6.2 revenue sharing but does not extract the gold (Impresse pays VerticalNet % of revenue)."),
 "doc42_qa9": (0.0, "Pred cites Schoolpop $52M from another contract; gold = Impresse buys >=$[*] Banners/Newsletters."),
 "doc42_qa10": (0.0, "Gold joint ownership of User Data exists; pred abstains."),
 "doc42_qa11": (0.0, "Gold license (Users access Co-Branded Content) exists; pred abstains."),
 "doc42_qa12": (0.25, "Affirms non-transferability but cites NICE from another contract; gold = Impresse->VerticalNet link license."),
 "doc42_qa13": (0.0, "Pred cites Vyera/CytoDyn transition from another contract; gold = VerticalNet audits Impresse records."),
 "doc42_qa14": (0.25, "Affirms audit rights but cites Retail-Impressions/CNET from another contract; gold = VerticalNet audits Impresse."),
 "doc42_qa15": (0.25, "Right category (uncapped carve-out) but cites confidentiality; gold = indemnification 9.4/9.5 carve-out."),
 "doc42_qa16": (0.0, "Pred cites CytoDyn 13.5 from another contract; gold = indemnification 9.4/9.5 carve-out."),
 "doc42_qa17": (1.0, "Matches gold covenant (Impresse not contest VerticalNet IP, except infringement) -- correct contract."),
 "doc43_qa0": (1.0, "Matches gold 'JOINT CONTENT LICENSE AGREEMENT'."),
 "doc43_qa1": (1.0, "Names gold party 'Zynga Game Ireland Limited' plus WPT/Zynga."),
 "doc43_qa2": (1.0, "Matches gold agreement date 1 Feb 2018."),
 "doc43_qa3": (1.0, "Matches gold effective date 1 Feb 2018."),
 "doc43_qa4": (0.0, "Gold 3-year initial term; pred says 10 years -- wrong."),
 "doc43_qa5": (0.0, "Pred says indefinite renewal from another contract; gold = 2-year extension if WPT paid >$12M."),
 "doc43_qa6": (0.0, "Gold governing law = California; pred says Delaware -- wrong."),
 "doc43_qa7": (0.0, "Pred denies a non-compete and discusses geography; gold = WPT won't authorize a Zynga Competitor."),
 "doc43_qa8": (0.5, "Captures consent-required anti-assignment; misses gold internal-reorganization exception."),
 "doc43_qa9": (0.0, "Gold royalty (Zynga to WPT, % of Net Revenue) exists; pred abstains."),
 "doc43_qa10": (0.0, "Gold $3M/yr Annual Minimum Guarantee exists; pred abstains."),
 "doc43_qa11": (0.75, "Captures gold license grant (Zynga -> WPT, Licensed Property)."),
 "doc43_qa12": (0.25, "Gestures at non-transferability (Zynga US/Ireland) but does not extract gold (WPT -> Zynga non-assignable license)."),
 "doc43_qa13": (0.75, "Correctly affirms a perpetual/irrevocable license (gold: end-user perpetual use)."),
 "doc43_qa14": (0.0, "Gold audit right (WPT examines Zynga records) exists; pred abstains."),
 "doc43_qa15": (0.25, "Right category (uncapped carve-out) but cites Article 13/10 from another contract; gold = Sections 2/5/8/9."),
 "doc43_qa16": (0.0, "Pred cites CytoDyn 13.5 from another contract; gold = the Section 2/5/8/9 liability carve-out."),
 "doc43_qa17": (0.0, "Gold insurance (carry liability insurance) exists; pred abstains."),
 "doc43_qa18": (0.5, "Captures the no-contest-marks/IP covenant concept; hedges 'no covenant not to sue'."),
 "doc44_qa0": (1.0, "Matches gold 'Strategic Alliance Agreement'."),
 "doc44_qa1": (0.0, "Gold party 'Freedom Mortgage' exists; pred abstains."),
 "doc44_qa2": (0.25, "Gold agreement date is near-blank (', 2013'); pred reasonably notes no explicit date."),
 "doc44_qa3": (0.0, "Gold term = later of 3yr / manager-condition; pred asserts fixed 10yr -- wrong."),
 "doc44_qa4": (0.0, "Gold governing law = New York; pred says Delaware -- wrong."),
 "doc44_qa5": (0.5, "Captures consent-required anti-assignment (core matches); adds cross-contract exceptions."),
 "doc45_qa0": (1.0, "Matches gold 'CHASE AFFILIATE AGREEMENT'."),
 "doc45_qa1": (1.0, "Names the parties (Chase + Affiliate) -- gold 'you as an Affiliate'."),
 # ---- chunk 6: entries 596-643 (docs 45-49) ----
 "doc45_qa2": (0.0, "Gold date 6 Apr 2007 exists; pred abstains."),
 "doc45_qa3": (1.0, "Matches gold effective date (commences on Chase approval of Affiliate Registration Form)."),
 "doc45_qa4": (0.0, "Gold term ends when terminated; pred asserts fixed 10yr -- wrong."),
 "doc45_qa5": (1.0, "Matches gold governing law = Delaware."),
 "doc45_qa6": (0.0, "Gold termination-for-convenience (Chase may revoke at any time) exists; pred abstains."),
 "doc45_qa7": (0.0, "Gold license (Chase -> Affiliate site/logo license) exists; pred abstains."),
 "doc45_qa8": (0.25, "Gestures at transfer/acceptance restrictions; misses gold nontransferable Chase license to Affiliate."),
 "doc45_qa9": (0.0, "Gold liability cap (aggregate = total Commissions) exists; pred abstains."),
 "doc46_qa0": (1.0, "Matches gold 'WEB HOSTING AGREEMENT'."),
 "doc46_qa1": (0.0, "Gold party 'Horst Entertainment Inc' exists; pred abstains."),
 "doc46_qa2": (0.0, "Gold date 9/9/97 exists; pred abstains."),
 "doc46_qa3": (0.0, "Gold license-purchase-on-termination ($15,000) clause exists; pred abstains."),
 "doc47_qa0": (1.0, "Matches gold 'Manufacturing, Design and Marketing Agreement'."),
 "doc47_qa1": (1.0, "Quotes parties clause incl. gold 'Subcontractor' (Zounds) + Manufacturer."),
 "doc47_qa2": (1.0, "Gives the correct date 3 Oct 2018 (gold agreement date)."),
 "doc47_qa3": (1.0, "Matches gold effective date 3 Oct 2018."),
 "doc47_qa4": (1.0, "Matches gold 10-year initial term -- correct contract."),
 "doc47_qa5": (1.0, "Matches gold renewal (successive 1-year terms, 60-day notice)."),
 "doc47_qa6": (1.0, "Matches gold renewal-termination notice (60 days)."),
 "doc47_qa7": (0.0, "Gold governing law = Arizona; pred says Delaware -- wrong."),
 "doc47_qa8": (0.0, "Gold competitive-restriction (5-year no-solicit) exists; pred abstains."),
 "doc47_qa9": (0.0, "Gold no-solicit-of-employees (5-year) clause exists; pred abstains."),
 "doc47_qa10": (0.0, "Pred cites ENERGOUS/DIALOG change-of-control from another contract; gold = CoC of Manufacturer needs Subcontractor consent."),
 "doc47_qa11": (0.25, "Concept overlap (assignment restriction) but pred quotes IP-Agreement consent clause; gold = CoC terminates agreement."),
 "doc47_qa12": (0.0, "Gold royalty (80% Product Cost / $80/unit) exists; pred abstains."),
 "doc47_qa13": (0.25, "Generic post-termination survival; gold = Subcontractor may buy remaining inventory."),
 "doc47_qa14": (0.0, "Gold audit (per Subcontractor's Auditing procedure) exists; pred abstains."),
 "doc47_qa15": (0.0, "Gold sole-remedy-for-warranty clause exists; pred abstains."),
 "doc47_qa16": (0.25, "Affirms liquidated damages but generic/cross-contract; gold = 100x salary for no-solicit breach."),
 "doc47_qa17": (0.0, "Gold warranty repair/return process exists; pred says no duration specified."),
 "doc48_qa0": (1.0, "Matches gold 'SERVICING AGREEMENT'."),
 "doc48_qa1": (0.0, "Gold party 'CURO MANAGEMENT, LLC' exists; pred abstains."),
 "doc48_qa2": (0.0, "Gold date 8 Apr 2020 exists; pred abstains."),
 "doc48_qa3": (0.0, "Gold condition-based term; pred asserts fixed 4 May 2021 -- wrong."),
 "doc48_qa4": (0.0, "Gold governing law = New York; pred says Delaware -- wrong."),
 "doc48_qa5": (0.25, "Generic post-termination transition; gold = Servicer cooperates to transfer administration to successor Servicer."),
 "doc48_qa6": (0.25, "Affirms audit/inspection rights but cites multiple other contracts; gold = Owner inspects Servicer books."),
 "doc48_qa7": (0.0, "Pred cites Impresse/VerticalNet IP-no-contest from another contract; gold = non-petition (bankruptcy) covenant."),
 "doc48_qa8": (1.0, "Matches gold third-party beneficiary (Agent may enforce)."),
 "doc49_qa0": (0.0, "Pred gives NICE/Contractor section refs; gold doc name = 'Affiliate Program ... General Terms and Conditions'."),
 "doc49_qa1": (0.0, "Pred gives termination/amendment boilerplate; gold party = 'Software Publishers'."),
 "doc49_qa2": (0.0, "Gold effective (begins on application acceptance) exists; pred abstains."),
 "doc49_qa3": (0.0, "Gold term = unlimited period; pred asserts fixed 10yr -- wrong."),
 "doc49_qa4": (0.0, "Gold governing law = Germany; pred says New York -- wrong."),
 "doc49_qa5": (0.0, "Gold termination-for-convenience (cancel any time) exists; pred says not permitted -- wrong."),
 "doc49_qa6": (0.25, "Affirms revenue sharing but cites Impresse/VerticalNet from another contract; gold = <=50% of gross sales price."),
 "doc49_qa7": (0.0, "Gold license (Software Publisher -> Affiliate advertising material) exists; pred abstains."),
 "doc49_qa8": (0.25, "Acknowledges damages limitations generally; misses gold lost-profit/data liability exclusion."),
}


def main() -> int:
    queue = [json.loads(l) for l in (CELL / "queue.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
    all_sfx = [q["qid"].split("__batch__")[1].replace("__seed42", "") for q in queue]
    missing = [s for s in all_sfx if s not in J]
    if missing:
        done = len(all_sfx) - len(missing)
        print(f"PROGRESS: {done}/{len(all_sfx)} judged; {len(missing)} remaining.")
        print("next remaining sfx:", missing[:8])
        return 0
    out = []
    for q in queue:
        sfx = q["qid"].split("__batch__")[1].replace("__seed42", "")
        score, rat = J[sfx]
        out.append({"qid": q["qid"], "judge_score": score, "rationale": rat,
                    "judge_model": "claude-opus-4.7-1m", "judge_protocol": "v1"})
    (CELL / "results.jsonl").write_text("\n".join(json.dumps(o) for o in out) + "\n", encoding="utf-8")
    mean = sum(o["judge_score"] for o in out) / len(out)
    print(f"COMPLETE: wrote {len(out)} judgments; mean judge = {mean:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
