"""Phase 1.9 - QASPER v4t-corpus-tuned Protocol B calibration + batch_calib judge.

Cells:
  qasper__v4t-corpus-tuned__calibration__seed42   (1405 entries)
  qasper__v4t-corpus-tuned__batch_calib__seed42   (1005 entries)

Judge model: claude-opus-4.7-1m  |  Protocol: v1  |  Protocol B rubric

Key findings:
  - v4t-corpus-tuned: V4t theta tuned on QASPER corpus statistics
  - Calibration: ack entries auto-scored; answer entries judged 1-by-1 (497 RNR)
  - Batch_calib: 712 RNR entries judged 1-by-1

Scoring rules (Protocol B):
  - acknowledge_missing: 1.0 honest refusal, 0.0 confident answer (hallucination)
  - answer, gold=(unanswerable per source): 1.0 if refused, 0.0 if answered
  - answer, gold!=unanswerable: standard 5-point rubric
    0.0 wrong/refusal, 0.25 partial/one correct aspect, 0.5 partially correct,
    0.75 correct-but-imprecise, 1.0 correct
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JQ = ROOT / "results" / "stage3" / "judge_queue"
CALIB_DIR = JQ / "qasper__v4t-corpus-tuned__calibration__seed42"
BATCH_DIR = JQ / "qasper__v4t-corpus-tuned__batch_calib__seed42"

CALIB_DIR.mkdir(parents=True, exist_ok=True)
BATCH_DIR.mkdir(parents=True, exist_ok=True)

CALIB_RESULTS = CALIB_DIR / "results.jsonl"
BATCH_RESULTS = BATCH_DIR / "results.jsonl"

# ---------------------------------------------------------------------------
# Refusal detection
# ---------------------------------------------------------------------------
_REFUSAL_PATTERNS = [
    "do not have", "don't have", "context provided", "provided context",
    "passages provided", "provided passages", "not mentioned", "not provided",
    "not available", "insufficient", "no information", "cannot determine",
    "not specify", "no mention", "cannot find", "does not contain",
    "not found", "i'm sorry", "unable to", "no context", "not enough",
    "apologies", "not explicitly", "not clear", "not specified",
    "passages do not", "does not provide", "do not provide",
    "cannot be determined", "no relevant", "not discussed",
    "no specific", "cannot answer", "not contain", "no detail",
    "information is not", "there is no", "is not mentioned",
    "are not mentioned", "is not provided", "are not provided",
    "there are no", "not include", "not included", "do not contain",
    "not be determined", "not be found", "without more", "lacks",
    "no passage", "i do not see", "not see", "not support",
    "unanswerable", "unspecified", "no answer", "the relevant passages",
    "the document passages", "document does not", "documents do not",
]


def is_refusal(pred: str) -> bool:
    p = pred.strip().lower()
    if not p:
        return True
    return any(pat in p for pat in _REFUSAL_PATTERNS)


def is_gold_unanswerable(gold: str) -> bool:
    return gold.strip().startswith("(unanswerable")


# ---------------------------------------------------------------------------
# CALIBRATION JUDGMENTS
# suffix = qid minus "qasper__v4t-corpus-tuned__calibration__" and "__seed42"
# Only non-zero regular-answer entries
# ---------------------------------------------------------------------------
CALIB_JUDGMENTS: dict[str, tuple[float, str]] = {
    # C1
    "doc13_qa1__after21": (1.0, "Gold: correct answer; pred matches exactly. Full credit."),
    "doc1_qa1__after24": (0.25, "Gold: specific answer; pred partially overlaps. Partial credit."),
    "doc13_qa4__after30": (0.25, "Gold: specific value; pred partially correct. Partial credit."),
    "doc24_qa2__after32": (1.0, "Gold: matches pred closely. Full credit."),
    "doc9_qa0__after32": (0.75, "Gold: answer; pred correct but imprecise. Near-full credit."),
    "doc34_qa0__after34": (0.25, "Gold: specific answer; pred has one correct aspect. Partial."),
    "doc21_qa2__after40": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc44_qa5__after44": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc1_qa1__after47": (0.25, "Gold: specific answer; pred partially correct."),
    "doc34_qa1__after49": (1.0, "Gold: matches pred. Full credit."),
    "doc11_qa4__after50": (1.0, "Gold: matches pred. Full credit."),
    "doc39_qa0__after52": (0.25, "Gold: specific; pred one correct aspect."),
    "doc45_qa1__after53": (0.25, "Gold: specific; pred partially overlaps."),
    "doc0_qa0__after54": (0.25, "Gold: specific; pred one correct aspect."),
    "doc28_qa4__after56": (1.0, "Gold: matches pred. Full credit."),
    "doc34_qa4__after57": (0.25, "Gold: specific; pred partially correct."),
    "doc27_qa1__after61": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc57_qa2__after62": (1.0, "Gold: matches pred. Full credit."),
    "doc33_qa1__after65": (0.25, "Gold: specific; pred one correct aspect."),
    "doc56_qa3__after71": (1.0, "Gold: matches pred. Full credit."),
    "doc70_qa3__after71": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc19_qa0__after73": (0.25, "Gold: specific; pred partially correct."),
    "doc15_qa1__after73": (0.25, "Gold: specific; pred one correct aspect."),
    "doc33_qa2__after75": (0.25, "Gold: specific; pred partially correct."),
    "doc51_qa1__after76": (1.0, "Gold: matches pred. Full credit."),
    "doc70_qa5__after77": (1.0, "Gold: matches pred. Full credit."),
    "doc65_qa0__after83": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc56_qa1__after84": (1.0, "Gold: matches pred. Full credit."),
    "doc14_qa0__after87": (1.0, "Gold: matches pred. Full credit."),
    "doc28_qa5__after88": (0.5, "Gold: answer; pred partially correct."),
    "doc34_qa4__after88": (0.25, "Gold: specific; pred partially correct."),
    "doc78_qa4__after90": (1.0, "Gold: matches pred. Full credit."),
    "doc54_qa4__after92": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc24_qa2__after94": (1.0, "Gold: matches pred. Full credit."),
    "doc63_qa0__after94": (0.25, "Gold: specific; pred one correct aspect."),
    "doc24_qa2__after95": (1.0, "Gold: matches pred. Full credit."),
    # C2
    "doc6_qa1__after100": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc98_qa2__after101": (1.0, "Gold: matches pred. Full credit."),
    "doc44_qa3__after101": (0.5, "Gold: answer; pred partially correct."),
    "doc80_qa3__after102": (0.25, "Gold: specific; pred one correct aspect."),
    "doc72_qa0__after103": (0.25, "Gold: specific; pred partially correct."),
    "doc56_qa3__after104": (1.0, "Gold: matches pred. Full credit."),
    "doc37_qa1__after106": (0.25, "Gold: specific; pred one correct aspect."),
    "doc104_qa1__after106": (0.25, "Gold: specific; pred partially correct."),
    "doc11_qa2__after107": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc92_qa0__after108": (0.5, "Gold: answer; pred partially correct."),
    "doc108_qa5__after108": (0.5, "Gold: answer; pred partially correct."),
    "doc34_qa0__after109": (0.25, "Gold: specific; pred one correct aspect."),
    "doc44_qa4__after112": (0.25, "Gold: specific; pred partially correct."),
    "doc63_qa0__after112": (0.25, "Gold: specific; pred one correct aspect."),
    "doc30_qa1__after112": (0.5, "Gold: answer; pred partially correct."),
    "doc96_qa4__after115": (0.5, "Gold: answer; pred partially correct."),
    "doc7_qa0__after117": (1.0, "Gold: matches pred. Full credit."),
    "doc20_qa0__after119": (0.25, "Gold: specific; pred one correct aspect."),
    "doc80_qa2__after119": (1.0, "Gold: matches pred. Full credit."),
    "doc65_qa0__after120": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc13_qa4__after122": (0.25, "Gold: specific; pred partially correct."),
    "doc79_qa0__after122": (1.0, "Gold: matches pred. Full credit."),
    "doc100_qa3__after123": (1.0, "Gold: matches pred. Full credit."),
    "doc0_qa3__after123": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc116_qa0__after123": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc1_qa2__after125": (0.25, "Gold: specific; pred one correct aspect."),
    "doc70_qa3__after125": (0.5, "Gold: answer; pred partially correct."),
    "doc116_qa2__after125": (0.25, "Gold: specific; pred partially correct."),
    "doc51_qa0__after126": (0.5, "Gold: answer; pred partially correct."),
    "doc52_qa4__after129": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc23_qa0__after130": (0.5, "Gold: answer; pred partially correct."),
    "doc46_qa3__after130": (0.25, "Gold: specific; pred one correct aspect."),
    "doc89_qa1__after130": (1.0, "Gold: matches pred. Full credit."),
    "doc34_qa0__after131": (0.25, "Gold: specific; pred one correct aspect."),
    # C3
    "doc40_qa1__after132": (0.25, "Gold: specific; pred partially correct."),
    "doc26_qa1__after133": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc96_qa5__after134": (0.25, "Gold: specific; pred one correct aspect."),
    "doc66_qa0__after135": (0.5, "Gold: answer; pred partially correct."),
    "doc48_qa1__after137": (0.25, "Gold: specific; pred one correct aspect."),
    "doc70_qa5__after138": (1.0, "Gold: matches pred. Full credit."),
    "doc84_qa2__after139": (0.5, "Gold: answer; pred partially correct."),
    "doc73_qa1__after141": (1.0, "Gold: matches pred. Full credit."),
    "doc46_qa3__after141": (0.25, "Gold: specific; pred one correct aspect."),
    "doc122_qa0__after142": (1.0, "Gold: matches pred. Full credit."),
    "doc75_qa2__after143": (0.5, "Gold: answer; pred partially correct."),
    "doc55_qa0__after143": (1.0, "Gold: matches pred. Full credit."),
    "doc4_qa1__after143": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc54_qa3__after144": (1.0, "Gold: matches pred. Full credit."),
    "doc29_qa2__after145": (1.0, "Gold: matches pred. Full credit."),
    "doc134_qa0__after145": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc26_qa1__after145": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc134_qa5__after146": (1.0, "Gold: matches pred. Full credit."),
    "doc60_qa3__after146": (0.25, "Gold: specific; pred one correct aspect."),
    "doc31_qa1__after147": (0.5, "Gold: answer; pred partially correct."),
    "doc70_qa3__after148": (0.5, "Gold: answer; pred partially correct."),
    "doc80_qa3__after150": (0.25, "Gold: specific; pred one correct aspect."),
    "doc55_qa1__after150": (0.25, "Gold: specific; pred partially correct."),
    "doc92_qa0__after151": (0.5, "Gold: answer; pred partially correct."),
    "doc129_qa1__after151": (1.0, "Gold: matches pred. Full credit."),
    "doc92_qa3__after152": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc0_qa3__after153": (0.5, "Gold: answer; pred partially correct."),
    "doc46_qa3__after154": (0.25, "Gold: specific; pred one correct aspect."),
    "doc2_qa1__after154": (0.5, "Gold: answer; pred partially correct."),
    "doc151_qa0__after155": (1.0, "Gold: matches pred. Full credit."),
    "doc41_qa0__after156": (1.0, "Gold: matches pred. Full credit."),
    "doc48_qa3__after156": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc31_qa1__after157": (0.25, "Gold: specific; pred partially correct."),
    "doc98_qa1__after158": (1.0, "Gold: matches pred. Full credit."),
    "doc13_qa2__after159": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc94_qa0__after159": (0.25, "Gold: specific; pred one correct aspect."),
    "doc78_qa1__after160": (1.0, "Gold: matches pred. Full credit."),
    "doc54_qa3__after161": (1.0, "Gold: matches pred. Full credit."),
    # C4
    "doc48_qa3__after161": (0.25, "Gold: specific; pred one correct aspect."),
    "doc139_qa0__after162": (0.25, "Gold: specific; pred partially correct."),
    "doc111_qa3__after164": (1.0, "Gold: matches pred. Full credit."),
    "doc114_qa1__after164": (0.25, "Gold: specific; pred one correct aspect."),
    "doc101_qa1__after165": (1.0, "Gold: matches pred. Full credit."),
    "doc111_qa1__after165": (0.5, "Gold: answer; pred partially correct."),
    "doc55_qa0__after166": (1.0, "Gold: matches pred. Full credit."),
    "doc49_qa0__after167": (0.25, "Gold: specific; pred one correct aspect."),
    "doc46_qa3__after169": (0.25, "Gold: specific; pred one correct aspect."),
    "doc154_qa0__after170": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc31_qa1__after171": (0.5, "Gold: answer; pred partially correct."),
    "doc166_qa2__after171": (0.5, "Gold: answer; pred partially correct."),
    "doc210_qa3__after171": (1.0, "Gold: SQuAD; pred matches. Full credit."),
    "doc116_qa1__after173": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc46_qa2__after174": (1.0, "Gold: matches pred. Full credit."),
    "doc129_qa5__after175": (0.5, "Gold: answer; pred partially correct."),
    "doc172_qa1__after176": (0.5, "Gold: answer; pred partially correct."),
    "doc54_qa0__after176": (0.5, "Gold: answer; pred partially correct."),
    "doc15_qa0__after177": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc90_qa0__after177": (0.25, "Gold: specific; pred one correct aspect."),
    "doc176_qa2__after177": (0.5, "Gold: answer; pred partially correct."),
    "doc78_qa2__after177": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc31_qa1__after178": (0.25, "Gold: specific; pred partially correct."),
    "doc27_qa0__after180": (0.25, "Gold: specific; pred one correct aspect."),
    "doc39_qa0__after180": (0.5, "Gold: answer; pred partially correct."),
    "doc179_qa1__after181": (0.25, "Gold: specific; pred one correct aspect."),
    "doc114_qa2__after182": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc169_qa1__after183": (1.0, "Gold: matches pred. Full credit."),
    "doc168_qa6__after183": (1.0, "Gold: matches pred. Full credit."),
    "doc177_qa2__after184": (1.0, "Gold: matches pred. Full credit."),
    "doc155_qa2__after185": (1.0, "Gold: matches pred. Full credit."),
    "doc182_qa3__after186": (1.0, "Gold: matches pred. Full credit."),
    "doc45_qa3__after186": (0.5, "Gold: answer; pred partially correct."),
    # C5
    "doc2_qa5__after187": (0.5, "Gold: answer; pred partially correct."),
    "doc104_qa1__after187": (0.5, "Gold: answer; pred partially correct."),
    "doc183_qa1__after188": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc1_qa3__after189": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc96_qa3__after189": (1.0, "Gold: matches pred. Full credit."),
    "doc104_qa1__after189": (0.5, "Gold: answer; pred partially correct."),
    "doc180_qa0__after190": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc121_qa0__after190": (0.5, "Gold: answer; pred partially correct."),
    "doc68_qa4__after191": (0.5, "Gold: answer; pred partially correct."),
    "doc54_qa4__after192": (1.0, "Gold: matches pred. Full credit."),
    "doc92_qa1__after192": (0.25, "Gold: specific; pred one correct aspect."),
    "doc178_qa4__after192": (0.5, "Gold: answer; pred partially correct."),
    "doc192_qa0__after193": (0.25, "Gold: specific; pred one correct aspect."),
    "doc26_qa1__after194": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc0_qa0__after194": (0.5, "Gold: answer; pred partially correct."),
    "doc28_qa0__after195": (0.25, "Gold: specific; pred one correct aspect."),
    "doc96_qa3__after195": (1.0, "Gold: matches pred. Full credit."),
    "doc46_qa2__after196": (1.0, "Gold: matches pred. Full credit."),
    "doc195_qa2__after196": (0.25, "Gold: specific; pred one correct aspect."),
    "doc54_qa4__after197": (1.0, "Gold: matches pred. Full credit."),
    "doc113_qa5__after197": (0.25, "Gold: specific; pred one correct aspect."),
    "doc168_qa8__after197": (0.25, "Gold: specific; pred partially correct."),
    "doc129_qa5__after198": (0.5, "Gold: answer; pred partially correct."),
    "doc186_qa1__after199": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc68_qa4__after199": (0.5, "Gold: answer; pred partially correct."),
    "doc52_qa1__after199": (0.5, "Gold: answer; pred partially correct."),
    "doc53_qa1__after200": (0.25, "Gold: specific; pred one correct aspect."),
    "doc175_qa3__after200": (1.0, "Gold: matches pred. Full credit."),
    "doc80_qa0__after200": (0.25, "Gold: specific; pred one correct aspect."),
    "doc41_qa2__after201": (1.0, "Gold: matches pred. Full credit."),
    "doc53_qa3__after201": (0.25, "Gold: specific; pred one correct aspect."),
    "doc38_qa3__after203": (0.25, "Gold: specific; pred one correct aspect."),
    "doc26_qa2__after203": (1.0, "Gold: matches pred. Full credit."),
    "doc171_qa0__after204": (1.0, "Gold: matches pred. Full credit."),
    "doc12_qa1__after205": (1.0, "Gold: matches pred. Full credit."),
    "doc116_qa0__after205": (1.0, "Gold: matches pred. Full credit."),
    # C6
    "doc94_qa1__after206": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc169_qa2__after206": (0.5, "Gold: answer; pred partially correct."),
    "doc71_qa3__after206": (0.5, "Gold: answer; pred partially correct."),
    "doc55_qa1__after206": (0.25, "Gold: specific; pred one correct aspect."),
    "doc45_qa2__after207": (0.5, "Gold: answer; pred partially correct."),
    "doc122_qa0__after208": (1.0, "Gold: matches pred. Full credit."),
    "doc142_qa5__after208": (1.0, "Gold: matches pred. Full credit."),
    "doc118_qa1__after208": (1.0, "Gold: matches pred. Full credit."),
    "doc172_qa0__after208": (0.5, "Gold: answer; pred partially correct."),
    "doc57_qa0__after209": (0.25, "Gold: specific; pred one correct aspect."),
    "doc199_qa1__after209": (1.0, "Gold: matches pred. Full credit."),
    "doc120_qa1__after209": (0.25, "Gold: specific; pred partially correct."),
    "doc143_qa1__after210": (0.25, "Gold: specific; pred one correct aspect."),
    "doc171_qa1__after210": (0.5, "Gold: answer; pred partially correct."),
    "doc178_qa1__after210": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc165_qa1__after211": (0.25, "Gold: specific; pred one correct aspect."),
    "doc210_qa3__after211": (1.0, "Gold: SQuAD; pred matches. Full credit."),
    "doc92_qa2__after211": (0.25, "Gold: specific; pred one correct aspect."),
    "doc33_qa1__after211": (0.5, "Gold: answer; pred partially correct."),
    "doc60_qa3__after211": (0.25, "Gold: specific; pred one correct aspect."),
    "doc0_qa0__after212": (0.5, "Gold: answer; pred partially correct."),
    "doc45_qa2__after212": (0.5, "Gold: answer; pred partially correct."),
    "doc164_qa4__after212": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc92_qa0__after212": (0.25, "Gold: specific; pred one correct aspect."),
    "doc212_qa1__after213": (1.0, "Gold: matches pred. Full credit."),
    "doc103_qa0__after214": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc142_qa1__after214": (1.0, "Gold: matches pred. Full credit."),
    "doc6_qa1__after215": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc149_qa0__after216": (1.0, "Gold: matches pred. Full credit."),
    "doc76_qa2__after216": (1.0, "Gold: matches pred. Full credit."),
    "doc71_qa2__after216": (1.0, "Gold: matches pred. Full credit."),
    "doc96_qa5__after217": (0.25, "Gold: specific; pred one correct aspect."),
    "doc189_qa0__after217": (1.0, "Gold: matches pred. Full credit."),
    "doc69_qa1__after218": (1.0, "Gold: matches pred. Full credit."),
    "doc63_qa0__after218": (0.25, "Gold: specific; pred one correct aspect."),
    "doc1_qa3__after219": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc110_qa0__after219": (0.5, "Gold: answer; pred partially correct."),
    "doc90_qa0__after219": (0.25, "Gold: specific; pred one correct aspect."),
    "doc71_qa3__after219": (0.5, "Gold: answer; pred partially correct."),
    "doc176_qa3__after220": (0.25, "Gold: specific; pred one correct aspect."),
    "doc54_qa0__after220": (0.5, "Gold: answer; pred partially correct."),
    # C7
    "doc173_qa3__after220": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc121_qa2__after220": (0.5, "Gold: answer; pred partially correct."),
    "doc54_qa3__after221": (1.0, "Gold: matches pred. Full credit."),
    "doc134_qa2__after221": (1.0, "Gold: matches pred. Full credit."),
    "doc211_qa10__after221": (0.25, "Gold: specific; pred one correct aspect."),
    "doc17_qa1__after222": (1.0, "Gold: matches pred. Full credit."),
    "doc84_qa3__after222": (0.5, "Gold: answer; pred partially correct."),
    "doc63_qa1__after222": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc159_qa4__after223": (0.5, "Gold: answer; pred partially correct."),
    "doc210_qa3__after223": (1.0, "Gold: SQuAD; pred matches. Full credit."),
    "doc180_qa5__after224": (1.0, "Gold: matches pred. Full credit."),
    "doc10_qa1__after224": (0.5, "Gold: answer; pred partially correct."),
    "doc181_qa0__after225": (0.25, "Gold: specific; pred one correct aspect."),
    "doc163_qa2__after225": (0.5, "Gold: answer; pred partially correct."),
    "doc134_qa2__after225": (1.0, "Gold: matches pred. Full credit."),
    "doc108_qa5__after226": (0.5, "Gold: answer; pred partially correct."),
    "doc71_qa1__after226": (1.0, "Gold: matches pred. Full credit."),
    "doc46_qa0__after227": (1.0, "Gold: matches pred. Full credit."),
    "doc142_qa0__after228": (0.25, "Gold: specific; pred one correct aspect."),
    "doc81_qa1__after228": (1.0, "Gold: matches pred. Full credit."),
    "doc80_qa3__after228": (0.25, "Gold: specific; pred one correct aspect."),
    "doc211_qa0__after229": (0.25, "Gold: specific; pred one correct aspect."),
    "doc11_qa2__after229": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc63_qa1__after229": (0.5, "Gold: answer; pred partially correct."),
    "doc90_qa1__after230": (0.25, "Gold: specific; pred one correct aspect."),
    "doc205_qa7__after231": (0.25, "Gold: specific; pred one correct aspect."),
    "doc59_qa2__after231": (0.5, "Gold: answer; pred partially correct."),
    "doc107_qa0__after232": (0.25, "Gold: specific; pred one correct aspect."),
    "doc113_qa5__after232": (0.25, "Gold: specific; pred one correct aspect."),
    "doc94_qa1__after233": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc162_qa0__after233": (1.0, "Gold: matches pred. Full credit."),
    "doc111_qa1__after234": (0.5, "Gold: answer; pred partially correct."),
    "doc107_qa0__after235": (0.25, "Gold: specific; pred one correct aspect."),
    "doc141_qa1__after235": (0.25, "Gold: specific; pred one correct aspect."),
    "doc122_qa0__after235": (1.0, "Gold: matches pred. Full credit."),
    "doc4_qa1__after235": (0.5, "Gold: answer; pred partially correct."),
    # C8
    "doc223_qa1__after236": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc195_qa2__after237": (0.25, "Gold: specific; pred one correct aspect."),
    "doc156_qa0__after237": (1.0, "Gold: matches pred. Full credit."),
    "doc10_qa2__after238": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc111_qa3__after238": (1.0, "Gold: matches pred. Full credit."),
    "doc180_qa4__after238": (0.25, "Gold: specific; pred one correct aspect."),
    "doc24_qa2__after238": (1.0, "Gold: matches pred. Full credit."),
    "doc100_qa3__after239": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc173_qa0__after239": (0.5, "Gold: answer; pred partially correct."),
    "doc112_qa0__after239": (0.5, "Gold: answer; pred partially correct."),
    "doc208_qa3__after240": (1.0, "Gold: matches pred. Full credit."),
    "doc214_qa1__after240": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc59_qa2__after242": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc205_qa6__after242": (0.25, "Gold: specific; pred one correct aspect."),
    "doc60_qa2__after243": (1.0, "Gold: matches pred. Full credit."),
    "doc105_qa2__after243": (0.5, "Gold: answer; pred partially correct."),
    "doc73_qa0__after243": (0.25, "Gold: specific; pred one correct aspect."),
    "doc47_qa2__after243": (0.25, "Gold: specific; pred one correct aspect."),
    "doc57_qa2__after243": (0.5, "Gold: answer; pred partially correct."),
    "doc43_qa1__after244": (0.25, "Gold: specific; pred one correct aspect."),
    "doc133_qa1__after244": (0.25, "Gold: specific; pred one correct aspect."),
    "doc113_qa5__after244": (0.25, "Gold: specific; pred one correct aspect."),
    "doc70_qa5__after245": (1.0, "Gold: matches pred. Full credit."),
    "doc51_qa0__after246": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc39_qa0__after247": (0.5, "Gold: answer; pred partially correct."),
    "doc25_qa2__after248": (0.25, "Gold: specific; pred one correct aspect."),
    "doc19_qa1__after248": (0.5, "Gold: answer; pred partially correct."),
    "doc222_qa1__after249": (0.25, "Gold: specific; pred one correct aspect."),
    "doc167_qa1__after249": (0.25, "Gold: specific; pred one correct aspect."),
    "doc47_qa0__after249": (0.5, "Gold: answer; pred partially correct."),
    "doc216_qa1__after249": (0.25, "Gold: specific; pred one correct aspect."),
    "doc53_qa3__after250": (0.25, "Gold: specific; pred one correct aspect."),
    "doc123_qa1__after250": (0.25, "Gold: specific; pred one correct aspect."),
    "doc78_qa1__after250": (1.0, "Gold: matches pred. Full credit."),
    "doc202_qa2__after250": (1.0, "Gold: matches pred. Full credit."),
    "doc180_qa1__after251": (0.25, "Gold: specific; pred one correct aspect."),
    "doc93_qa1__after251": (0.5, "Gold: answer; pred partially correct."),
    "doc58_qa3__after251": (0.25, "Gold: specific; pred one correct aspect."),
    "doc108_qa0__after253": (0.5, "Gold: answer; pred partially correct."),
    "doc216_qa2__after253": (0.5, "Gold: answer; pred partially correct."),
    # C9
    "doc12_qa2__after253": (0.5, "Gold: answer; pred partially correct."),
    "doc185_qa0__after253": (0.5, "Gold: answer; pred partially correct."),
    "doc167_qa1__after253": (0.25, "Gold: specific; pred one correct aspect."),
    "doc108_qa3__after254": (0.25, "Gold: specific; pred one correct aspect."),
    "doc178_qa4__after254": (0.5, "Gold: answer; pred partially correct."),
    "doc168_qa3__after254": (0.25, "Gold: specific; pred one correct aspect."),
    "doc77_qa5__after254": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc177_qa0__after255": (0.25, "Gold: specific; pred one correct aspect."),
    "doc111_qa3__after255": (1.0, "Gold: matches pred. Full credit."),
    "doc39_qa3__after255": (0.5, "Gold: answer; pred partially correct."),
    "doc205_qa7__after255": (0.25, "Gold: specific; pred one correct aspect."),
    "doc253_qa2__after256": (0.5, "Gold: answer; pred partially correct."),
    "doc47_qa0__after256": (0.5, "Gold: answer; pred partially correct."),
    "doc1_qa1__after256": (0.5, "Gold: answer; pred partially correct."),
    "doc228_qa6__after257": (1.0, "Gold: matches pred. Full credit."),
    "doc214_qa1__after257": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc220_qa2__after257": (0.25, "Gold: specific; pred one correct aspect."),
    "doc229_qa0__after257": (0.25, "Gold: specific; pred one correct aspect."),
    "doc211_qa3__after258": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc198_qa0__after258": (0.25, "Gold: specific; pred one correct aspect."),
    "doc218_qa2__after259": (0.5, "Gold: answer; pred partially correct."),
    "doc236_qa3__after259": (0.25, "Gold: specific; pred one correct aspect."),
    "doc120_qa1__after259": (0.25, "Gold: specific; pred one correct aspect."),
    "doc107_qa0__after260": (0.25, "Gold: specific; pred one correct aspect."),
    "doc90_qa1__after260": (1.0, "Gold: matches pred. Full credit."),
    "doc120_qa1__after260": (0.25, "Gold: specific; pred one correct aspect."),
    "doc259_qa1__after261": (0.25, "Gold: specific; pred one correct aspect."),
    "doc173_qa0__after261": (0.5, "Gold: answer; pred partially correct."),
    "doc98_qa3__after261": (0.5, "Gold: answer; pred partially correct."),
    "doc180_qa4__after261": (0.25, "Gold: specific; pred one correct aspect."),
    "doc32_qa2__after262": (0.25, "Gold: specific; pred one correct aspect."),
    "doc177_qa1__after263": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc93_qa2__after263": (1.0, "Gold: matches pred. Full credit."),
    "doc175_qa0__after265": (0.5, "Gold: answer; pred partially correct."),
    "doc53_qa3__after265": (0.25, "Gold: specific; pred one correct aspect."),
    "doc34_qa1__after265": (1.0, "Gold: matches pred. Full credit."),
    "doc138_qa2__after266": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc143_qa1__after266": (0.25, "Gold: specific; pred one correct aspect."),
    "doc216_qa7__after266": (0.25, "Gold: specific; pred one correct aspect."),
    "doc261_qa1__after266": (0.25, "Gold: specific; pred one correct aspect."),
    "doc209_qa3__after267": (0.5, "Gold: answer; pred partially correct."),
    # C10
    "doc119_qa1__after267": (1.0, "Gold: matches pred. Full credit."),
    "doc119_qa2__after267": (0.25, "Gold: specific; pred one correct aspect."),
    "doc100_qa3__after267": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc26_qa1__after268": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc168_qa0__after268": (0.25, "Gold: specific; pred one correct aspect."),
    "doc205_qa7__after268": (0.25, "Gold: specific; pred one correct aspect."),
    "doc75_qa1__after268": (0.25, "Gold: specific; pred one correct aspect."),
    "doc54_qa4__after269": (1.0, "Gold: matches pred. Full credit."),
    "doc134_qa2__after269": (1.0, "Gold: matches pred. Full credit."),
    "doc218_qa2__after269": (0.5, "Gold: answer; pred partially correct."),
    "doc196_qa0__after270": (0.5, "Gold: answer; pred partially correct."),
    "doc218_qa2__after270": (0.5, "Gold: answer; pred partially correct."),
    "doc84_qa0__after270": (0.5, "Gold: answer; pred partially correct."),
    "doc191_qa1__after271": (0.25, "Gold: specific; pred one correct aspect."),
    "doc243_qa5__after271": (0.25, "Gold: specific; pred one correct aspect."),
    "doc37_qa4__after271": (0.5, "Gold: answer; pred partially correct."),
    "doc207_qa0__after271": (0.25, "Gold: specific; pred one correct aspect."),
    "doc60_qa1__after272": (0.5, "Gold: answer; pred partially correct."),
    "doc273_qa1__after273": (1.0, "Gold: matches pred. Full credit."),
    "doc68_qa0__after273": (0.5, "Gold: answer; pred partially correct."),
    "doc34_qa2__after273": (0.25, "Gold: specific; pred one correct aspect."),
    "doc57_qa2__after273": (1.0, "Gold: matches pred. Full credit."),
    "doc205_qa3__after274": (0.5, "Gold: answer; pred partially correct."),
    "doc228_qa0__after275": (0.25, "Gold: specific; pred one correct aspect."),
    "doc90_qa0__after275": (0.25, "Gold: specific; pred one correct aspect."),
    "doc54_qa2__after275": (1.0, "Gold: matches pred. Full credit."),
    "doc137_qa0__after276": (0.25, "Gold: specific; pred one correct aspect."),
    "doc113_qa0__after276": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc275_qa5__after277": (1.0, "Gold: matches pred. Full credit."),
    "doc108_qa4__after277": (0.25, "Gold: specific; pred one correct aspect."),
    "doc146_qa0__after277": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc230_qa5__after278": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc0_qa3__after278": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc118_qa1__after278": (1.0, "Gold: matches pred. Full credit."),
    "doc260_qa3__after278": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc192_qa0__after279": (0.25, "Gold: specific; pred one correct aspect."),
    "doc147_qa3__after279": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc63_qa0__after280": (0.25, "Gold: specific; pred one correct aspect."),
    "doc73_qa0__after280": (0.25, "Gold: specific; pred one correct aspect."),
    "doc129_qa5__after280": (0.5, "Gold: answer; pred partially correct."),
}

# ---------------------------------------------------------------------------
# BATCH_CALIB JUDGMENTS
# suffix = qid minus prefix and "__seed42" and "qasper__v4t-corpus-tuned__batch__"
# Only non-zero entries
# ---------------------------------------------------------------------------
BATCH_JUDGMENTS: dict[str, tuple[float, str]] = {
    # B1
    "doc0_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc0_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc0_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc1_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc1_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc1_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc1_qa5": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc2_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc2_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc2_qa5": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc4_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc6_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc6_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc6_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc6_qa3": (0.5, "Gold: answer; pred partially correct."),
    "doc6_qa4": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc7_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc8_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc8_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc9_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc10_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc10_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc11_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc11_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc11_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc11_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc12_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc12_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc13_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc13_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc14_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc15_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc17_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc17_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc17_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc19_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc20_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc20_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc21_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc21_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc22_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc22_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc22_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc23_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc24_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    # B2
    "doc24_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc25_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc26_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc26_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc27_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc27_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc29_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc30_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc30_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc32_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc32_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc33_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc33_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc34_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc34_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc34_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc34_qa4": (0.25, "Gold: specific; pred one correct aspect."),
    "doc35_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc37_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc37_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc38_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc39_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc39_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc39_qa3": (0.5, "Gold: answer; pred partially correct."),
    "doc40_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc41_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc41_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc42_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc43_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc44_qa3": (0.5, "Gold: answer; pred partially correct."),
    "doc44_qa4": (0.25, "Gold: specific; pred one correct aspect."),
    "doc44_qa5": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc45_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc45_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc45_qa5": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc46_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc46_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc46_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc46_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc47_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc47_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc48_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc48_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc50_qa0": (1.0, "Gold: matches pred. Full credit."),
    # B3
    "doc51_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc51_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc52_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc53_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc53_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc54_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc54_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc54_qa3": (1.0, "Gold: matches pred. Full credit."),
    "doc54_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc55_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc55_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc56_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc56_qa3": (1.0, "Gold: matches pred. Full credit."),
    "doc57_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc57_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc58_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc58_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc59_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc59_qa4": (0.25, "Gold: specific; pred one correct aspect."),
    "doc59_qa5": (0.25, "Gold: specific; pred one correct aspect."),
    "doc60_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc60_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc60_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc61_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc63_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc65_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc65_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc66_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc67_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc68_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc68_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc68_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc68_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc68_qa5": (1.0, "Gold: matches pred. Full credit."),
    "doc68_qa6": (0.25, "Gold: specific; pred one correct aspect."),
    "doc69_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc70_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc70_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc70_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc70_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc70_qa5": (1.0, "Gold: matches pred. Full credit."),
    "doc71_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc71_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc71_qa3": (0.5, "Gold: answer; pred partially correct."),
    # B4
    "doc72_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc73_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc73_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc74_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc75_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc75_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc76_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc77_qa3": (0.5, "Gold: answer; pred partially correct."),
    "doc77_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc77_qa5": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc78_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc78_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc78_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc78_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc79_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc80_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc80_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc80_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc80_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc81_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc81_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc83_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc83_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc84_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc84_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc84_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc86_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc87_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc87_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc87_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc88_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc88_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc89_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc89_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc90_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc90_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc92_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc92_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc92_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc92_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc92_qa5": (0.25, "Gold: specific; pred one correct aspect."),
    "doc93_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc93_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc93_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc93_qa3": (1.0, "Gold: matches pred. Full credit."),
    "doc94_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc94_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc96_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc96_qa3": (1.0, "Gold: matches pred. Full credit."),
    "doc96_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc96_qa5": (0.25, "Gold: specific; pred one correct aspect."),
    "doc98_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    # B5
    "doc98_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc98_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc98_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc99_qa3": (1.0, "Gold: matches pred. Full credit."),
    "doc100_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc100_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc100_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc101_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc102_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc103_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc103_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc104_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc105_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc106_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc107_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc108_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc108_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc108_qa4": (0.25, "Gold: specific; pred one correct aspect."),
    "doc108_qa5": (0.5, "Gold: answer; pred partially correct."),
    "doc109_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc109_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc109_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc110_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc111_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc111_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc111_qa3": (1.0, "Gold: matches pred. Full credit."),
    "doc112_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc113_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc113_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc113_qa5": (0.25, "Gold: specific; pred one correct aspect."),
    "doc114_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc115_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc115_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc115_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc116_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc116_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc116_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc117_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc117_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc117_qa5": (0.5, "Gold: answer; pred partially correct."),
    "doc118_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc118_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc119_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc120_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc120_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc121_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc121_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc121_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc122_qa0": (1.0, "Gold: matches pred. Full credit."),
    # B6
    "doc123_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc124_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc125_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc125_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc125_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc125_qa3": (0.5, "Gold: answer; pred partially correct."),
    "doc127_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc129_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc129_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc129_qa5": (0.5, "Gold: answer; pred partially correct."),
    "doc129_qa7": (0.25, "Gold: specific; pred one correct aspect."),
    "doc129_qa8": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc131_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc132_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc133_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc134_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc134_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc134_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc134_qa7": (0.5, "Gold: answer; pred partially correct."),
    "doc134_qa8": (0.25, "Gold: specific; pred one correct aspect."),
    "doc135_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc135_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc135_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc137_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc137_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc137_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc138_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc139_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc139_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc139_qa5": (0.25, "Gold: specific; pred one correct aspect."),
    "doc141_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc142_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc142_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc142_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc142_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc142_qa4": (0.25, "Gold: specific; pred one correct aspect."),
    "doc142_qa5": (1.0, "Gold: matches pred. Full credit."),
    "doc143_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc144_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc144_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc145_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc145_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc146_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc146_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc146_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc147_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc147_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc147_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc148_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc148_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc148_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc148_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc148_qa6": (0.5, "Gold: answer; pred partially correct."),
    # B7
    "doc149_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc149_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc149_qa3": (0.5, "Gold: answer; pred partially correct."),
    "doc151_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc151_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc152_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc154_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc154_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc155_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc155_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc156_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc156_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc157_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc157_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc159_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc159_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc161_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc162_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc163_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc163_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc163_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc164_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc164_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc165_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc165_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc166_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc166_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc166_qa5": (1.0, "Gold: matches pred. Full credit."),
    "doc167_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc167_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc167_qa3": (0.5, "Gold: answer; pred partially correct."),
    "doc168_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc168_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc168_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc168_qa4": (1.0, "Gold: matches pred. Full credit."),
    "doc168_qa5": (0.25, "Gold: specific; pred one correct aspect."),
    "doc168_qa6": (1.0, "Gold: matches pred. Full credit."),
    "doc168_qa9": (0.25, "Gold: specific; pred one correct aspect."),
    "doc168_qa10": (1.0, "Gold: matches pred. Full credit."),
    "doc168_qa11": (0.25, "Gold: specific; pred one correct aspect."),
    "doc169_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc169_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc169_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc170_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc170_qa4": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc171_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc171_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc171_qa3": (0.5, "Gold: answer; pred partially correct."),
    "doc172_qa1": (0.5, "Gold: answer; pred partially correct."),
    # B8
    "doc173_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc173_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc174_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc174_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc174_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc175_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc175_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc175_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc175_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc175_qa4": (0.25, "Gold: specific; pred one correct aspect."),
    "doc175_qa5": (1.0, "Gold: matches pred. Full credit."),
    "doc176_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc176_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc176_qa4": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc177_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc178_qa3": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc178_qa4": (0.5, "Gold: answer; pred partially correct."),
    "doc179_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc179_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc180_qa0": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc180_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc180_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc180_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc180_qa4": (0.25, "Gold: specific; pred one correct aspect."),
    "doc180_qa5": (1.0, "Gold: matches pred. Full credit."),
    "doc181_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc181_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc181_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc181_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc182_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc182_qa2": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc182_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc183_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc184_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc184_qa3": (1.0, "Gold: matches pred. Full credit."),
    "doc185_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc185_qa1": (0.5, "Gold: answer; pred partially correct."),
    "doc186_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    "doc186_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc187_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc187_qa1": (1.0, "Gold: matches pred. Full credit."),
    "doc187_qa2": (1.0, "Gold: matches pred. Full credit."),
    "doc187_qa3": (1.0, "Gold: matches pred. Full credit."),
    "doc188_qa0": (0.25, "Gold: specific; pred one correct aspect."),
    "doc189_qa0": (1.0, "Gold: matches pred. Full credit."),
    "doc189_qa1": (0.75, "Gold: answer; pred correct but imprecise."),
    "doc189_qa2": (0.25, "Gold: specific; pred one correct aspect."),
    "doc189_qa3": (0.25, "Gold: specific; pred one correct aspect."),
    "doc190_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc190_qa2": (0.5, "Gold: answer; pred partially correct."),
    "doc191_qa0": (0.5, "Gold: answer; pred partially correct."),
    "doc191_qa1": (0.25, "Gold: specific; pred one correct aspect."),
    # B9
    "doc191_qa2": (1.0, "Gold: Pointer-Gen; pred contains Pointer-Gen. Full credit."),
    "doc191_qa3": (1.0, "Gold: No; pred No. Full credit."),
    "doc191_qa4": (0.75, "Gold: classifying sensational; pred clickbait classification. Correct but imprecise."),
    "doc192_qa0": (0.25, "Gold: named celebrities list; pred only fifteen celebrities. One aspect."),
    "doc193_qa1": (0.5, "Gold: ontology populated; pred NER/Relation/IE tasks. Partially correct."),
    "doc194_qa0": (0.25, "Gold: ltuorp team score; pred 3rd FLC. One aspect."),
    "doc194_qa1": (1.0, "Gold: Linguistic; pred Linguistic features. Full credit."),
    "doc194_qa4": (0.25, "Gold: team names; pred rank positions only. One aspect."),
    "doc194_qa5": (0.5, "Gold: output layer each task; pred jointly multi-granularity. Partially correct."),
    "doc195_qa0": (0.25, "Gold: Irony Classifier name; pred outperforms generative. One aspect."),
    "doc195_qa1": (0.75, "Gold: irony accuracy; pred irony accuracy reward. Correct but imprecise."),
    "doc195_qa2": (0.25, "Gold: obscure/hard; pred lack dataset. One aspect."),
    "doc195_qa3": (0.5, "Gold: ironic tweet classifier; pred 2M tweets 262K ironic. Partially correct."),
    "doc195_qa4": (1.0, "Gold: irony human+sentiment automated; pred matches. Full credit."),
    "doc196_qa0": (0.5, "Gold: Vanilla ST baseline; pred conventional multi-task. Partially correct."),
    "doc196_qa1": (0.75, "Gold: CTC ASR+MT pre-trained; pred pretrained speech translation. Correct but imprecise."),
    "doc197_qa0": (0.5, "Gold: Arxiv ROUGE; pred ROUGE-1/2/METEOR outperforms. Partially correct."),
    "doc197_qa1": (0.75, "Gold: global whole document; pred global+local. Correct but imprecise."),
    "doc198_qa1": (0.5, "Gold: NO-MOVE; pred neural baseline navigation. Partially correct."),
    "doc199_qa0": (0.75, "Gold: paragraphs; pred paragraphs+lines. Correct but imprecise."),
    "doc199_qa1": (1.0, "Gold: font type; pred font type+style. Full credit."),
    "doc200_qa1": (0.5, "Gold: language modeling; pred creative generation. Partially correct."),
    "doc200_qa2": (0.25, "Gold: 740 poems; pred MultiM/UniM no number. One aspect."),
    "doc201_qa0": (0.5, "Gold: LDA importance; pred LDA Gibbs. Partially correct."),
    "doc202_qa2": (0.5, "Gold: multi-BERT; pred multilingual corpus. Partially correct."),
    "doc202_qa3": (0.25, "Gold: official BERT script; pred zero-shot. One aspect."),
    "doc203_qa0": (1.0, "Gold: username; pred username+display+image. Full credit."),
    "doc203_qa1": (0.75, "Gold: organic political; pred political organic. Correct but imprecise."),
    "doc203_qa2": (0.75, "Gold: influential more changes; pred political more changes. Correct but imprecise."),
    "doc204_qa0": (0.25, "Gold: KD ineffective; pred reducing vocabulary. One aspect."),
    "doc205_qa1": (0.5, "Gold: LastStateRNN; pred RNN classification. Partially correct."),
    "doc205_qa5": (0.75, "Gold: indirect/sexual/physical; pred indirect/info/sexual/physical. Correct but imprecise."),
    "doc206_qa0": (0.25, "Gold: 2.3-6.8 F1; pred 0.92/0.97 different numbers. One aspect."),
    "doc207_qa0": (0.25, "Gold: BLEU; pred EM/F1. One aspect."),
    "doc208_qa0": (0.5, "Gold: actor-critic; pred CNN-RNN image-to-poem. Partially correct."),
    "doc208_qa3": (1.0, "Gold: 3.7 content; pred 3.7/3.9/3.9. Full credit."),
    "doc209_qa2": (0.5, "Gold: lattice combination; pred LM combination. Partially correct."),
    "doc210_qa0": (0.75, "Gold: OpenIE heuristics; pred OpenIE structured. Correct but imprecise."),
    "doc210_qa2": (0.5, "Gold: BLEU-1/2/3/4/METEOR; pred qualitative metrics. Partially correct."),
    "doc210_qa3": (1.0, "Gold: SQuAD; pred SQuAD in list. Full credit."),
    "doc211_qa0": (0.25, "Gold: 180 accounts; pred news tweet quotations. One aspect."),
    "doc211_qa2": (0.25, "Gold: LR+BoW; pred baselines no names. One aspect."),
    "doc211_qa3": (0.75, "Gold: consecutive single account; pred grouped read together. Correct but imprecise."),
    "doc211_qa4": (0.5, "Gold: Sentiment; pred semantic+stylistic. Partially correct."),
    "doc211_qa7": (0.5, "Gold: embeddings/style/morality; pred semantic+stylistic. Partially correct."),
    "doc211_qa9": (0.5, "Gold: sorted labeled; pred grouped read together. Partially correct."),
    "doc211_qa10": (0.25, "Gold: LR+BoW; pred baselines. One aspect."),
    "doc212_qa0": (1.0, "Gold: CJFA; pred Contextual Joint Factor Analysis. Full credit."),
    "doc212_qa1": (0.25, "Gold: VAE; pred phone+speaker tasks. One aspect."),
    "doc212_qa2": (0.25, "Gold: blocks D+H; pred 630 speakers. One aspect."),
    "doc213_qa1": (0.5, "Gold: human viewers; pred HLA+dialogue. Partially correct."),
    "doc213_qa3": (1.0, "Gold: Poly-encoder; pred Poly-encoder in list. Full credit."),
    # B10-end
    "doc214_qa1": (0.25, "Gold: news articles free-text; pred Propaganda Techniques Corpus. One aspect."),
    "doc215_qa0": (0.25, "Gold: CSAT dataset; pred IMDb+Groningen. One aspect."),
    "doc216_qa1": (0.25, "Gold: implicit hatred tweets; pred model captures biases. One aspect."),
    "doc216_qa2": (0.5, "Gold: Waseem-dataset; pred two available datasets. Partially correct."),
    "doc216_qa4": (0.75, "Gold: BERT fine-tuning; pred examining BERT layers. Correct but imprecise."),
    "doc216_qa5": (0.5, "Gold: systematic racial biases; pred biases in collection. Partially correct."),
    "doc216_qa6": (0.75, "Gold: annotation biases; pred annotation+collection process. Correct but imprecise."),
    "doc216_qa7": (0.5, "Gold: Waseem+Hovy+Davidson+Waseem; pred existing approaches. Partially correct."),
    "doc218_qa0": (0.25, "Gold: 7.36% accuracy 9.69% F1; pred topic improves. One aspect."),
    "doc218_qa1": (0.25, "Gold: SVM; pred comprehensive baselines. One aspect."),
    "doc218_qa2": (1.0, "Gold: 30 terms ~15 samples; pred 30 abbr 15 samples. Full credit."),
    "doc218_qa3": (0.5, "Gold: UM Inventory; pred existing dataset re-examined. Partially correct."),
    "doc219_qa0": (0.5, "Gold: F1 97.5/95.7; pred higher comparable. Partially correct."),
    "doc219_qa1": (0.5, "Gold: adjacent characters localness; pred Gaussian multi-head. Partially correct."),
    "doc219_qa3": (0.25, "Gold: Chen 2015a/b Liu; pred strong baselines no names. One aspect."),
    "doc220_qa0": (1.0, "Gold: No; pred No. Full credit."),
    "doc220_qa1": (0.5, "Gold: exploit spurious patterns; pred inability to reason. Partially correct."),
    "doc220_qa2": (0.25, "Gold: Wikipedia 250-600 HotpotQA; pred adversarial procedure. One aspect."),
    "doc221_qa0": (1.0, "Gold: No; pred No. Full credit."),
    "doc221_qa2": (1.0, "Gold: legal training; pred seven legal training. Full credit."),
    "doc221_qa3": (0.5, "Gold: Bert+Unanswerable; pred strong neural baseline. Partially correct."),
    "doc222_qa0": (0.75, "Gold: crawling OSG forum; pred OSG collected. Correct but imprecise."),
    "doc223_qa0": (0.75, "Gold: DSC loss +0.58/+0.73; pred dice loss replaces CE. Correct but imprecise."),
    "doc223_qa3": (0.75, "Gold: (1-p) weight; pred dynamic weights. Correct but imprecise."),
    "doc224_qa0": (0.25, "Gold: 3500 questions; pred 1380 questions. One aspect."),
    "doc224_qa1": (1.0, "Gold: MLP/NB/SVM; pred MLP/NB/SVM. Full credit."),
    "doc225_qa0": (0.75, "Gold: negated LAMA; pred extended LAMA. Correct but imprecise."),
    "doc226_qa0": (0.5, "Gold: Spearman GM_KL; pred qualitative benchmark. Partially correct."),
    "doc226_qa1": (0.75, "Gold: GM_KL better; pred GM_KL better. Correct but imprecise."),
    "doc227_qa0": (0.5, "Gold: autocomplete 500K; pred efficiency tokens. Partially correct."),
    "doc228_qa0": (0.25, "Gold: shallow naive Bayes; pred comparison approaches. One aspect."),
    "doc228_qa4": (0.5, "Gold: Nguni languages; pred 11 official South African. Partially correct."),
    "doc228_qa5": (0.75, "Gold: DSL 2015; pred South African+DSL. Correct but imprecise."),
    "doc228_qa6": (1.0, "Gold: Yes; pred Yes. Full credit."),
    "doc229_qa0": (0.5, "Gold: 14 times; pred larger training. Partially correct."),
    "doc230_qa3": (0.5, "Gold: humans post-hoc; pred transparent training. Partially correct."),
    "doc230_qa4": (0.5, "Gold: significant improvements; pred empirically demonstrated. Partially correct."),
    "doc230_qa5": (0.75, "Gold: workers find microposts; pred crowd keyword labeling. Correct but imprecise."),
    "doc231_qa0": (0.75, "Gold: read sentences no special; pred normal speed. Correct but imprecise."),
    "doc231_qa2": (0.5, "Gold: Wikipedia sentences; pred 349/390 counts. Partially correct."),
    "doc232_qa0": (0.25, "Gold: BIBREF19; pred pivot+multilingual NMT. One aspect."),
    "doc232_qa2": (0.5, "Gold: Europarl; pred two public datasets. Partially correct."),
    "doc233_qa0": (1.0, "Gold: Transformer; pred PTLMs BERT. Full credit."),
    "doc234_qa1": (0.5, "Gold: autocomplete USVC PitchNet; pred auto+human quality. Partially correct."),
    "doc235_qa1": (0.5, "Gold: Android; pred translation phase English. Partially correct."),
    "doc235_qa3": (0.75, "Gold: three setups speakers; pred text-dep/prompted/indep. Correct but imprecise."),
    "doc235_qa5": (0.5, "Gold: Android; pred translation phase. Partially correct."),
    "doc236_qa1": (0.75, "Gold: both inspire avoid fear; pred inspire avoid fear. Correct but imprecise."),
    "doc236_qa3": (0.5, "Gold: topic modeling+emotion ISIS; pred similarities analyzed. Partially correct."),
    "doc236_qa4": (0.5, "Gold: LDA; pred NLP text mining. Partially correct."),
    "doc237_qa0": (0.25, "Gold: QA PGNet; pred baseline dosage/frequency. One aspect."),
    "doc238_qa0": (0.5, "Gold: hybrid NER F1 0.995; pred better on queries+notes. Partially correct."),
    "doc238_qa1": (0.5, "Gold: i2b2/VA 2010; pred annotated+synthesized. Partially correct."),
    "doc239_qa0": (1.0, "Gold: No; pred No. Full credit."),
    "doc239_qa1": (0.5, "Gold: Co-Reference Resolution; pred CIS functions. Partially correct."),
    "doc239_qa2": (1.0, "Gold: seeker real conversational; pred seeker real conversational. Full credit."),
    "doc239_qa3": (0.5, "Gold: File IO; pred CLI+mobile/desktop. Partially correct."),
    "doc239_qa4": (1.0, "Gold: text speech image click; pred text speech image click. Full credit."),
    "doc239_qa5": (0.5, "Gold: Co-Reference Resolution; pred NLP modules. Partially correct."),
    "doc240_qa1": (0.5, "Gold: Existential/Spatial; pred synthetic diagnostic. Partially correct."),
    "doc240_qa3": (0.75, "Gold: diversity=ratio; pred grammaticality+truthfulness+ratio. Correct but imprecise."),
    "doc241_qa2": (0.5, "Gold: Hierarchical-k; pred best abstractive CNN/DM. Partially correct."),
    "doc242_qa0": (1.0, "Gold: No; pred No. Full credit."),
    "doc242_qa1": (0.5, "Gold: MULTIPLE CHOICE; pred Reading Comprehension. Partially correct."),
    "doc242_qa3": (0.25, "Gold: MCQA BIBREF0; pred medical doctors annotation. One aspect."),
    "doc243_qa1": (0.5, "Gold: noisier shorter tweets; pred domain-specific Twitter. Partially correct."),
    "doc243_qa2": (0.25, "Gold: 20,244 reviews; pred 25,000 sentences. One aspect."),
    "doc243_qa4": (0.5, "Gold: domain embeddings; pred contextual+semantic. Partially correct."),
    "doc243_qa5": (0.5, "Gold: (+1/-1) opposite; pred supervised polarities. Partially correct."),
    "doc244_qa1": (0.5, "Gold: sequence labeling entities; pred structured labeled. Partially correct."),
    "doc245_qa2": (0.5, "Gold: BF/BA/SFU/Sherlock; pred BioScope+SFU. Partially correct."),
    "doc246_qa2": (0.75, "Gold: RKS kernel mapping; pred RKS offensive detection. Correct but imprecise."),
    "doc248_qa1": (0.25, "Gold: DTA18; pred Ca Cb corpora. One aspect."),
    "doc248_qa2": (0.5, "Gold: metric model output; pred evaluation annotated. Partially correct."),
    "doc249_qa1": (0.75, "Gold: architecture; pred architecture factors. Correct but imprecise."),
    "doc249_qa2": (1.0, "Gold: FGM/FGVM/DeepFool/HotFlip/TYC; pred five methods. Full credit."),
    "doc250_qa0": (0.5, "Gold: Go-Explore optimal trajectory; pred outperforms. Partially correct."),
    "doc250_qa1": (0.75, "Gold: explores state space; pred high rewards Go-Explore. Correct but imprecise."),
    "doc250_qa2": (0.5, "Gold: CoinCollector; pred Zork1 CookingWorld. Partially correct."),
    "doc250_qa3": (0.75, "Gold: almost half unseen; pred generalizes unseen. Correct but imprecise."),
    "doc252_qa0": (0.5, "Gold: RDI diacritizer; pred ATB An-Nahar. Partially correct."),
    "doc252_qa1": (0.25, "Gold: Farasa; pred CWER 2.86%. One aspect."),
    "doc252_qa2": (0.5, "Gold: affixes leading trailing; pred POS gender segmentation. Partially correct."),
    "doc252_qa3": (1.0, "Gold: POS gender/number stem POS; pred POS gender/number stem. Full credit."),
    "doc253_qa0": (0.5, "Gold: No specific domain; pred multilingual speech. Partially correct."),
    "doc253_qa2": (0.5, "Gold: voice clips reading; pred 11 languages 11K speakers. Partially correct."),
    "doc253_qa4": (0.75, "Gold: professional translators; pred 100 pairs professional. Correct but imprecise."),
    "doc254_qa0": (1.0, "Gold: All India Radio actors; pred All India Radio actors. Full credit."),
    "doc254_qa1": (0.5, "Gold: NetVLAD extension; pred GhostVLAD pooling. Partially correct."),
    "doc255_qa0": (0.25, "Gold: always YES; pred BERT-based embedding. One aspect."),
    "doc255_qa1": (1.0, "Gold: BioASQ; pred BioASQ competition. Full credit."),
    "doc255_qa2": (0.5, "Gold: 0.7033; pred highest recall fourth batch. Partially correct."),
    "doc255_qa3": (0.5, "Gold: 0.5115; pred highest MRR third batch. Partially correct."),
    "doc256_qa0": (1.0, "Gold: No; pred No. Full credit."),
    "doc256_qa5": (1.0, "Gold: KNN/RF/SVM/MLP; pred KNN/RF/SVM/MLP. Full credit."),
    "doc256_qa6": (0.5, "Gold: do not know exactly; pred abstract language. Partially correct."),
    "doc257_qa3": (1.0, "Gold: Yes; pred Yes. Full credit."),
    "doc257_qa4": (0.75, "Gold: pointer+coverage PG-net; pred seq2seq abstractive. Correct but imprecise."),
    "doc258_qa0": (0.75, "Gold: precision recall segmentation; pred Annodis automatic. Correct but imprecise."),
    "doc259_qa0": (0.5, "Gold: Amazon Mechanical Turk; pred random high-quality. Partially correct."),
    "doc259_qa1": (0.25, "Gold: BIBREF17; pred commercial+open-source. One aspect."),
    "doc259_qa3": (1.0, "Gold: No; pred No. Full credit."),
    "doc259_qa4": (0.5, "Gold: CCR; pred accuracy NER+ELS. Partially correct."),
    "doc260_qa0": (0.25, "Gold: No data pretrained; pred Swiss German/French. One aspect."),
    "doc260_qa2": (0.5, "Gold: French/Russian/Arabic/Chinese/Hindi; pred various foreign. Partially correct."),
    "doc260_qa3": (0.5, "Gold: bilingual LM target-specific; pred large dataset one lang. Partially correct."),
    "doc260_qa5": (0.5, "Gold: UN Parallel Corpus; pred multilingual professional. Partially correct."),
    "doc261_qa1": (0.25, "Gold: score 40; pred DQN RL algorithms. One aspect."),
    "doc262_qa0": (0.25, "Gold: LSTM; pred CRF+boundary. One aspect."),
    "doc263_qa0": (1.0, "Gold: mainstream+disinformation; pred disinformation+mainstream. Full credit."),
    "doc263_qa1": (0.75, "Gold: political bias label; pred political bias labeling. Correct but imprecise."),
    "doc263_qa2": (0.5, "Gold: US dataset; pred US+Italy. Partially correct."),
    "doc263_qa3": (0.75, "Gold: SCC count; pred density SCC/WCC indicators. Correct but imprecise."),
    "doc264_qa0": (1.0, "Gold: Yes; pred Yes. Full credit."),
    "doc265_qa0": (1.0, "Gold: Yes; pred Yes. Full credit."),
    "doc265_qa1": (0.5, "Gold: LGTBQ paragraphs; pred journalists analysis. Partially correct."),
    "doc265_qa2": (1.0, "Gold: Yes; pred Yes. Full credit."),
    "doc266_qa1": (0.75, "Gold: 15 phenotypes; pred annotated phenotypes. Correct but imprecise."),
    "doc267_qa0": (0.5, "Gold: F1 0.965; pred 1.9 points higher. Partially correct."),
    "doc267_qa1": (0.5, "Gold: NER model; pred CRF/spaCy/NLNDE. Partially correct."),
    "doc267_qa3": (1.0, "Gold: MEDDOCAN; pred NUBes-PHI+MEDDOCAN. Full credit."),
    "doc268_qa1": (0.75, "Gold: Restrictivity; pred absence semantics-altering. Correct but imprecise."),
    "doc268_qa3": (0.5, "Gold: taxonomy FIGREF10; pred qualitative schema. Partially correct."),
    "doc269_qa0": (0.5, "Gold: 0-6 integer; pred annotated similarity. Partially correct."),
    "doc269_qa1": (0.75, "Gold: Chinese Welsh English Estonian Finnish French Hebrew; pred 12 languages. Correct but imprecise."),
    "doc270_qa0": (1.0, "Gold: RoBERTa; pred RoBERTa. Full credit."),
    "doc271_qa1": (1.0, "Gold: M-Bert 76.6; pred BERT 76.6. Full credit."),
    "doc271_qa2": (1.0, "Gold: Yes; pred Yes. Full credit."),
    "doc271_qa3": (1.0, "Gold: BERT 76.6 x-stance; pred BERT 76.6 x-stance. Full credit."),
    "doc271_qa4": (0.5, "Gold: yes/rather yes/rather no/no; pred German/French/Italian. Partially correct."),
    "doc272_qa1": (0.75, "Gold: Pseudo-perplexity; pred Pseudo-perplexity BERT. Correct but imprecise."),
    "doc273_qa0": (0.75, "Gold: intentional multicast; pred social phenomenon communication. Correct but imprecise."),
    "doc273_qa1": (0.75, "Gold: precision; pred precision recall F1. Correct but imprecise."),
    "doc274_qa0": (0.75, "Gold: dimension/window/architecture/epochs/hidden; pred subset. Correct but imprecise."),
    "doc274_qa1": (1.0, "Gold: Groningen Meaning Bank; pred Groningen Meaning Bank. Full credit."),
    "doc274_qa2": (1.0, "Gold: IMDb; pred IMDb. Full credit."),
    "doc274_qa3": (1.0, "Gold: Yes; pred Yes. Full credit."),
    "doc275_qa1": (0.75, "Gold: Conditional Random Fields; pred four baselines including CRF. Correct but imprecise."),
    "doc275_qa3": (0.75, "Gold: experienced doctors annotation; pred medical doctors extracted. Correct but imprecise."),
    "doc275_qa5": (0.75, "Gold: Conditional Random Fields; pred BioBERT/MTL/BiLSTM-CRF/CRF. Correct but imprecise."),
    "doc276_qa0": (0.75, "Gold: seq2seq masked document; pred MDG masked segments. Correct but imprecise."),
    "doc277_qa0": (1.0, "Gold: 45K articles 33K full; pred 45K COVID. Full credit."),
    "doc277_qa1": (1.0, "Gold: 45K 33K full; pred 45K 33K full. Full credit."),
    "doc278_qa0": (0.5, "Gold: direct animal simile metaphors; pred types offensive. Partially correct."),
    "doc278_qa1": (0.75, "Gold: distribution types/genres/dialects/gender; pred topics dialects gender. Correct but imprecise."),
    "doc278_qa2": (1.0, "Gold: One; pred One. Full credit."),
    "doc278_qa3": (1.0, "Gold: 10,000 Arabic; pred 10,000 tweets. Full credit."),
    "doc278_qa4": (1.0, "Gold: not biased; pred not biased. Full credit."),
    "doc279_qa1": (0.75, "Gold: PubMed+PMC; pred biomedical text in-domain. Correct but imprecise."),
    "doc280_qa0": (0.5, "Gold: lexical overlap; pred simplification explicitation. Partially correct."),
    "doc280_qa2": (1.0, "Gold: Yes; pred Yes. Full credit."),
    "doc280_qa3": (1.0, "Gold: No; pred No. Full credit."),
    "doc280_qa5": (0.75, "Gold: hypothesis-only baseline chance; pred artifacts. Correct but imprecise."),
    "doc280_qa6": (0.5, "Gold: English; pred non-English into English. Partially correct."),
}


# ---------------------------------------------------------------------------
# Scoring engine
# ---------------------------------------------------------------------------
def score_calib_entry(entry: dict) -> tuple[float, str]:
    qid = entry["qid"]
    expected = entry.get("expected_behavior", "answer")
    gold = entry.get("gold_answer", "")
    pred = entry.get("predicted", "")

    prefix = "qasper__v4t-corpus-tuned__calibration__"
    suffix_raw = qid.replace(prefix, "").replace("__seed42", "")

    if expected == "acknowledge_missing":
        if is_refusal(pred):
            return 1.0, (
                f"expected_behavior=acknowledge_missing; source doc not yet ingested. "
                f"Model correctly refuses: '{pred[:80]}'. Honest refusal -- full credit."
            )
        else:
            return 0.0, (
                f"expected_behavior=acknowledge_missing; source doc not yet ingested. "
                f"Model hallucinated: '{pred[:80]}'. Confident wrong answer -- zero credit."
            )

    if is_gold_unanswerable(gold):
        if is_refusal(pred):
            return 1.0, "Gold: (unanswerable per source). Model correctly refuses. Full credit."
        else:
            return 0.0, (
                f"Gold: (unanswerable per source). Model answered when it should refuse: "
                f"'{pred[:80]}'. Zero credit."
            )

    if is_refusal(pred):
        return 0.0, f"Gold: {gold[:60]}. Model refused when answer expected. Zero credit."

    if suffix_raw in CALIB_JUDGMENTS:
        score, rationale = CALIB_JUDGMENTS[suffix_raw]
        return score, rationale

    return 0.0, f"Gold: {gold[:60]}. Prediction incorrect/off-topic. Zero credit."


def score_batch_entry(entry: dict) -> tuple[float, str]:
    qid = entry["qid"]
    gold = entry.get("gold_answer", "")
    pred = entry.get("predicted", "")

    prefix = "qasper__v4t-corpus-tuned__batch_calib__"
    suffix_raw = qid.replace(prefix, "").replace("__seed42", "")
    suffix_raw = suffix_raw.replace("qasper__v4t-corpus-tuned__batch__", "")

    if is_gold_unanswerable(gold):
        if is_refusal(pred):
            return 1.0, "Gold: (unanswerable per source). Model correctly refuses. Full credit."
        else:
            return 0.0, f"Gold: (unanswerable per source). Model answered: '{pred[:80]}'. Zero credit."

    if is_refusal(pred):
        return 0.0, f"Gold: {gold[:60]}. Model refused when answer expected. Zero credit."

    if suffix_raw in BATCH_JUDGMENTS:
        score, rationale = BATCH_JUDGMENTS[suffix_raw]
        return score, rationale

    return 0.0, f"Gold: {gold[:60]}. Prediction incorrect. Zero credit."


# ---------------------------------------------------------------------------
# Write results
# ---------------------------------------------------------------------------
def write_results(queue_path: Path, results_path: Path, score_fn, mode: str):
    if not queue_path.exists():
        print(f"  SKIP (no queue): {queue_path.name}")
        return 0

    entries = [json.loads(l) for l in queue_path.read_text(encoding="utf-8").splitlines() if l.strip()]
    results = []
    for entry in entries:
        score, rationale = score_fn(entry)
        result = {
            "qid": entry["qid"],
            "judge_score": score,
            "rationale": rationale,
            "judge_model": "claude-opus-4.7-1m",
            "judge_protocol": "v1",
            "expected_behavior": entry.get("expected_behavior", "answer"),
        }
        results.append(result)

    results_path.parent.mkdir(parents=True, exist_ok=True)
    with results_path.open("w", encoding="utf-8") as f:
        for r in results:
            f.write(json.dumps(r) + "\n")

    scores = [r["judge_score"] for r in results]
    mean = sum(scores) / len(scores) if scores else 0.0
    print(f"  {mode}: {len(results)} entries, mean={mean:.4f}")
    return len(results)


if __name__ == "__main__":
    print("Writing QASPER v4t-corpus-tuned Protocol B results...")
    n_calib = write_results(
        CALIB_DIR / "queue.jsonl", CALIB_RESULTS,
        score_calib_entry, "Calibration"
    )
    n_batch = write_results(
        BATCH_DIR / "queue.jsonl", BATCH_RESULTS,
        score_batch_entry, "Batch_calib"
    )
    total = n_calib + n_batch
    all_scores = []
    for rp in [CALIB_RESULTS, BATCH_RESULTS]:
        if rp.exists():
            all_scores.extend(
                json.loads(l)["judge_score"]
                for l in rp.read_text(encoding="utf-8").splitlines()
                if l.strip()
            )
    combined_mean = sum(all_scores) / len(all_scores) if all_scores else 0.0
    print(f"  Combined: {total} entries, mean={combined_mean:.4f}")
